### ISSUE TITLE
Add "/noclip" and "/reach" commands

### ISSUE THREAD

**Issue by DeathHammer000** [ForgeEssentials/ForgeEssentialsMain#1067]
Being that this mod is both a client-side and server-side utility mod, I would love to see noclip mode and the "/reach" command (allows the toggling of the reach distance of the player to help with building) added.

I moved from 1.6.4 to 1.7.10 to build a new modded parkour map - but a very popular commands mod, the now-defunct SPC, will not be ported to 1.6.4. It's been hard to build without the two commands (both of which were added by SPC), despite the features of WECUI and other mods like it.

I hope that these commands are added for the 1.7.10 version (and for 1.8 and up when Forge is released for it; spectator mode doesn't allow block placement).

Thanks.

**Comment by olee** [comment]
@luacs1998 IIRC you said `/noclip` works now, but what about `/reach`?

**Comment by luacs1998** [comment]
Haven't had time to investigate it yet, but will likely require an AT/mixins.

**Comment by olee** [comment]
@luacs1998 Think you can spend some time on this? This is a much requested feature and it would be nice to get this working properly...

**Comment by luacs1998** [comment]
I got you /noclip already, but as for /reach, I ran into a little problem.

Forge is nice enough to add getters and setters for the reach distance, but the thing is, if I use that, it applies to the *whole server*. Not sure you guys want that.

**Comment by olee** [comment]
probably not...
Now that you say that I remember having problems with that when I was writing on my own new mod.
I took a look at the raytracing function on the client and I saw that it has hardcoded values for the distances. That means to get this working we will need to overwrite that function to make it dynamic on **client side**. This means we would need an AT on the client side. I could provide you with the function and the lines that need to be added and you could write the AT for that. Or the other solution would be to add Mixin to the FE client mod. Your call.

**Comment by luacs1998** [comment]
Do we need ATs? Can we reflect?

**Comment by olee** [comment]
"...  hardcoded values ..."

**Comment by luacs1998** [comment]
Done by @olee

**Comment by DeathHammer000** [comment]
Kinda ironic how I've moved off of Minecraft now...

**Comment by olee** [comment]
Well then just get back! :smirk:

**Comment by DeathHammer000** [comment]
One day...

...one day, I will return...
