### ISSUE TITLE
[multiworld] Backup going crazy when creating end-world

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1171]
Ok this was really weird.
When I created a end-multiworld, and joined that world, the backup module always went crazy and repeatedly tried to backup dimension 1 (which wouldn't be the multiworld, but the default end-dim).
This was really weird and because my server became unusable, I had to kill the server. Stopping it with `/stop` or ctrl+C was only possible once - the other times I had to send SIGKILL.

This needs to be investigated ASAP.
We might even need to disable creating end-worlds for the moment.

**Comment by luacs1998** [comment]
Is this still an issue in the latest builds?

**Comment by olee** [comment]
I didn't test it for a while now, but I don't think it's fixed.
I will try to test it once I have a bit more time, but that will probably take a while.
