### ISSUE TITLE
Multiworld feature requests

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1175]
Copied from pastebin http://pastebin.com/z7qn98pJ

Multiworld Portals
- New world of random type
 - Possible types configurable (so can exempt flatland for exp)
- Existant world by config
 - (examples;
 - Visited - Allows players to return to any world they've been to
 - None - Players cannot return to worlds
 -  Block - Identify a block that if a player has placed it, they can return to that world
  - (exm, I would make a PortalBeacon block (or you could provide it if you want))
  - (who can remove the block,
  - if it's removal removes the world from everyone's list,
  - and wether the block needs power/how much
  - is not your prob if you don't add the block) (though the extra functionality might be a nice long term goal...)
 - Block/Interact - If a player interacts with the identified block that was placed by another player, they can also return to that world
 - Item - Identify an item that if a player uses the item on a world, they can return
                        (exm, A log/scanner item
 - Block/Item - Identify a block and an item. The block acts like a beacon for that world and the item is the player's record of beacons.
                        (exm, A player places a beacon and logs it, any later player may log it also
- Public worlds
 - Server can make worlds that are essentially permanant by simply listing them in the config which puts them into everyones list. (alternately you could make a block that can store beacon codes so that players can trade them using the block/item configured)
 
- AutoDelete -
 - If 0 then off
 - If 1 then any world which no one has linked, is auto deleted to save server space
 - If >1 then retained for X days after last online of a player who has access to that world (remember to include access for admins but exclude it from this check (if you decide to implement this) :D )
 - If <0 then deleted after X days of no access regardless
 
Implementation suggestions (up to you!)
        When a player visits a new world, it's stored in a special directory. If they do whatever the server requires to be able to return, it's moved to the regular dir.
 
The idea here is that you can create a portal that is temporary, like a stargate or wormhole, it closes after X seconds after use. A new portal can be opened in the same frame but to any location to which the player opening the portal has access. If a player want's to invite someone else to a world they've visited, they may open a portal and anyone who goes through while it's open goes to the same place, even a new world.
 
Example config
 
a_portal_types:{nether_style,on_demand}
        //on_demand being the type defined above
        //nether style being normal portals made of worldtype specific blocks?...
i_onDemandOpenTimout:25 //seconds sounds resonable
i_openPortalCooldown:300        //prevent trolls blocking portals
a_revisit:{block-item,public}
s_revisitBlock:{custom:portalBeacon}
s_revisitItem:{custom:portalLog}
i_playerRehome:0
        //Player sleeping on a new world does NOT get their home reset (this would be achievable by simply turning off beds reseting spawns altogether EXCEPT that you might want the to be able to respawn on worlds they have earned access too (or as string)
        // 0 = reset regardless
        // 1 = reset if accessible by above rules
        // 2 = never reset player spawn
i_autoDelete:22 //so if someone takes a couple weeks off, no biggie

**Comment by olee** [comment]
I think we should close this for now.
We got all major features for multiworld done and if there is anything people want to have added, please open a new separate issue.
Even then new features for multiworld will probably have to wait for the 1.8 port.
