### ISSUE TITLE
World Border Kickback issue

### ISSUE THREAD

**Issue by Cuppycake** [ForgeEssentials/ForgeEssentialsMain#1176]
FE Version1.4.0-beta2-servercore

Issue:

With world border enabled and kickback enabled the user crosses the world border and instead of getting kicked back the user gets teleported to build height where they fall to their death in an endless loop. If they don't get trapped in this death loop they get teleported under bedrock and fall out of the world.

**Comment by olee** [comment]
Want to take a look at WorldBorder these days.
Will check this at the same time.

**Comment by evernife** [comment]
offtopic, but, a player who was in a boat triend to croos the border line, and get kick from the server, and couldn't connect again, i have to deactivate the borders to let him join.

**Comment by olee** [comment]
Do you have any log message?

**Comment by evernife** [comment]
No sorry. I will try to get some.

**Comment by evernife** [comment]
Here it is: http://pastebin.com/YpahsX9L

**Comment by olee** [comment]
Yeah looks like some bug... will probably be gone once I finish new WorldBorder

**Comment by KaneHart** [comment]
This is fixed Now "Topic" can be closed.

Proof: https://www.youtube.com/watch?v=EI-WEwvNr0s

**Comment by evernife** [comment]
I will test the "BOAT" bug.
