### ISSUE TITLE
Restore functionality of /setspawn

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1183]
The setspawn functionality, as a part of teleport, should **NEVER** be in the /feperm command. /feperm is too complex, and such superfluous things only add to its complexity.

/p user|group spawn should be moved back to /setspawn, where it belongs.

Clean up your mess.

**Comment by luacs1998** [comment]
@Malkierian the spawn and home can differ between users. For example, a user can set /home to the entrance hall of his house, but set his spawn to his bedroom, for example. This is if the server admin decides he can be trusted not to use the main spawn for his assigned group. Or perhaps we should add a "home" argument as well that sends a player to their home location?

@olee the reason why I want FE spawn handling to be cleanly disabled is because don't you think it's troublesome if you want to disable something, you have to clear the setting then reset it? Spawn handling is already in teleport. No reason why setting it shouldn't. 

It'll also help to reduce the clutter in /feperm, which while powerful, due to the sheer amount of possibilities it allows can be daunting to the end user.

**Comment by olee** [comment]
/feperm is actually not that big. It has only permission commands (allow, deny, etc) and prefix + spawn.
The other subcommands it has are only for listing stuff.
I will try to finish that issue here once I have some time again.
