### ISSUE TITLE
Reduce worldborder message frequency

### ISSUE THREAD

**Issue by RedFox071** [ForgeEssentials/ForgeEssentialsMain#1185]
Not so much of a bug as a request but when using a second stage in the worldborder module if the first stage is a warning there is a lot of chat message spam. Something like a few times a second while the player is moving. It is definitely very visible but it seems like it is a bit too much. If the message was sent once per block that would probably be enough.

**Comment by luacs1998** [comment]
This should be closed with the new worldborder module.
