### ISSUE TITLE
Fake player permissions

### ISSUE THREAD

**Issue by Trakaa** [ForgeEssentials/ForgeEssentialsMain#1187]
My server has several mods that utilize fake players. (SEE: Thermal Expansion) When I promote them it does not seem to give them the permissions they need. For example the '/p user [CoFH] group set Members' succeeds, but the blocks that require permissions to interact or break blocks do not work. 

When I allow Guests to have all permissions the blocks will work as intended.

**Comment by luacs1998** [comment]
On further investigation, fakeplayers aren't given UUIDs. We'll have to give them UUIDs on our own part.

**Comment by olee** [comment]
Is the UUID so.th. like "000-000-..." or null? If one of those two conditions are met we could generate a UUID from the username (hash) to be used.

**Comment by olee** [comment]
Should be fixed together with #1265.
If there are any more problems, please report.
