### ISSUE TITLE
Economy/plots requests

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1189]
Mainly to make plots more versatile.

Economy:
- [x] Allow players to earn currency by gathering XP (optional) (default 10XP : 1 currency)
- [x] Allow players to sell items to the server or other players for income (configurable by server admins)
- [ ] A way for players to trade items (already implemented for plots, should be easy enough to implement for items)
 - Allow players to right click other players to request a trade (opens a GUI, may require client mod)

Plots:
- [ ] Automatic permission management for plots
 - Plot owner, on confirmation of ownership, should be given as much permissions within his plot as the server admin is prepared to give him
 - If a player stops owning a plot, his permissions within the plot should be revoked, and ownership permissions given to the new player
- [ ] More versatile plot setting (for example, select an area and subdivide it into many smaller plots)
- [ ] Implement rentals
 - Players are to pay rent for plots of which they are registered as the owner
 - Payment can be either manual or automatic, the plot-owner can be nagged on rent payments
 - Interval between rent payments can be configured, will be the same for everyone on server (hourly? daily? weekly? monthly?)
 - Should a player not be able to pay his rent on time, he will be given a certain amount of time (configurable by server admins) to raise the money and a late-payment penalty (also configurable by server admins). After the time has elapsed, he will lose plot-owner permissions, but still be registered as the owner.
- [x] Implement purchasing of plots (partially done)
 - to be turned on by server admins
 - players are only allowed to claim up to X size of land
 - want a higher allowance? pay the server more money (can be turned off by server admins)
 - increasing allowance should be capped, to prevent abuse
- [x] Server admins should be able to repossess plots and resell them on the market
 - ~~The plot owner will be compensated if the plot is a purchase (configurable)~~
- [x] Automatic plot valuation (surface area of plot x admin-defined multiplier)
- [ ] Plot expansion and shrinking (may be a bit difficult)
- [ ] Entry fees for plots (with appropriate fee-setting, whitelisting, etc)

[Current draft (probably needs to be updated)](https://docs.google.com/document/d/1e_ao4uTxJgtNtbMU4Tj5LZRrGIPoYHmzlFFc10nqPpQ/edit#heading=h.6fkq9qbylm4p)

**Comment by luacs1998** [comment]
After a long hiatus, work will continue on the feature_improveplots branch.

**Comment by Flukethoughts** [comment]
so how is this progressing?

**Comment by olee** [comment]
Sorry, some work from me needed in order for @luacs1998 to continue so it's probably my fault plots got a bit deplayed. Will work on this soon.

**Comment by Flukethoughts** [comment]
thats fine it's just good to hear you guys are still doing your thing.

**Comment by olee** [comment]
Off topic: @Flukethoughts you should be on IRC more often again!

**Comment by evernife** [comment]
I do not understood this well, but, how people will create plots?
I can remember of a really good protection system called "GriefPrevention". If this plots system are like theyir "Claim"s would be really nice, in fact, controlling the range of your land will be really good. And should finde a easy way to expand the area, without commands. (MyTown uses a "Selector", Griefprevention uses a "Gold Shovel")
Just with this i can't take a measure of the plots system.

**Comment by Flukethoughts** [comment]
greifprevention is still in production in a different fork for 1.7.10 and fe will soon catch up in the game when the plot system is finished that's when we get to come in and make good suggestions on how we want it to work and the ability it should have. The FE team builds for the users not the man lol

**Comment by olee** [comment]
I worked 16 hours on plots and economy yesterday :laughing: 
But it's working really good now - it's just that there are still features missing.
The new plot system will allow real trading of land and some other cool stuff.
If everything goes well, you will get a PR with first plots feature tonight (in about 10h maybe?).
