### ISSUE TITLE
[Chat] Auto Message Causes Main Thread to Hang.

### ISSUE THREAD

**Issue by KaneHart** [ForgeEssentials/ForgeEssentialsMain#1202]
I can't tell you what is exactly happening. It works 100% fine I have 3 lines with just a basic message no colors etc. Every 60 Minutes one of the 3 messages are displayed in the order and not using Randomize message orders.

About 1 Second sometimes 2 Seconds before the message everyone Mining or doing activity that requires server packet to the client stalls out and then of course catches up after the message shows up on the client side.

I assume it's the main thread hanging and this is with just 2-3 people online not 100's.

**Comment by luacs1998** [comment]
Get me profiler results.

**Comment by KaneHart** [comment]
Let me know when you have and feel free to share them with us ;)

**Comment by luacs1998** [comment]
Well, since you're not going to show me how it lags, I'm taking this as a non-issue ;)
