### ISSUE TITLE
FeatureRequest: Add the command trim to world border

### ISSUE THREAD

**Issue by BakermanLP** [ForgeEssentials/ForgeEssentialsMain#1206]
Hello,
I am absolut impressed about ForgeEssentials . Most needed plugins are already builtin. That's great.

Can you pleas also include the trim command to delete chunks or only mca files behind the worldborder?

That would be absolutly great!
Thanks

Michael (aka BakermanLP)

**Comment by luacs1998** [comment]
Worldborder is scheduled to be reworked in a future update around the time of MC 1.8. It may be done, it may not.
