### ISSUE TITLE
[economy] Sell-command not working

### ISSUE THREAD

**Issue by Flukethoughts** [ForgeEssentials/ForgeEssentialsMain#1222]
Shop sell command don't work if there is a sub Id
Ex 1251:5 
This issue wont allow selling of certain items in certain mods.

**Comment by luacs1998** [comment]
Known - whoever came up with the sellcommand syntax is a moron

**Comment by Flukethoughts** [comment]
Is there any fix for it currently?

**Comment by Flukethoughts** [comment]
still can't get it to work I also don't know if honestly a Fe problem but should be looked into

**Comment by DarkAxi0m** [comment]
fyi, I got it to work with, add to add the 0 
`/sellcommand @p 17 32 0 /addtowallet @p 1`

**Comment by luacs1998** [comment]
So it's settled?

**Comment by guitarguy1133** [comment]
might wanna edit the wiki to reflect
