### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Xee1** [ForgeEssentials/ForgeEssentialsMain#1224]
On every startup appear this error in console:
http://pastebin.com/NxnQ2tHj

And on closing:
[18:56:48] [Thread-164/ERROR] [FML/ForgeEssentials]: Protocol error. Ignoring packet

**Comment by olee** [comment]
Known problem with WorldEdit integration. Should be fixed soon.
What's the status about it @luacs1998 ?

**Comment by luacs1998** [comment]
Use the fixed WorldEdit. @olee give him a link, I'm on mobile.

**Comment by olee** [comment]
I don't have the link. Couldn't we update the bundeled WE version in FE?? Why is it still the old one anyway?

**Comment by luacs1998** [comment]
Because I havent found a way to update it myself in a buildscript-compatible way?

http://www.mediafire.com/?g8dfjkwhawzpfrh

**Comment by Xee1** [comment]
Thanks now work! Oh, FE download worldedit 6.0.1 , this create a lot of error! (Example: If i break a block I have one long error in console!)

**Comment by luacs1998** [comment]
You need to replace the WorldEdit jar in your mods folder.

**Comment by Xee1** [comment]
Yes, I've made this, my comment is just an information
