### ISSUE TITLE
Issues with some commands

### ISSUE THREAD

**Issue by Flukethoughts** [ForgeEssentials/ForgeEssentialsMain#1226]
~~Certain Signs like !@#$%^&*()_ can crash the game~~
~~/afk does not work~~
/vanish does not work
/Zone Info does not work
I will list others as I get to them

**Comment by RlonRyan** [comment]
First issue is the same as #1242.

**Comment by luacs1998** [comment]
/vaish is known to be not working - the mechanism broke between 1.6 and 1.7. I'll have to either remove it or re-implement a netty based mechanism.

**Comment by olee** [comment]
Closed in regards to #1346

`/are info` has already been fixed.
