### ISSUE TITLE
Prefix under _OPS_

### ISSUE THREAD

**Issue by Flukethoughts** [ForgeEssentials/ForgeEssentialsMain#1228]
unable to disable Prefix no matter how many times I set it to clear.

**Comment by Cuppycake** [comment]
Yep Ive tried everything. I'm creating a new group called Staff. Even after removing the members from _OPS_ they still have an [OPERATOR] prefix as long as they are in the op list.

**Comment by luacs1998** [comment]
Oi @olee who hardcoded the prefixes? https://github.com/ForgeEssentials/ForgeEssentialsMain/blob/a1ac8b0bdb9b881c0f2e344f77fcef4e216b0f6c/src/main/java/com/forgeessentials/api/permissions/ServerZone.java#L56

**Comment by olee** [comment]
Hm that should have been default values only...
Clearing the _OPS_ prefix should be possible, by setting it to an empty value currently (which is not possible iirc with `/p` at the moment...
Need to think of a solution.

For now try going into the permission file and set the value for prefix to an empty string.

**Comment by Flukethoughts** [comment]
still it reverted back
