### ISSUE TITLE
Version 1.6.4 had a default group setting

### ISSUE THREAD

**Issue by Flukethoughts** [ForgeEssentials/ForgeEssentialsMain#1229]
This is not the case for 1.7.10 in the future I would prefer to chose what group is default.

**Comment by Malkierian** [comment]
I think changing the default group has already been discussed, and we have a few ideas of how to handle it. However, in the mean time, you can still change the prefix and suffix and such for the _GUESTS_ group, which is the default.

**Comment by Flukethoughts** [comment]
which then is reverted back to Guest

**Comment by Malkierian** [comment]
How and when are you changing out?

**Comment by olee** [comment]
You have the default group `_GUESTS_`.
If you want to be able to change it quickly, just make a new group and include it from `_GUESTS_`

````
/p group my_guest create
/p group _GUESTS_ include add my_guest
````
