### ISSUE TITLE
Permission critical error

### ISSUE THREAD

**Issue by Flukethoughts** [ForgeEssentials/ForgeEssentialsMain#1234]
If this is the perms for the group why does the group have the abilite of fe.perm and other stuff. serious issue please fix.

fe.internal.group=true
fe.internal.group.priority=20
fe.internal.prefix=&2Members
fe.protection.break.tile.chickenChunkLoader=false
fe.protection.interact.tile.chickenChunkLoader.*=false
fe.protection.inventory.tile.chickenChunkLoader.*=false
fe.protection.place.tile.chickenChunkLoader.*=false
fe.protection.place.tile.computercraft\:turtle.*=false
fe.protection.place.tile.machineBlock.0=false
fe.protection.use.item.railcraft.cart.anchor.*=false
fe.teleport=true
fe.teleport.personalwarp=false
fe.teleport.warp=true

**Comment by olee** [comment]
You probably have set other permissions incorrectly.
Try `/p debug` and then use `/p`.
It will show you which rule applies to allow you use of `/p` or other commands.
