### ISSUE TITLE
WorldEdit permissions

### ISSUE THREAD

**Issue by Flukethoughts** [ForgeEssentials/ForgeEssentialsMain#1235]
I can deny mc. and fe. but where is the world edit function so i can deny // 
Superpick axe gives users the ability to destroy objects even when the perm says no to break.block.*

**Comment by helinus** [comment]
WorldEdit perms are somehow not registering in at least build 360

**Comment by olee** [comment]
That's @luacs1998 fault in a way...
FE has updated code for WE-permissions, but the WE version bundeled is not the correct one iirc.
Before all WE-command permissions worked without any problems :neutral_face:

**Comment by helinus** [comment]
I've tried with his fixed version of WE and they're still not regestering

**Comment by Flukethoughts** [comment]
Very Much still an issue

**Comment by luacs1998** [comment]
Are you using the permission nodes registered on sk's wiki?

**Comment by olee** [comment]
So the registration of WE commands is now performed by WE-forge like default and not by our WE-integration? That would explain why the permissions are not showing up.

@luacs1998 Please check these [lines](https://github.com/ForgeEssentials/ForgeEssentialsMain/blob/develop/src/main/java/com/forgeessentials/compat/worldedit/WEIntegrationHandler.java#L31-L33
). That commented line there looks a bit wrong...

**Comment by luacs1998** [comment]
Yes, command handling is now done by WEForge.
@olee the commented out line is commented out for a reason...

Reopen if there are still issues.
