### ISSUE TITLE
Issue with graves not being accessible

### ISSUE THREAD

**Issue by Flukethoughts** [ForgeEssentials/ForgeEssentialsMain#1237]
Issue submitted to my server

This was submitted to my server just thought I would update you on it.

Hello everyone, I usually am not one to complain, and I'm sure you all heard of these issues before, but I thought I'd state them thoroughly.

Problem 1: On the server, the graves are a skull on top of a fence post. I died once, all I had to do was walk up to it, not morphed, and right click it with an empty hand. Once I removed everything, the head disappeared. Everything worked out perfectly.

However the second time I died, I found my grave, and I met all the conditions I explained above, except when I right clicked the skull, it didn't open. I right clicked it many times, and it didn't open. I left clicked it, I right clicked it, and eventually I just broke it, and it dropped a regular skeleton skull. I never got any of that stuff back, and even though it wasn't very valuable, what happens when I die with something valuable?

Thanks for reading, KLuebbert

**Comment by RlonRyan** [comment]
Not very much to go on... Is there a proven way to reproduce the issue?

**Comment by RlonRyan** [comment]
I am thinking that this is the same issue as #1255. As #1255 provides more information on the error I am closing this issue in favor for #1255.
