### ISSUE TITLE
Easy item ban command

### ISSUE THREAD

**Issue by Flukethoughts** [ForgeEssentials/ForgeEssentialsMain#1238]
While Item in hand you would run command
/banhand
And it would do 
/p Global deny fe.protection.use.######
/p Global deny fe.protection.Inventory.######
/p Global deny fe.protection.place.######
/p Global deny fe.protection.break.######
/p Global deny fe.protection.interact.######

**Comment by luacs1998** [comment]
I haven't implemented parameters for command scripts yet. Maybe later.

**Comment by olee** [comment]
I suggest adding this to `/itemperm` command as `/itemperm ban` subcommand. Would just need a few added lines then.
