### ISSUE TITLE
Alot of issue

### ISSUE THREAD

**Issue by Flukethoughts** [ForgeEssentials/ForgeEssentialsMain#1239]
Alot of commands are enabled globally 
/craft i will add others.

**Comment by olee** [comment]
With "globally enabled" - do you mean the default permission is set for everyone to be able to use them?

PS: Please start adding proper titles and descriptions to your issues or I'd rather close them directly before trying to understand them.

**Comment by Flukethoughts** [comment]
there are issues with commands being available to regular users by default. Like /craft /superpixaxe and others. I don't report bugs all the way because either way most of the time you ignore them and close them before the issue is fixed.

**Comment by Cuppycake** [comment]
Your comment is pretty ignorant. This is an open forum to help fix issues by bringing them to the dev team's attention. These tickets should be as clear and concise as possible as to not waste time deciphering what might be wrong. 'Alot of issues'  isn't a great way to title your ticket. Then upon looking at the ticket you vaguely describe a single issue. Tossing out tickets here should be reserved for detailed reports on issues. Not as if we're just BSing in IRC.

**Comment by olee** [comment]
@Cuppycake Thank you very much! It's great to have people around that understand that we are doing all work in our free time for the community.

@Flukethoughts Why didn't you just give a proper explanation like that from the beginning?

Anyway about your problem: There is nothing **WE** can do about that.
It's the mod's fault for making these commands allowed for non-OP players.
You will need to configure the `mc.craft` or `mc.superpickaxe` permissions - or however they are called - manually with permissions.
