### ISSUE TITLE
Switch to mumfrey's Mixin system for event injection

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1243]
When Mixin stabilizes, we should implement it in place of the current system that we have.

The reason is because Mixin seems to be more versatile and doesn't require us to go wading deep into asm as the current system does (not that I don't like you, @matthewprenger , but...)

This will most likely happen as part of the port to MC 1.8.

**Comment by matthewprenger** [comment]
Yeah ServerTools doesn't actually use the ASM system I wrote. It's still on the old one. I'm going to either move to mixin, get a hook into forge, or rewrite it once again.

**Comment by luacs1998** [comment]
Mixin has become more mature over time, but I've been told it's still not mature for primetime yet.

**Comment by luacs1998** [comment]
Moved to PR #1314
