### ISSUE TITLE
Zones not working with perms

### ISSUE THREAD

**Issue by Linrox** [ForgeEssentials/ForgeEssentialsMain#1244]
I have found a some issues with zones and perms
1. with debug mode on, zones do not register that the player has entered into a zone as it still shows _root_ zone in the debug info and the _all_ group.
2. when a perm is set within a zone with /p group zone deny/allow perm it has no effect but if the zone is omitted and it defaults to _server_ then the perm takes effect on all (in and out of zone)

**Comment by olee** [comment]
- 1. Debug mode does not show the zone you are in, but the zone which the permission result was taken from.
- 2. You probably just used the commands incorrectly or didn't set the zone-area correctly.

**Comment by Linrox** [comment]
on #1 issue. fair enough
on #2 issue, i don't think so, but if that is the case then the wiki is wrong too.

after creating the group member and the zone i have tested it by adding a entry msg, which works. 

I then have tried both of these while in the zone.
  (1)    /p group <groupname> zone <zonename> allow or deny perm 
            (e.g  /p group member zone testzone deny fe.protection.break.tile.*) i have also tried _ALL_ instead of *
  (2)    /p group <groupname> Allow or deny perm
            (e.g  /p group member deny fe.protection.break.tile.*) i have also tried _ALL_ instead of *
            This one applies it to the default of _SERVER_ zone
  
 if i do (1) then nothing happens, e.g if it is a deny break, i can still break 
 if i do (2) then it works but everywhere in that world.
 
 If i am using them incorrectly, i can except that, but it is not then clear on how the perms/zones work together
 
 I really would like to understand and get the zone/perms working so i can do a vid tut for everyone else.
 if i could get a little help from you olee with this it will benifit you guys in the longrun.

**Comment by Linrox** [comment]
Thanks you Fluke for you personal help. very much appreciated. :)
Shame WE integration still has so many issues

**Comment by Flukethoughts** [comment]
Worked with linrox on this issue. Worldedit has an issue with creating zone. I have tested this myself countless times. 

When world edit is installed you can't do a few commands

**Comment by olee** [comment]
I will just quote myself here:
2. You probably just used the commands incorrectly or didn't set the zone-area correctly.

I thought that it was probably the second - because of @luacs1998 changes with WE-permissions, WE-integration does not work currently and you have to use `//fewand` to have usable selections.

**Comment by darkmdbeener** [comment]
does //fewand not work when world edit is installed?

**Comment by luacs1998** [comment]
Yes, you can use the WorldEdit //wand instead. FE is notified of selections made through WorldEdit.
