### ISSUE TITLE
Is Fe dead?

### ISSUE THREAD

**Issue by Flukethoughts** [ForgeEssentials/ForgeEssentialsMain#1245]
I haven't seen much activity in Fe lately just wondering If it's dead and we are in limbo until sponge?
no offence is meant.

**Comment by luacs1998** [comment]
Let's not start this debate again.

**Comment by olee** [comment]
I have stuff to do for work and university and it's the same for luacs IIRC so no wonder that FE-development has a slight decline right now.
If there's _important_ bugs to fix though, just ping me enough on IRC and I will see to fix them.

**Comment by RlonRyan** [comment]
:squirrel:

**Comment by liach** [comment]
When will the wiki be updated? I want to see more information about Questioner Module.

**Comment by luacs1998** [comment]
@liach Questioner module is gone. It shouldn't even be a module to begin with.
