### ISSUE TITLE
Request: Pre-generate a world

### ISSUE THREAD

**Issue by Sunconure11** [ForgeEssentials/ForgeEssentialsMain#1246]
Do you think it would be possible to add a command to allow one to pre-generate their world?

**Comment by olee** [comment]
Already exists in FE, but it had some problems a while ago. Has been fixed IIRC though.

**Comment by Sunconure11** [comment]
What is the command then?

**Comment by olee** [comment]
`/filler` should do it.
--> https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/World-Border%20Module
