### ISSUE TITLE
Suggestion: Clear dropped items on a regularly basis

### ISSUE THREAD

**Issue by Sunconure11** [ForgeEssentials/ForgeEssentialsMain#1248]
Can we add one of the abilities from the ClearLagg plugin, which is clearing dropped items, as well as other entities if needed, on a regularly basis? If it is already in the mod, how do I use it?

**Comment by luacs1998** [comment]
It isn't implemented per-se, but you can hack around by using timed commands from the scripting module to call /butcher.

**Comment by RlonRyan** [comment]
Does the wontfix tag really apply here?

**Comment by luacs1998** [comment]
Seems like this is a dupe of #1132 - but since I closed that, ya...

**Comment by olee** [comment]
As already said, use a scheduled command.
FE may be powerful, but we can't do any small feature where there are other solutions for it.
