### ISSUE TITLE
Random server crash, seems to be related to StorageManager

### ISSUE THREAD

**Issue by halvors** [ForgeEssentials/ForgeEssentialsMain#1251]
Random server crash, seems to be related to StorageManager. Happends randomly and i don't know what is triggering this.

http://pastebin.com/eQUZLGRm

**Comment by luacs1998** [comment]
Alright @olee, you win. You have my permission to remove the old data saving system and move to your new one.
That should fix this.

**Comment by olee** [comment]
Finally... thanks.

**Comment by olee** [comment]
Removed in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/aea8d804fb6d172c3ca104a5b5dfb8d7ad2c725f
