### ISSUE TITLE
Database table blockChange's player field is to small for player UUID.

### ISSUE THREAD

**Issue by halvors** [ForgeEssentials/ForgeEssentialsMain#1254]
Database table blockChange's player field is to small for player UUID.

**Comment by luacs1998** [comment]
Whoever wants to fix this can fix this. But seeing as playerlogger is due for a rewrite by @Malkierian I'm not going to.

**Comment by Goten87** [comment]
that can fix it eazy them self if that have phpmyadmin in there just edit the player field to hold 255 chars and your good thats what i did

**Comment by Goten87** [comment]
this is fixed now so can be closed
