### ISSUE TITLE
Permission system reload restores cleared prefixes

### ISSUE THREAD

**Issue by kerts93** [ForgeEssentials/ForgeEssentialsMain#1258]
When you remove prefix from _OPS_ and _GUESTS_ with prefix clear, it restores them with next permission system reload.

Confirmed in versions:
Beta 3
Beta 4 (http://198.23.242.205:8080/job/ForgeEssentials/lastSuccessfulBuild/artifact/build/libs/forgeessentials-1.7.10-1.4.0-beta4-server.jar/ - downloaded on 23.01.2015 11:30 (GMT+2).)

**Comment by kerts93** [comment]
That also includes server restart.

**Comment by luacs1998** [comment]
Try running /p save after you clear the prefixes.

**Comment by kerts93** [comment]
Triied it, no change.

**Comment by kerts93** [comment]
Few notes:
- I ran the permissions in file-based system
- At least when using version Beta 5 build 393 when using MySQL, it saves it and keeps it clear when you manually save after clearing prefixes.

**Comment by olee** [comment]
Could it be you completly removed all permissions from the group?
The default-prefix and other defaults are only set if the group does not exist at all [(see here)](https://github.com/ForgeEssentials/ForgeEssentialsMain/blob/develop/src/main/java/com/forgeessentials/permissions/core/ZonedPermissionHelper.java#L285-L313)
The code checks, if the groups already exist. If not and only then the defaults will be added.

**Comment by kerts93** [comment]
Nope, I certainly had permissions in _GUESTS_ group. I didn't make any changes in _OPS_ group though - these are the 2 groups that had the issue.

**Comment by luacs1998** [comment]
I seem to be encountering the same problem. You need to manually save permissions after clearing prefixes, in order for the clear operation to stick.

**Comment by olee** [comment]
I tested it myself right now and even without manually saving, it works.
Just start up your server and run the following commands:
```
/p group _OPS_ prefix clear
/p group _GUESTS_ prefix clear
```
And optionally you can run `/p save` to save permissions immediatly.

Even after restarting the server, the prefix won't reapper (tested with latest build).
