### ISSUE TITLE
Item commands request

### ISSUE THREAD

**Issue by CourtArtanis** [ForgeEssentials/ForgeEssentialsMain#1262]
Hi,
In Bukkit Essentials you could type /i cobble - and it'd give you a default amount of cobblestone (set to 64 in config) It'd only work for Vanilla items though, which was still useful for patching holes and just general admin.

Currently the /i or /item command doesn't exist (to give yourself the item as a command since it's quicker than NEI)

and

Item shortnames, so typing cobble will automatically complete to cobblestone (tab doesn't work)

Thanks :)

**Comment by helinus** [comment]
I think the vanilla /give command covers all of what you requested: http://minecraft.gamepedia.com/Command#give
