### ISSUE TITLE
GC command request

### ISSUE THREAD

**Issue by CourtArtanis** [ForgeEssentials/ForgeEssentialsMain#1263]
Hi,

Typing /gc command using either Cauldron (Or maybe just Bukkit/Essentials?) would give you an overview of server resources; allocated/used/free RAM, TPS, chunks loaded and memory usage per dimension. Among resource monitoring, It's a good overview of which worlds are loaded when they shouldn't be, and to spot sneaky chunkloaders and irresponsible usage.

Is this something which would be add-able to ForgeEssentials?

**Comment by luacs1998** [comment]
This is already partially implemented - use /perfstats or something.

The rest can be found in Forge's native TPS command ( /forge tps )

**Comment by CourtArtanis** [comment]
You can use TPS and forgetps but perfstats didn't work and I couldn't find it's derivative :\

**Comment by helinus** [comment]
@CourtArtanis update to FE build 370 or later as perfstats is fairly new command

**Comment by luacs1998** [comment]
If what we have isn't enough, consider opis.
