### ISSUE TITLE
[Question] seperated API and Locolization request

### ISSUE THREAD

**Issue by liach** [ForgeEssentials/ForgeEssentialsMain#1264]
I think ForgeEssentials may develop an API for some mods to use. I don't think it's very nice to build mods with fe downloaded. And locolizations for players?

**Comment by luacs1998** [comment]
We experimented on player localizations a while back and it turned out to be a disaster.

FE's API is too intertwined with the rest of FE to be separated out. You shouldn't be downloading APIs anyway - you should resolve FE via maven.

We're on the Forge maven repo, com.forgeessentials:forgeessentials:1.4.0-SNAPSHOT

**Comment by liach** [comment]
Localization in UTF-8 turned to be ASCII? That's poor.

**Comment by luacs1998** [comment]
No, it's the fact that

- Our localizations project never took off, it was in XML and too hard to edit, devs also forgot to update locale files when adding new features

- FE, as a server-only mod, has no way I know of to find out what locale a client is in. So, we were just localizing everything to English (US) and sending it to the clients,

**Comment by liach** [comment]
> FE's API is too intertwined with the rest of FE to be separated out. You shouldn't be downloading APIs anyway - you should resolve FE via maven.

How about adding a task called `apiJar` which extracts `com/forgeessentials/api`, `com/forgeessentials/util`, `com/forgeessentials/commons/selections`, `com/forgeessentials/core/moduleLauncher/FEModule.java` and`com/forgeessentials/core/moduleLauncher/ModuleContainer.java`? This prevents mods from being ForgeEssentials addons, and they could run without FE when shipping the api, keeping their ability to interact with FE at the same time.

**Comment by luacs1998** [comment]
FML has tools like the @Optional annotation, which strips out a particular annotated method or field (maybe even a whole class, IDK) if a certain mod is not present. Last I heard the goal was to move away from shipping others' APIs (which may get messy), that's why I'm forcing this.

**Comment by liach** [comment]
How about `@FEModule` annotation? Hah.

**Comment by luacs1998** [comment]
That is not part of the API.

**Comment by olee** [comment]
@liach this is pretty useless because you need the full FE jar for testing anyway.
So why add something which would only help developing mod compatibility blind?

**Comment by liach** [comment]
Btw I don't think any function, method, or annotation in `cpw.mods.fml.common.Optional` could remove annotations. So once the mod is used w/o fe it needs to ship those annotations used. Right?
