### ISSUE TITLE
Better support for fake players?

### ISSUE THREAD

**Issue by StarkRG** [ForgeEssentials/ForgeEssentialsMain#1265]
Recently had a discussion over on the [EnderIO github](https://github.com/CrazyPants/EnderIO/issues/1771) about being unable to get their Killer Joes working. It seems that every single machine has its own fakeplayer and random UUID, meaning adding them to the ForgeEssentials permissions would be time consuming and unscalable.

tterrag pretty much that there wasn't anything he could do about it (despite pretty much every other mod not doing it the way he does and, therefore, working), and suggested I contact you guys to see about adding a "class-based blacklist". By which, I assume, he means having a way to give permissions to certain types of fakeplayers by default without having to explicitly enter them into the permissions system one by one.

While one solution would be to just give all fakeplayers all permissions and be done with it, I imagine there are quite a few server owners who would like to be able to continue to deny certain fakeplayers certain permissions. That said, I think it makes sense to give all fakeplayers all permissions by default and give server owners the ability to restrict those they discover doing things they don't want them to do.

In particular, I think it makes sense to handle fakeplayers differently from real players (in particular real players have UUIDs and are often given fewer permissions by default until they are explicitly granted them).

**Comment by luacs1998** [comment]
I'm working on a framework to better support fake players in FE permissions. Just need @olee to walk me through some things.

**Comment by tterrag1098** [comment]
I actually just implemented a fix for this issue in EIO, all Killer Joes now have the same UUID...which seems wrong imo, but it works

**Comment by luacs1998** [comment]
https://www.reddit.com/r/feedthebeast/comments/2xd1jw/mod_fakeusers

**Comment by olee** [comment]
Sorry, after checking again I noticed the thing with random UUIDs.
The fix referenced above at least covers FakePlayers in general.
But if the UUIDs are really random, then it would frequently add more and more fakeplayers to the permission-registry.
We need to know, if FakePlayers with the same name can really have different UUIDs and if so, add a fix for that in UserIdent.
We could check there, if the player is a FakePlayer and use another UUID then.

**Comment by olee** [comment]
After checking https://github.com/CrazyPants/EnderIO/issues/1771 I see that they fixed it.

It seems they added the location to the name of the FakePlayer.
Because the UUID of FakePlayer's is generated by their name, the UUID was always random as well.
