### ISSUE TITLE
Multiworld Portal? :)

### ISSUE THREAD

**Issue by barthy** [ForgeEssentials/ForgeEssentialsMain#1267]
I know you got alot to do but add this to your todo list  :)  Portals for multiworlds !
thanks guys... keep up the good work :)

**Comment by luacs1998** [comment]
Can't remember if it's planned or has already been done...

**Comment by helinus** [comment]
There is a basic portal feature in the teleport module, not entirely sure how it works though...
The command syntax is a bit confusing but you can create a portal with ``/portal create <name> [width] [height] [x y z]`` where ``<name>`` is what you want to call the portal, ``[width] [height]`` is the size of the portal in blocks and ``[x y z]`` is where you want it to lead to.

**Comment by olee** [comment]
It's done, BUT there are problems with selections not remembering the world they were made in, preventing you from creating portals to other dimensions :-1:

**Comment by barthy** [comment]
was more refering to multiworlds portals  since i like to make a mining make that i reset oftenly and create portals at 1 location in a spawn area then lead them to specific places in the other dims

**Comment by olee** [comment]
That's what they are intended for - it's just like I said that setting them up across worlds is a bit problematic right now.

**Comment by barthy** [comment]
no worries Olee just asking :)   just throw some bucks for support..  will promote your mod on forums  you guys are doings a great work and it's need to be shown :)

**Comment by olee** [comment]
Once #1329 is merged, this can be closed as well.
