### ISSUE TITLE
Problem connecting to irc.twitch.tv via chat module

### ISSUE THREAD

**Issue by BakermanLP** [ForgeEssentials/ForgeEssentialsMain#1271]
Hello,
I have got a problem with the chat module. I can't connect to irc.twitch.tv

Here is the relevant part of my Chat.cfg file:
    irc {
        S:channel=#bakerman_lp
        B:enable=true
        S:ircHeader=(IRC) [%channel] <%ircUser>
        B:muteCmdBlocks=false
        S:name=bakerman_lp
        S:nickservPass=
        I:port=6667
        S:server=irc.twitch.tv
        S:serverPass=oauth:XXXXXXXXXXXXXX
        B:silentMode=false
        B:suppressEvents=true
    }

All settings above are working for example in kvirc. The oauth is also correct, but here it is "cleaned out".

[07:54:15] [Server thread/INFO] [ForgeEssentials/ForgeEssentials]: Initializing IRC connection
[07:54:15] [Server thread/INFO] [ForgeEssentials/ForgeEssentials]: Attempting to join IRC server: irc.twitch.tv on port: 6667
[07:54:15] [Server thread/WARN] [ForgeEssentials/ForgeEssentials]: Could not connect to IRC server.
[07:54:15] [Server thread/INFO] [ForgeEssentials/ForgeEssentials]: Saving permissions...

The latest beta build on jenkins gives me the following log messages:
[08:23:30] [Server thread/INFO] [ForgeEssentials/ForgeEssentials]: Initializing IRC connection
[08:23:30] [Server thread/INFO] [ForgeEssentials/ForgeEssentials]: Attempting to join IRC server: irc.twitch.tv on port: 6667
[08:23:30] [Server thread/WARN] [ForgeEssentials/ForgeEssentials]: IRC connection failed, could not reach the server.

But on the same machine I tried the following:
telnet  irc.twitch.tv 6667
Trying 199.9.250.239...
Connected to irc.twitch.tv.
Escape character is '^]'.
HELP
:tmi.twitch.tv 421 you HELP :Unknown command

Can you please help me? Is there a way to get more logging? Activating debug in main.cfg has no effect on this.

A google search didn't help.

Thanks

Michael (aka BakermanLP)

**Comment by luacs1998** [comment]
FE IRC functionality was never designed for and never supported by us when using with twitch.

Do you want me to consider this a feature request?

**Comment by BakermanLP** [comment]
As far as i know this should be a normal IRC Server. Vor do you know any
difference?

luacs1998 <notifications@github.com> schrieb am Fr., 30. Jan. 2015 17:24:

**Comment by luacs1998** [comment]
Does twitch ban pircbotx-based bots?

**Comment by BakermanLP** [comment]
Haven't seen any issues about that. Can I enable some extra debugging in the IRC Module to see the connection log? I want to see something like this:
=== Success One ===
*** Trying address irc.twitch.tv/199.9.250.229
*** Connected to server.
>>>PASS XXXXXXXXXXXXXXXXXXXXXXXX
>>>NICK brianhsu
>>>USER PircBotX 8 * :PircBotX 1.9, a fork of PircBot, the Java IRC bot - pircbotx.googlecode.com
<<<:tmi.twitch.tv 001 brianhsu :connected to TMI
*** Logged onto server.
>>>JOIN #brianhsu
<<<:tmi.twitch.tv 002 brianhsu :your host is TMI
<<<:tmi.twitch.tv 003 brianhsu :this server is pretty new
<<<:tmi.twitch.tv 004 brianhsu tmi.twitch.tv 0.0.1 w n
<<<:tmi.twitch.tv 375 brianhsu :- tmi.twitch.tv Message of the day - 
<<<:tmi.twitch.tv 372 brianhsu :- not much to say here
<<<:tmi.twitch.tv 376 brianhsu :End of /MOTD command
<<<:brianhsu!brianhsu@brianhsu.tmi.twitch.tv JOIN #brianhsu
<<<:brianhsu.tmi.twitch.tv 353 brianhsu = #brianhsu :brianhsu
<<<:brianhsu.tmi.twitch.tv 366 brianhsu #brianhsu :End of /NAMES list
<<<:jtv!jtv@jtv.tmi.twitch.tv PRIVMSG brianhsu :HISTORYEND brianhsu
>>>WHO #brianhsu
<<<:brianhsu.tmi.twitch.tv 315 brianhsu #brianhsu :End of /WHO list
>>>MODE #brianhsu
====================

**Comment by c0nnex** [comment]
2 Issues:

a) Twitch does not support "CAP" - Commands.
Source has to be changed to do "bot.setCapEnabled(false);"

b) 
In the configuration "S:serverPass=" is the WRONG location for your oauth!
Add a line "S:password=oauth:xxxxxxxx" to the Chat.cfg-Irc Section.

With this changes I successfully connected to twitch with FE.

-c0nnex

**Comment by c0nnex** [comment]
Ok got all working now and added some features to the twitch implementation. #1296
A Binary is available on request, in case the pull is not accepted/takes longer time.
(To see it in action see http://twitch.tv/c0nnex )

**Comment by BakermanLP** [comment]
Thank you very much!
