### ISSUE TITLE
Cannot select Zones

### ISSUE THREAD

**Issue by Shiggles** [ForgeEssentials/ForgeEssentialsMain#1272]
Hey, trying to save a zone. I have my pos1 set at roughly 500, 70, 500, and my pos2 at -750, 70, -750, expanded up 100 and down 20. However, I cant seem to figure out how to save it. When i hit zone define name it says no selection available, but //size hows # of blocks to be 194,487,480.

This worked in FE beta2 and earlier.

Am I missing a command somewhere to go from worldEdit to FE core?

**Comment by olee** [comment]
Same old WE bug. Take a look at https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1266

**Comment by Shiggles** [comment]
Would it be possible to use beta2, create the zones I want, then upgrade to
beta4? I might try playing around with it since it's a brand new server and
I don't have anyone on it.

**Comment by olee** [comment]
Use `/fewand`. This one ALWAYS works.

**Comment by Fogger** [comment]
WorldEdit //wand selection is supported in the latest Jenkins build: 378
