### ISSUE TITLE
Crash on Server start [java.lang.NoClassDefFoundError]

### ISSUE THREAD

**Issue by ultrasn0w** [ForgeEssentials/ForgeEssentialsMain#1274]
When I start up my Server, the Server crashes and the log spits out this:

http://pastebin.com/LqZtXThM

Full log:
https://mega.co.nz/#!JNBRya5a!_PlIN0ANYhqC0xgI_REVRBOsQrFyxvzwWQr5jhAGOws

Greetings
ultrasn0w

**Comment by olee** [comment]
As you can see in the log, it's a bug from psychedelicraft where getItemName crashes:
````
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at ivorius.psychedelicraft.items.ItemInjectable.func_77653_i(ItemInjectable.java:94) ~[ItemInjectable.class:?]
	at com.forgeessentials.protection.ModuleProtection.getItemName(ModuleProtection.java:123) ~[ModuleProtection.class:?]

**Comment by ultrasn0w** [comment]
Thank you, I'll do so.

**Comment by ultrasn0w** [comment]
I would like to reopen this issue, because I removed ForgeEssientals from the mods installed on my server and now everything is working fine, I also tried and readd ForgeEssientals, but the same crash happens again.
Can you please help me with that problem or do you think there's just an Incompatibility?

**Comment by Ivorforce** [comment]
Like mentioned in my thread - 
It's partially both mod's fault - technically, the server shouldn't try to translate at all, which is why this doesn't happen without ForgeEssentials. On the other hand, I'm calling Client-Side only code on a shared method, which ultimately crashes the server.

Anyway, I've changed the calls in my mod, so the issue should be solved.

**Comment by i128kbps** [comment]
I have nearly the same problem with the most recent build. When i install FE in my Skyfactory 4 Modpack the server did not come up with the same error as here decribed.

**Comment by Zethalion** [comment]
Open a new issue as this one is resolved ages ago
