### ISSUE TITLE
Possible conflict with other mod using sqlite-jdbc

### ISSUE THREAD

**Issue by Gwani** [ForgeEssentials/ForgeEssentialsMain#1277]
Hi there!

I have written a mod which utilizes sqlite-jdbc-3.8.7 on the server by having the sqlite library's classes packed into the mod's jar file for easy distribution. The mod also relocates the sqlite-jdbc packages as sub-packages of my mod to avoid conflicts.

This works well until i add ForgeEssentials (currently using forgeessentials-1.7.10-1.4.0-beta4-server.jar) to the serverside mods. After that, JDBC cannot find the sqlite driver anymore when my mod tries to access its database:
`java.sql.SQLException: No suitable driver found for jdbc:sqlite:mymod.sqlite`

Could it be possible that ForgeEssentials somehow unregisters JDBC drivers or replaces the class loader responsible for locating the driver classes? I see that ForgeEssentials creates its own lib folder in mcserver\ForgeEssentials\lib for some libraries it uses. When i put the sqlite-jdbc-3.8.7.jar into this folder, my mod is able to find the JDBC driver again.

I also wouldn't rule out that i did something wrong the way i included sqlite in my mod. In this case i'd appreciate if someone could point me in the right direction ;-)

Cheers,
Gwani

**Comment by luacs1998** [comment]
No we don't - it's just that your sqlite loads before ours so we can't find what we need.

Consider remapping your sqlite library through ForgeGradle? Or you can do a special-case to overwrite our sqlite library with yours. We don't integrity-check the files so you can do that.
