### ISSUE TITLE
Perm to end world hunger

### ISSUE THREAD

**Issue by Fogger** [ForgeEssentials/ForgeEssentialsMain#1280]
Could you possibly add something like `.starve` or `.losehunger` or `.needsfood`

__Reason__
Much like my other request https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1279. I run a grey-listed server where guests are held in limbo, unable to do anything or even die while they wait for a mod to promote them, but in this time, it is easy to use up all their hunger bar, slowing movement to a crawl and when they are eventually promoted, they immediately start taking damage, or in our case using HungerOverhaul Mod, die instantly of starvation. :dancer:

The only possible solution I have found is to give guests /heal & hope they have the foresight to use it before being promoted. but without any Guest welcome message I can't even let them know about it. just have to hope that they study the /help pages thoroughly.

**Comment by olee** [comment]
There is one possibility I know of:
Use a fe.protection.zone.command setting to run /heal on every guest on the whole server every some minutes.

`/p group guest value fe.protection.zone.command /heal %p`
`/p group guest value fe.protection.zone.command.interval 60000`

This should work (without any testing done or guarantee!)

**Comment by Fogger** [comment]
This zone command doesn't appear to work.

I changed `guest` to `_GUESTS_`, to match the spelling as it is on my server.
Not sure if the Interval is in ticks or seconds, but even with an interval of `1`, it never fires.

The /heal command works when manually typed.

This is how it appears in the `_GUESTS_.txt`:
`fe.protection.zone.command=/heal %p`
`fe.protection.zone.command.interval=1`

**Comment by olee** [comment]
You should be able to handle multiple commands if you create a macro for that.
@luacs1998 can tell you about it (I didn't make them and don't know how to use them yet).

**Comment by olee** [comment]
Timer to set food / saturation to max every minute should suffice without adding any noticeable performance cost.
````
player.getFoodStats().addStats(20, 1.0F);
````
