### ISSUE TITLE
Guest player starts at spawn on reconnect

### ISSUE THREAD

**Issue by Sunconure11** [ForgeEssentials/ForgeEssentialsMain#1281]
So I'm running a Forge Essentials server, and a guest user has been claiming that upon reconnecting, they are sent back to spawn. Is there anything in Forge Essentials that can do this? I am using version forgeessentials-1.7.10-1.4.0-beta4, because later versions have issues with world borders that keep players from playing properly.

**Comment by olee** [comment]
FE does not interfere with player-locations **as long as they do not die**.
If it's about players dying, then it's part of #1218 anyway so I'm closing this one.
