### ISSUE TITLE
Proper crafting permissions

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1287]
Decide who can craft what using permissions.

Will probably require a ASM hook (replace constructor of SlotCrafting)

**Comment by olee** [comment]
Not really high priority and will be very difficult to implement.
There are many non-vanilly crafting tables and many which work automatically.
This will make controlling CRAFTING through permissions nearly impossible.

**Comment by luacs1998** [comment]
Have you looked into the FML crafting event?

**Comment by PitchBright** [comment]
Reminder to put in /protectdebug for crafting perms.
