### ISSUE TITLE
[REQ] IRC bot use /nick instead of real game name

### ISSUE THREAD

**Issue by Fogger** [ForgeEssentials/ForgeEssentialsMain#1288]
We use /nick to make players (often random) game names match their IRC nicks, and this is great in game, but when using the irc bot, it uses their real minecraft names instead.

**Comment by c0nnex** [comment]
Since i have the same problem, i started working on it. Since it requires major rewrite of most of the IRC stuff it might take some time, until the pull request will be available

**Comment by luacs1998** [comment]
Should be already done - I forgot to close the issue.

Grab build 400 and test.

**Comment by c0nnex** [comment]
hmm .. there are still a *lot* of references to getCommandSenderName() .... It replaces fine for the ingamechat but all IRC Stuff is relying to getCommandSenderName()/getuser
I started working on a persistent nickname-Mapping-Database  so they can be mapped both ways around game->irc and irc->game. Should i stop that?

**Comment by luacs1998** [comment]
Stop it. You have the player, just get the value of "nickname" from the persistent entity tag.

**Comment by c0nnex** [comment]
Then it'll have to iterate through all players when a message from irc comes in ... On a busy channel ( i have like 10-30 msg a sec on a busy day ) this is a performance impact if there are like 200 players on the server.

**Comment by c0nnex** [comment]
Also nickname persistence  removes the problem of someone faking as me using the /nick command

**Comment by luacs1998** [comment]
Alright. Can you please tell me exactly what you need and I'll work with you to solve it.

**Comment by c0nnex** [comment]
Current idea (in IRCChatFormatter):

´´´
private static Map<String, String> nickMap = new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER);
private static Map<String, String> nickReverseMap = new TreeMap<String, String>(String.CASE_INSENSITIVE_ORDER);
public static String getPlayerIRCName(EntityPlayer player);
public static String getPlayerIRCName(String playerName);
public static String getIRCPlayerName(String ircName);
public static EntityPlayer getIRCPlayer(String ircName);
´´´

Every nick will be registered in nickMap as  "c0nnexX","my Fancy Name" , and nickReverseMap as "My Fane Name","c0nnexX". 
nickMap is persisted to Disc, to prevent faking someone else. No entry mean no nick used.
Whenever anything comes goes to IRC (e.g. login/logout etc) the nick will be exchanged.
When a msg comes in from irc, the user will be searched via the reverseMap.

**Comment by c0nnex** [comment]
of course alter /nick to check against reserved nicks etc.

**Comment by luacs1998** [comment]
Alright, I'll make a separate issue for that. Have you looked into the UserIdent class?

**Comment by c0nnex** [comment]
Ah that wahat i'm missing :-) have been looking for something like that. will have a look when i get up.
will you be working on that mapping stuff or shall I see what i can do?

Von meinem iPad gesendet

Am 16.02.2015 um 06:47 schrieb luacs1998 <notifications@github.com<mailto:notifications@github.com>>:


Alright, I'll make a separate issue for that. Have you looked into the UserIdent class?

-
