### ISSUE TITLE
[REQ] Make doas use the original sender permission and not the target player permission

### ISSUE THREAD

**Issue by sylphio** [ForgeEssentials/ForgeEssentialsMain#1291]
Right now, doas is really useful especially for any command that do not allow to specify a "target" like FE warp.

if would be really useful if the command
   /doas player1 warp somewhere

Use the person who call doas permission and not the "player1" permissions.
Right now, doas cannot do anything that the player isn't allowed to do by himself.

Thank

**Comment by luacs1998** [comment]
That's the whole point of /doas - it's supposed to be a sudo-like command.

I can create another command for it though...

**Comment by sylphio** [comment]
Good to know, thanks for the answer.

**Comment by luacs1998** [comment]
On second thoughts, it's a hell if I want to have permissions be checked on one player and the command to run on another player. Most commands should let you apply its effects on other players...
