### ISSUE TITLE
Can't login to server with forgeessentials installed

### ISSUE THREAD

**Issue by zlepper** [ForgeEssentials/ForgeEssentialsMain#1294]
Everything I login to my server I get this error serverside: http://zlepper.dk/fml-server-3.zip
Then I get kicked.

The issue happens around line 49000. I send the entire log in the hope that you can find the issue. 

Neither server nor client crashes, the client is just disconnected.

**Comment by olee** [comment]
Then you should send us the client-log, too.

**Comment by zlepper** [comment]
Using the latest version fixed the issue. 
Also, the latest version is not on curseforge.

**Comment by olee** [comment]
Of course - we only ship out versions about once a month on curseforge.
If you ever have a problem, use the latest jenkins-build first.
