### ISSUE TITLE
[REQ] Ability to change speed via command

### ISSUE THREAD

**Issue by Biofusionz** [ForgeEssentials/ForgeEssentialsMain#1299]
Just a simple command to change the players speed whether flying or walking.

/speed [name] [speed 0-10]

**Comment by luacs1998** [comment]
In progress (feature/speed_command branch), just that I encountered some crazy FOV bugs.

**Comment by olee** [comment]
Any progress on this issue?
I would really love to have this command as well (there have already been many times I wanted to use such a command in MC).

**Comment by evernife** [comment]
too ^^

**Comment by olee** [comment]
@luacs1998 Even if you have FOV bugs (probably only with very high speed, right?), could you merge this to develop if it's usable other than that? I also might be able to fix the bug if you are at your wits end.

**Comment by luacs1998** [comment]
The FOV bugs also happen at speeds of 0.1F.

For reference, the player walking is 0.05F.

It's kept in a branch because I don't want people to use it and then ask me "what the fuck happened to my FOV???"
