### ISSUE TITLE
Vanilla teleport behavior missing

### ISSUE THREAD

**Issue by gravitythief** [ForgeEssentials/ForgeEssentialsMain#1300]
I cannot use tildes when specifying coordinates. There may be other features missing as well.

**Comment by luacs1998** [comment]
I'll consider this a request, since we don't have the option of specifying tildes in coords.

**Comment by gravitythief** [comment]
isn't this a vanilla feature though?

**Comment by olee** [comment]
That's definetly considered a bug, as it prevents usage of vanilla features.
Some adventure maps rely on command-blocks + relative-tp.
