### ISSUE TITLE
Cross-Dimension Teleporting

### ISSUE THREAD

**Issue by hidemat** [ForgeEssentials/ForgeEssentialsMain#1302]
Hello. I'm asking here because I can't find the config file for it. Is it possible to disable cross-dimension teleporting in beta5? This is so players can't use, for example, /home to tp from one world to the other.

Thanks for your time.

**Comment by olee** [comment]
This is currently not possible as far as I know.
You can disable warping / teleporting for some dimension, but not specially across dimensions while still allowing in-dimension teleporting.

**Comment by hidemat** [comment]
I see. Thanks for replying.

**Comment by olee** [comment]
Does not really need a hook - we just need to add a permission and integrate it into teleport-handler.

**Comment by luacs1998** [comment]
@olee hook is needed because FML does not allow us to cancel the teleport event. Unless you have another way to cancel cross-dim teleports?

**Comment by olee** [comment]
If you take a look at the question of @hidemat you will see that he was talking about direct teleport commands FE provides.
If one wants to prevent players traveling to a dimension, they can just set the protection permission for that and players will not be able to enter the dim.

**Comment by olee** [comment]
See? That's it....
