### ISSUE TITLE
[Crash] MultiWorld : Importing world by copying region folder and level.dat

### ISSUE THREAD

**Issue by Mistercl0ud** [ForgeEssentials/ForgeEssentialsMain#1304]
Hello,

I've been following the procedure described in a previous request to import am existing world into Multi world. However, every time I'm doing that my minecraft crash when I'm coming back to the main world.

http://pastebin.com/HGzCcMbe

**Comment by luacs1998** [comment]
You need to speak to CaveBiomes to work with us for a solution.

Also, you installed fastcraft, and you forgot to mention you did :)

**Comment by Mistercl0ud** [comment]
Well I just installed cavebiome. But when I tried before without it I also had crashes. Is Fastcraft not compatible with Multiworld ?

**Comment by olee** [comment]
Continueing conversation in original post.
