### ISSUE TITLE
Playerlogger rework.

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1306]
You said you wanted to do it, so you're assigned, @Malkierian

If possible, please get it done before end-March, I want to move to 1.8 by then. Just waiting on PL to push 1.4.0 as a stable release.

Here's the design doc: https://docs.google.com/document/d/1YXiKzCjeLzDdyC_cgQWrk0RNpThdmYIkuFIzv2BXDYk/edit

**Comment by luacs1998** [comment]
As soon as the mixin PR is finished, I will start working on hooks for this.

**Comment by olee** [comment]
Hooks? If we need any that is.
For the start the existing events should suffice.

**Comment by olee** [comment]
I think we should move this to the next milestone like 1.4.1 or 1.5.0.
This is just too big a feature and is only holding us back to make a 1.4.0 release.

**Comment by Flukethoughts** [comment]
If you do a player logger please incorporate mysql and a pruning method to prune the database after so much said time.

**Comment by olee** [comment]
Considering this for now as "DONE".
New features for the (yet small) PlayerLogger will be added as soon as players request them.

@Flukethoughts
Prune is (should) not be necessary will (probably) not be done for the new, optimized PlayerLogger.
Even if you get some thousands of entries in the PlayerLogger after a year, the database should be no more that 5-10 MB in size and it does not impact performance as well.

If you really want to prune it, either just delete it after confirming your world has a state where you do not want to revert anything, or prune it manually with SQL statements on the database.

If we would ever get a report of a 20 MB+ PlayerLogger, that's when we would consider adding this.
