### ISSUE TITLE
Cauldron sanity check

### ISSUE THREAD

**Issue by MrMcCrab** [ForgeEssentials/ForgeEssentialsMain#1308]
I know it's there for a reason, but the wiki says there should be a config setting in the main.cfg to disable it. Was it removed or is it somewhere else? Running forgeessentials-1.7.10-1.4.0-beta5

**Comment by luacs1998** [comment]
It's now a system property. If you can set the system property, you can try.

Just that you'll crash before that seeing as I doubt the latest version of Cauldron doesn't support Forge 1258.
