### ISSUE TITLE
forgeessentials warning abut %100 memory used

### ISSUE THREAD

**Issue by scootashy** [ForgeEssentials/ForgeEssentialsMain#1312]
is there a way or would a config be added to adjust that for servers since the host had to work to shut off the warnings as only 1 gb out of 2 gb of memory was used and it was saying %100 memory used. If we could adjust it to match up to the max memory of a server and set its warning target to a number say 3/4 or so to the max to get that warning and have it accurate would be good.

**Comment by mrwuss** [comment]
We are having this issue as well on our server. Roughly 4GB of the supplied 22GB are being used and FE continues to tell us that we are at 100% usage. At times it will refuse to even launch on the server stating there is not enough memory.

**Comment by mrwuss** [comment]
[Server] Timer-4/INFO [ForgeEssentials]: High memory use detected. 100% of memory in use.

Is the spammed warning

According to multicraft's panel we are using 12% of the allotted 22GB for the server.

**Comment by luacs1998** [comment]
Update your beta build.

**Comment by trismegistis** [comment]
Hi, I'm using the latest build as of today, ends in a 16, it is still saying im using 96% memory, even though not even 1/3 of total allocated memory is being used. only about 1gig of 4gigs atm.

**Comment by olee** [comment]
1) How do you check that you are using that amount of memory?
2) How much RAM did you assign your server?

**Comment by trismegistis** [comment]
I used the Task Manager of Windows, showing Java using 1.5 Gigs of RAM, and I have used -Xmx4G in my server start bat

**Comment by olee** [comment]
So you are running the *server* locally on your windows PC?
(Just want to confirm you did not mix up the local client RAM and the server one :wink:)

**Comment by trismegistis** [comment]
No, I'm running a 1492 Forge Server with a large modpack. It's public and
the IP/Website is Trismegistis.com.

**Comment by liach** [comment]
Try to add a `-Xms4G` in the args?

**Comment by trismegistis** [comment]
Ok will do
