### ISSUE TITLE
Voting module crashes server when rewards are added to config.

### ISSUE THREAD

**Issue by TimB1087** [ForgeEssentials/ForgeEssentialsMain#1317]
Version 1.4.0-beta5-server
Forge version 1291

When I add rewards to the config file for the voting module, the server will not start. Removing the rewards from the list allows the server to start up just fine. Other config settings don't seem to affect this issue.

Here is the crash report and the config file that causes the crash. The items listed in the config under rewards are vanilla items, and are not mod items, so you can eliminate the possibility of modded items causing the error.

Crash report:
http://pastebin.com/hYQfd673

Config:
http://pastebin.com/RSsfkn7r

**Comment by liach** [comment]
It seems there shouldn't be a "toString", but more likely to be a "getUnlocalizedName". That's it.
