### ISSUE TITLE
missing worldedit commands

### ISSUE THREAD

**Issue by darkmdbeener** [ForgeEssentials/ForgeEssentialsMain#1318]
everything else worked. I just upgraded from DW20 1.0.3 to 1.0.4 and dragged the FE back over. everything seems to be there but worldedit.

**Comment by helinus** [comment]
I'm thinking you forgot to drag worldedit back over as it is its own jar in the mods folder.

**Comment by darkmdbeener** [comment]
i dont see that even when I re download it.

**Comment by darkmdbeener** [comment]
it being FE which says comes with WE

**Comment by luacs1998** [comment]
FE comes with WorldEdit in that we extract the worldedit jar on server startup. This is done on purpose.
