### ISSUE TITLE
minecraft server runing under mcmyadmin running forge 1291 with forge essentials any version

### ISSUE THREAD

**Issue by kain184** [ForgeEssentials/ForgeEssentialsMain#1321]
hello all i am having a strange issue was wondering if you can help / replicate will include a server file download and a log here with it. but running the server while not under mcmyadmin the server runs with the only noticeable errors that i can find being missing textures and a weird thing at the end of load up where the dimensions go into a kind of sleep mode till someone logs into the server then it loads fine as seen here i have the server first with out ether forge essentials https://dl.dropboxusercontent.com/u/49292585/nonadminnonessentials.log and then with https://dl.dropboxusercontent.com/u/49292585/nonadminwithessentials.log and now here with mcmyadmin https://dl.dropboxusercontent.com/u/49292585/McMyAdminnoessentials.log and from https://dl.dropboxusercontent.com/u/49292585/adminnoessentials.log (being the log from mcadmin and forge respectfully. ) it will also run and work fine. but the problem comes with running both of them. in these two logs the system will load get to the point were the dimensions would sleep and then the entire system will start a reboot loop till i kill it https://dl.dropboxusercontent.com/u/49292585/admin with essentials.log https://dl.dropboxusercontent.com/u/49292585/Mcwithessentials.log so i ask can anyone on any of these logs find the cause of this because i have been going for days trying looking at every part i can and cant find the reason. it is driving me crazy. a few days ago i had this exact server i have tried upgrading and downgrading mods as well as looking at all the advice i can. but i can never find the reason the two of them wont get along. so please help

**Comment by luacs1998** [comment]
Pastebin your logs, I am not going to download anything.

**Comment by jermangarc** [comment]
Missing textures error is normal, as many mods will report them on startup. 

As for the dimensions, all dimensions except Overworld are supposed to be unloaded until you travel to those dimensions, unless you specify in your configs that you want them loaded all the time. This is off by default so as to not eat up server resources.

Examining your logs, I noticed that you have AromaBackup installed. So I would start checking your backup system. For example, McMyAdmin has it's own backup system and world auto-save. Forge Essentials ALSO has this feature and you have Aromabackup installed as well. Make sure you only have one of these backup systems working and not all three. I could see this causing lots of lag and potential problems for your environment. 

I could be wrong, but from seeing your logs, you have lots going on and I'm not entirely sure you have everything configured properly. Check your McMyAdmin config and compare it to your ForgeEssentials config and make sure there aren't features overlapping. That's where I would start.

**Comment by kain184** [comment]
was looking through. as you said and i actually after a lot of issues found that it was the mod Buildcraft utilities causing a array error with one of its tanks that was causing the issue kept giving me a metadata is 7 error. anyway don't know if your software itself was picking that up or not as the issue did not pop up until that mod was installed with mcmyadmin and forge essentials. it had to have both to cause the issue.  and as for paste-bin i cant do that because of the size of my logs its to big for them to use it. but as of now i have the system working with both your mods but if you want to look into that issue for the future.

**Comment by Flukethoughts** [comment]
just a heads up mcmyadmin doesn't interact with anything forge essentials does I have went this route myself thinking something isn't right only to find it was user side later.

**Comment by olee** [comment]
First: Closing this as usererror - report back if you really still need help or better get on IRC.

@jermangarc
Now I'm interested in what you said about McMyAdmin and FE together:
- Why are you using both and not only FE? (What is FE missing that you need McMyAdmin?)
- What was that about permissions of McMyAdmin?

**Comment by jermangarc** [comment]
@olee 
McMyAdmin is a Server admin tool and not a mod or plugin. When I was running MCPC+ (cauldron) I was able to set permissions, set user groups and manage them per world basis easily via the web interface without typing in commands. I also have other admins that can log into this interface remotely and do the same when I'm not around.

Basically McMyAdmin is the software running the server. It also helps me monitor my CPU and Memory load via the web interface. At any rate, I found a post on their site that can shed some light for you. Here it is:
http://support.mcmyadmin.com/mcmyadmincommunity/topics/forgeessentials_integration_into_mcmyadmin

**Comment by evernife** [comment]
Hmm, FE have FERemoteClient to edit perms.
https://github.com/ForgeEssentials/FERemoteClient 
Its more useful :D 
(two years old comment, lol)

**Comment by olee** [comment]
Lol @jermangarc, I actually posted a reply on that site there 5 months ago.
I just forgot what it was about.

Then again, remote will make McMyAdmin actually pretty much useless...

**Comment by jermangarc** [comment]
Awesome, I'll have to take a look at it then! Thanks for the info.

**Comment by olee** [comment]
It is still in development, but should be done in maybe a week or two.

**Comment by cullorblind** [comment]
I usually use McMyAdmin to launch the server and keep it running.  After a server reboot for updates or whatever, it will automatically launch the server.  It also handles restarting the server after a crash, and will attempt starting the server X number of times before giving up if there's a more serious problem.  On my spigot server, it does tie into a few different user management systems tough, but I don't use that currently.

Will feremote have a way to launch/restart the server if it crashes, because that's my main use for it.

**Comment by olee** [comment]
No - of FE remote (as the name implies) is for remote management.
But for these things like automatic server restart are many simple scripts available that do the job and it is even easy to write oneself.

But FE remote will completely cover the management of the running server.
