### ISSUE TITLE
Current sell command syntax

### ISSUE THREAD

**Issue by Sunconure11** [ForgeEssentials/ForgeEssentialsMain#1322]
What is the current syntax for a command block that sells an item? The one on the wiki does not work properly.

**Comment by Sunconure11** [comment]
This is the error I get:

http://pastebin.com/ZETpLNrS

**Comment by luacs1998** [comment]
Expected structure: "/sellcommand <player> <item> [amount] [meta] <command [args]>

Wiki has been updated.

**Comment by Sunconure11** [comment]
Can you add some examples of it that I can use in the command block? Its not picking up the addtowallet command.

**Comment by luacs1998** [comment]
It SHOULD work...

**Comment by Sunconure11** [comment]
Well, with that syntax you posted, I'm still getting the error when it tries to execute the addtowallet command.
