### ISSUE TITLE
Vanilla (mod-based) commands

### ISSUE THREAD

**Issue by kerts93** [ForgeEssentials/ForgeEssentialsMain#1323]
I have problem that I cannot use any of the vanilla commands (and most mod-based) even when usergroup has * permissions. For example commands like whitelist, op, list etc. It returns that I do not have enough permissions

Using version beta 6 #418 (jenkins)
//EDIT: same with latest version #422

**Comment by luacs1998** [comment]
Run /p debug, run the command you're trying to do and give me the chat output.

**Comment by kerts93** [comment]
It doesn't return anything, only gives me that you cannot use this command.
![Log](http://i.imgur.com/syYIBDW.png)
Commands I tried: /whitelist add (2 times) and /list

**Comment by luacs1998** [comment]
Try opping yourself.

I may need to check if the perms are registered correctly, and may need to fuck over CommandHandler if I'm not getting my perms correctly...

**Comment by kerts93** [comment]
When opped then all commands work.

**Comment by olee** [comment]
I will try to fix `/p debug` so it correctly shows perms even when not OP.

When the command works correctly again, you should easily be able to find the problem with why you can't use the commands.

**Comment by olee** [comment]
Has been fixed in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/119ea69f603e3a2ee649f85a7b57dc2aa152d21a
