### ISSUE TITLE
Stop Portals from creating glass (or any block)

### ISSUE THREAD

**Issue by BuggeringHell** [ForgeEssentials/ForgeEssentialsMain#1330]
It would be great no blocks were changed/set when creating a new portal; this adds more flexibility when creating custom portals, essentially allowing portals to be made from anything.

**Comment by olee** [comment]
It's supposed to create normal portal-surfaces later on, but for that we need some magic.
If we currently let it create portal-surfaces instead of glass, it will try to teleport players to the nether - we need to hook into the code and prevent it from doing so.

**Comment by BuggeringHell** [comment]
Personally it would be good if it could just be air blocks, or the blocks that are currently present (so making portals out of secret walls, existing doors, fake caves, etc). Though an additional command argument to determine what surface/block type would also be good (e.g. none/portal/block <id|name>)

**Comment by olee** [comment]
Well air would not make sense because you cannot see them at all then - the glass is just temporary until it becomes proper portal-surface.

**Comment by BuggeringHell** [comment]
The air would be what you would walk through, so it could be wrapped in a frame, or put in front of a door if that makes sense. I think Multiverse-Portals functioned in that way to allow for people to make portals out of anything.

**Comment by olee** [comment]
Oh that's a nice idea.
For example one could put a portal-frame into a corridor to make it go elsewhere without player's noticing it before (traps?)

**Comment by BuggeringHell** [comment]
Exactly, so e.g. small buildings that are bigger on the inside (a classic example is the tardis), a 'bottomless pit' that leads to a dungeon somewhere else, or even a welcome zone that with customized portals (waterfalls, etc) that go to different dimensions.

**Comment by BuggeringHell** [comment]
Hey olee,

What is the likelihood of the glass panes being removed from the code anytime soon? Or adding a portal argument that a conditional checks for before creating/destroying the glass and cancelling the block destroy event.

Should I make a pull request to demonstrate what I mean?

Code in question:
```
    @SubscribeEvent(priority = EventPriority.NORMAL)
    public void breakEvent(BreakEvent e)
    {
        if (FMLCommonHandler.instance().getEffectiveSide().isClient())
            return;
        WorldPoint point = new WorldPoint(e.getPlayer().dimension, e.x, e.y, e.z);
        for (Portal portal : portals.values())
            if (portal.getPortalArea().contains(point))
            {
                e.setCanceled(true);
                break;
            }
    }
 private static void buildPortalFrame(Portal portal)
    {
        World world = DimensionManager.getWorld(portal.getPortalArea().getDimension());
        if (world != null)
        {
            for (int ix = portal.getPortalArea().getLowPoint().getX(); ix <= portal.getPortalArea().getHighPoint().getX(); ix++)
                for (int iy = portal.getPortalArea().getLowPoint().getY(); iy <= portal.getPortalArea().getHighPoint().getY(); iy++)
                    for (int iz = portal.getPortalArea().getLowPoint().getZ(); iz <= portal.getPortalArea().getHighPoint().getZ(); iz++)
                        if (world.getBlock(ix, iy, iz) != Blocks.glass_pane)
                            world.setBlock(ix, iy, iz, Blocks.glass_pane);
        }
    }

    private static void destroyPortalFrame(Portal portal)
    {
        World world = DimensionManager.getWorld(portal.getPortalArea().getDimension());
        if (world != null)
        {
            for (int ix = portal.getPortalArea().getLowPoint().getX(); ix <= portal.getPortalArea().getHighPoint().getX(); ix++)
                for (int iy = portal.getPortalArea().getLowPoint().getY(); iy <= portal.getPortalArea().getHighPoint().getY(); iy++)
                    for (int iz = portal.getPortalArea().getLowPoint().getZ(); iz <= portal.getPortalArea().getHighPoint().getZ(); iz++)
                        if (world.getBlock(ix, iy, iz) == Blocks.glass_pane)
                            world.setBlock(ix, iy, iz, Blocks.air);
        }
    }
```

**Comment by luacs1998** [comment]
You can make a PR, but I'd leave it up to olee to accept it...

**Comment by olee** [comment]
We are working on it right now.
Glass panes will first be replaced by portal-frame.
Then we can add an option to make the portals invisible, too.

**Comment by BuggeringHell** [comment]
Adding /portal creqte

**Comment by BuggeringHell** [comment]
(close and comment is really close to the keyboard on github mobile...)

Adding the argument noframe to /portal create would be useful, so it completely skips the block set code (so it doesn't replace any blocks)

**Comment by olee** [comment]
Ok that should be a lot better now.
Now the portals use the regular portal-block with some magic :wink: 

As for the `noframe` option, we will have to see when I have time.

**Comment by olee** [comment]
Please note, that you probably need to recreate existing portals if you want them to have a frame.
