### ISSUE TITLE
Console spam leads to "timed out"

### ISSUE THREAD

**Issue by FiveEYZ** [ForgeEssentials/ForgeEssentialsMain#1334]
getting spammed with this after latest jenkins build 428 http://pastebin.com/XVYRKVgg

**Comment by FiveEYZ** [comment]
think the problem is https://github.com/Bertware/bukkitgui2/
no more lag / Timed out when i closed it and run the server without it

**Comment by olee** [comment]
No it's a fault on our side.
I fixed it already and will commit it soon.
