### ISSUE TITLE
Afterlife error

### ISSUE THREAD

**Issue by FiveEYZ** [ForgeEssentials/ForgeEssentialsMain#1335]
If a player have a Afterlife grave and then logs in i see this error in the console http://pastebin.com/nWqpg2qv
http://pastebin.com/HUpZ33Qx

They cant access the grave, sometimes they get the items back if we place a block on the fence and break it and the items will fall out on the ground.

another thing: there is alot of
"[permission persistence timer/INFO] [ForgeEssentials/]: Saving permissions..."
in the console.

and "/home" resets after every server restart and i need to run "/home here" again.

**Comment by olee** [comment]
Probably a problem with fastcraft - try removing it.
If that solves the problem, we will need to take a look at fastcraft compability.

**Comment by FiveEYZ** [comment]
tested now without fastcraft: http://pastebin.com/DS9xTr4A

**Comment by olee** [comment]
Hm this is interesting, as there's EnderIO in the stacktrace.
There seems to be either an issue with our FE-skull tile-entity or it is just somehow not correctly assigned to the block.
Could you pastebin me a list of the mods you've got installed? (a simple `ls` on your mods directory should suffice)

**Comment by FiveEYZ** [comment]
FTB infinity update 1.1.0
https://feedthebeast.atlassian.net/wiki/display/PML/Infinity+1.7+1.1.0

**Comment by cullorblind** [comment]
Looks like openblocks graves and afterlife conflict.   Both are trying to save inventory in a block in the same place.

Either can be disabled in configs.

**Comment by FiveEYZ** [comment]
well open blocks saves the inv but it dosent make a grave in the game(that part is disabled)

it only throws the error when i go back to the location i died and on the fence there is a skeleton skull with <ERROR>

**Comment by ultrasn0w** [comment]
There is another Thing with Afterlife, Potion effects are only applied on the first death.

**Comment by olee** [comment]
That should not be the case.
I tested it several times and they were always applied.
If they are not on your server, there is probably another mod that interferes with respawn.

**Comment by olee** [comment]
As there has been no response any more I'm closing this.
Please report here if the issue should still persist.

**Comment by Pyeroh** [comment]
I can say that with the latest version, it works like a charm...

**Comment by evernife** [comment]
too
