### ISSUE TITLE
A bit more info about how to setup the development environ

### ISSUE THREAD

**Issue by arruda** [ForgeEssentials/ForgeEssentialsMain#1338]
Hi there, since there'll be no more releases for 1.6.4, I was thinking of trying out and adding the patch from (#1065) in a 1.6.4 release.

But I'm new to this, so I got a little bit lost:

Following the old readme, for 1.6.4, I couldn't figure out what is the ForgeGradle version that should be used:

https://github.com/ForgeEssentials/ForgeEssentialsMain/blob/1.3.0.4_f964_mc164/README.md#development-setup

It would be nice if you could specify it, or even put a link to it, just for clarity sake's. 
Thanks =)

**Comment by luacs1998** [comment]
You are expected to have basic FG knowledge. If not, it's a simple Google search away.

**Comment by arruda** [comment]
Ok, I just posted here to try to make easier to newcomers, I googled and found that apparently for the version 1.6.4 (`9.11.1.965`, been both the latest and recommended release) don't have the gradle support.

I found also that the `9.11.1.964` release appears to be an delicate one, that looks like it has gradle support, but I'm not sure this one, for not been the latest, nor the recommended is ok to be used with your mod.

If you could just post what forge version (release) you used, and that worked with your mod, it would make a lot easier to those that wish to help out, since it narrows a bit the searches in google, in the minecraft forge forums.

Thanks =)

**Comment by luacs1998** [comment]
For all accounts and purposes, 965 is just 964 ported to grade.

**Comment by arruda** [comment]
Thanks =)

--

Felipe Arruda Pontes
arruda.blog.br

2015-03-12 12:24 GMT-03:00 luacs1998 <notifications@github.com>:
