### ISSUE TITLE
Ponderings of mine....

### ISSUE THREAD

**Issue by InvertedCow** [ForgeEssentials/ForgeEssentialsMain#1339]
Hello, I was wondering if there is a way to do a few things:

1 totally remove a block from a modpack.  Not just disable the recipe with mod tweaker but completely remove it altogether, particularly with certain mods added world generation blocks that do not have a recipe.

2 totally and completely remove and block unwanted dimensions. Some mods add dimensions that  for some mod packs are awesome but for others do not work at all. it is easy to remove blocks that are needed to make the portals and whatnot but forge essentials still tries to save the dimensions every few minutes.  If they can be removed altogether  so that the files do not even exist that could drastically save of performance (especially for people with crappy computers like yours truly) And since they are blocked even if a player did attempt to creative  cheat in a portal they could not access the dimension. 

thanks!

**Comment by luacs1998** [comment]
That would require messing around in the innards of MC and Forge, and I have been told that lex-sama, our glorious Emperor, has made it an act of high treason to ASM into Forge.

It is possible to turn off backups for some dimensions (I can't remember how), but the dimension files will still be on your disk, just not loaded.

Then when I get dimension restriction running in protection, it should be possible to prevent people from travelling there.

**Comment by InvertedCow** [comment]
that is too bad, Although I would at this point be willing to commit the high treason if it meant that I could save some time working with the editing of all the items in my pack lol.  

Just enter a little list of numbers and say remove these... no one would know we can make it seem innocent  lol 

if anyone ever tells me that making an adventure modpack is easy I am going to punch them in the jubbulies!

**Comment by olee** [comment]
You can prevent players from traveling to other dimensions with protection.
IIRC if you set fe.protection.zone.knockback = true on the world-zone for the specific dimension, it will prevent players entering that dim (well currently they will probably be teleported there and instantly return to their previous world).

**Comment by InvertedCow** [comment]
Thanks for the suggestion, I think that is a server based system though. (I may be wrong I am still learning) 

I am building an adventure map so multiplayer configurations do not work in SSP. That is the problem I have been having. I have found Bukket plugins that can do most of the things that I want to do, (like world border world wrap) but they do not translate to single player and that messed me up. Which is why I am here trying to find another solutions. 

That is the problem I have had all along most things are made for multiplayer and server systems  but are useless for single player and do not cross over between the two very well or at all.

**Comment by olee** [comment]
FE is also usable on client!
All the stuff you can do on the server, is also possible in singleplayer :wink: 
Especially for adventure maps FE offers the greatest features.

For example by permissions you could make stone unbreakable, but allow breaking sand / dirt so players need to dig through a stone-labyrinth, which is filled with dirt :smile:

**Comment by InvertedCow** [comment]
That is why I was directed to F.E. to begin with. I had set up a server for an adventure map I am attempting to build, but the only world border stuff I had found was bukket. which is server only. I did a World border using the bukket worldborder plugin with a world wrap but it would not translate to singleplayer when the server rental expired. (I made that suggestion on another thread as recommended by lucas)  

This is the biggest map I have attempted ever in my gaming history and it is proving to be equally large in headaches. 

I have a few main obstacles that I am attempting to overcome;

One I want an "endless ocean" But I only need a map about 3200 blocks square. 

This I had achieved with the world border that failed and sent me back on a quest to find a solution, hence; here.

Two I want there to be certain things that are not obtainable lava for example 
The original cause of this thread. 

The removal of the other dimensions is not essential but would lower the overall drain on the game, currently I have  the overworld, (needed) Nether, The End, IceAge, Caves, Underdark, DinoWorld (all un needed or unwanted) They detract from the storyline If  accessible.  If I can remove items needed in their generation that eliminates the access  but doesn't eliminate the dimension. 

Your idea. sounds like it would work, However it is beyond my scope of knowledge at this time.

**Comment by olee** [comment]
If you still need help, please provide some concrete examples / questions and I can tell you how to do it.
With this general description I wouldn't even know where to start.

**Comment by InvertedCow** [comment]
I was going to send you a copy of the modpack as it sits right now but google drive is not working right and dropbox holds less than half the size of the zip file.  as soon as I find a usable free file sharing system I will give you message.
