### ISSUE TITLE
Rendering of horizontal portals on client

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1340]
Mixin already present, but the question is if we want to move the mixin to the client mod, and by extension, have the client mod include the mixin library as well. Would this lead to bloat? Discuss.

**Comment by olee** [comment]
Current workaround is having the FE-server-core present on the client as well which does the needed patching.

**Comment by luacs1998** [comment]
Mixins already implemented on clientside for /reach, now just to fix portal mixin and move it over.

**Comment by olee** [comment]
Actually we need both - a client and a server Mixin.
The one on the server side needs to prevent the default portal mechanics - the client one (might) be needed for visual fixes.
