### ISSUE TITLE
IRC Chat functionality not working as expected

### ISSUE THREAD

**Issue by rumak** [ForgeEssentials/ForgeEssentialsMain#1341]
I believe the IRC chat Functionality is not working as expected. 

Here is the setup. 

One new Forge server with FE installed version 1.4.0-beta5. One UnrealIRCD IRC server. 

The client(mod) connects, but no traffic is sent from the mc server to the irc server, only traffic from the irc channel to the mc server. 

I do have B:silentMode=false. 

Anything else I can do/check as I believe this is a bug. 

Nothing in the logs on the IRC server or mc server. 

Talked briefly to Olee on IRC and was suggested that this may be a bug. Let me know what you require from me on my end. 

FE Version: 
 You are currently running ForgeEssentials version 1.4.0-beta5
 Build information: Build number is: 397, build hash is: ebbaf87

**Comment by Biofusionz** [comment]
I had trouble with this at first but changing the config options to
# Enable IRC interoperability?
        B:enable=true
and
# Suppress all IRC/game notifications. Some channels require this.
        B:suppressEvents=false
This made it work for me, I can't remember which option it was which made it work.

**Comment by luacs1998** [comment]
Logs?

**Comment by rumak** [comment]
Thanks for the quick fix on IRC... For anyone else.. fixed as of build 450.

http://ci.forgeessentials.com/job/ForgeEssentials/450/
