### ISSUE TITLE
Re-implement /vanish

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1346]
Opened for closed issue https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1226

**Comment by luacs1998** [comment]
This was broken in the 1.7 port.

We previously used a packet sniffer to remove traces of vanished players from the server. I have not managed to replicate this functionality.

**Comment by olee** [comment]
Sounds like a lot of magic...
If it's that troublesome, we might better remove `/vanish` for now and turn this issue into a feature request instead of a bug.
I will leave the decision to you.

**Comment by Flukethoughts** [comment]
well looking into vanish no packet might be the best choice for a solution

**Comment by luacs1998** [comment]
We'll see. However, this may not make it into the initial 1.7.10 stable releases.

**Comment by luacs1998** [comment]
Done by olee
