### ISSUE TITLE
Wrench use

### ISSUE THREAD

**Issue by Flukethoughts** [ForgeEssentials/ForgeEssentialsMain#1350]
I denied all use of wrench in a zone. Well it didn't work.
/p global zone spawn deny fe.protection.use.item.itemYetaWrench
/p group _ALL_ zone spawn deny fe.protection.use.item.itemYetaWrench
nether worked
well im back to bother you

**Comment by olee** [comment]
Did you try `/protectdebug` or `/p debug`?

**Comment by luacs1998** [comment]
That actually depends on how the mod handles wrenh use internally. If they don't rely on or throw forge events, there's only so much we can do.

**Comment by olee** [comment]
I just saw you used `fe.protection.use.item.itemYetaWrench` instead of whats probably correct: `fe.protection.use.item.itemYetaWrench.*`.

I will just close this as done until you can report that it's definetly not working with the correct permission.
Try `/itemperm` and `/protectdebug` again!

**Comment by Flukethoughts** [comment]
olee i did but i don't think it has anythign to do with ur perms but yea ae2 cable try it urself to confirm
