### ISSUE TITLE
FE server crash

### ISSUE THREAD

**Issue by FiveEYZ** [ForgeEssentials/ForgeEssentialsMain#1354]
Got a crash on FTB Infinity 1.2.1 CoFHcore updated to RC7-211 (additional mods: Mytown2 and MyEssentials-core)
using forge 1307

http://pastebin.com/gMxCrQyh

crash because of Autonomus Activator and permissions.

**Comment by olee** [comment]
Just a bug on my side.
Going to fix it the next day.

**Comment by FiveEYZ** [comment]
crash with extrautility and forgeessentials
   at com.rwtema.extrautils.block.BlockSpike.doPlayerLastHit(BlockSpike.java:351)
   at com.rwtema.extrautils.block.BlockSpikeDiamond.func_149670_a(BlockSpikeDiamond.java:62)

http://pastebin.com/gfzGC2Qa

**Comment by olee** [comment]
Please give me time until tonight and I will try to fix.
If not it will have time to finish it tomorrow.

**Comment by olee** [comment]
Should be fixed with 830e8ff72dff113f588c6c564e93458daf903186
