### ISSUE TITLE
Running /help does not work. 

### ISSUE THREAD

**Issue by HiddenKn** [ForgeEssentials/ForgeEssentialsMain#1356]
Minecraft version: 1.6.4 (Custom tekkit modpack)
Error (from console, so in reverse):
21.03 10:20:59 [Server] INFO at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
21.03 10:20:59 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
21.03 10:20:59 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
21.03 10:20:59 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:277)
21.03 10:20:59 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:315)
21.03 10:20:59 [Server] INFO at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:88)
21.03 10:20:59 [Server] INFO at net.minecraft.command.CommandHelp.func_71515_b(SourceFile:36)
21.03 10:20:59 [Server] INFO at net.minecraft.command.CommandHelp.func_71534_d(SourceFile:74)
21.03 10:20:59 [Server] INFO at java.util.Collections.sort(Unknown Source)
21.03 10:20:59 [Server] INFO at java.util.Arrays.sort(Unknown Source)
21.03 10:20:59 [Server] INFO at java.util.ComparableTimSort.sort(Unknown Source)
21.03 10:20:59 [Server] INFO at java.util.ComparableTimSort.sort(Unknown Source)
21.03 10:20:59 [Server] INFO at java.util.ComparableTimSort.mergeCollapse(Unknown Source)
21.03 10:20:59 [Server] INFO at java.util.ComparableTimSort.mergeAt(Unknown Source)
21.03 10:20:59 [Server] INFO at java.util.ComparableTimSort.mergeHi(Unknown Source)
21.03 10:20:59 [Server] INFO java.lang.IllegalArgumentException: Comparison method violates its general contract!
21.03 10:20:59 [Server] INFO An unknown error occurred while attempting to perform this command

Modlist:
Minecraft Coder Pack;8.09;http://mcp.ocean-labs.de/
Forge Mod Loader;6.4.49.965;https://github.com/MinecraftForge/FML/wiki
Minecraft Forge;9.11.1.965;http://MinecraftForge.net/forum/index.php/topic,5.0.html
AppliedEnergistics Core;rv14.finale3;
CodeChicken Core;0.9.0.7;http://www.minecraftforum.net/topic/909223-
Forge Essentials|PreLoader;1.3.0.2;
Immibis's Microblocks;57.6.3;http://www.minecraftforum.net/topic/1001131-110-immibiss-mods-smp/
Micdoodle8 Core;;http://www.micdoodle8.com/
Not Enough Items;1.6.1.8;http://www.minecraftforum.net/topic/909223-
PowerCrystals Core;1.1.8;http://minecraft.curseforge.com/mc-mods/powercrystalscore/
OpenModsCore;@VERSION@;http://openmods.info/
Applied Energistics;rv14.finale3;http://ae-mod.info/Downloads/
BuildCraft;4.2.2;http://www.mod-buildcraft.com/
Universal Electricity;3.1.0;http://www.universalelectricity.com/
CalclaviaCore;1.2.0;http://calclavia.com/calclavia-core
Atomic Science;1.2.0;http://www.calclavia.com/atomic-science
Autoutils;1.0.1;
Backpack;1.28.37;http://www.minecraftforum.net/topic/1492661-
ComputerCraft;1.63;http://www.computercraft.info
BC Builders;4.2.2;http://www.mod-buildcraft.com/
BC Energy;4.2.2;http://www.mod-buildcraft.com/
BC Factory;4.2.2;http://www.mod-buildcraft.com/
BC Transport;4.2.2;http://www.mod-buildcraft.com/
MineFactory Reloaded;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
CoFH Core;2.0.0.5;http://www.teamcofh.com
Nether Ores;1.6.2R2.2.2;http://minecraft.curseforge.com/mc-mods/netherores/
Forge Multipart;1.0.0.250;https://github.com/Chicken-Bones/ForgeMultipart
Thermal Expansion;3.0.0.7;http://www.teamcofh.com
Big Reactors;0.3.4A2;http://www.big-reactors.com
bspkrsCore;v5.3(1.6.4);http://bspk.rs/Minecraft/1.6.4/bspkrsCore.version
BC Silicon;4.2.2;http://www.mod-buildcraft.com/
Additional Buildcraft Objects;1.0.7.560;http://www.minecraftforum.net/index.php?app=forums&module=forums&section=findpost&pid=8920844
Carpenter's Blocks;3.2.6;
ChickenChunks;1.3.3.3;http://www.minecraftforum.net/topic/909223
CoFH Loot;2.0.0.5;http://www.teamcofh.com
CoFH Masquerade;2.0.0.5;http://www.teamcofh.com
CoFH Social;2.0.0.5;http://www.teamcofh.com
CoFH World;2.0.0.5;http://www.teamcofh.com
Immibis Core;57.1.94;http://www.minecraftforum.net/topic/1001131-110-immibiss-mods-smp/
Dimensional Anchors;57.1.95;http://www.minecraftforum.net/topic/1001131-110-immibiss-mods-smp/
Dimensional Doors;1.6.4-R2.2.3;http://www.minecraftforum.net/topic/1650007-147smpssplan-dimensional-doors-v110-physics-what-physics-updated-with-fancy-opengl/
EnderStorage;1.4.3.5;http://www.minecraftforum.net/topic/909223
Equivalent Exchange 3;0.1;http://www.minecraftforum.net/topic/1106178-
Logistics Pipes;0.7.4.dev.205;http://www.minecraftforum.net/topic/1831791-
Waila;1.5.2a;
ExtraCells;1.6.8f;http://m3gafr3ak.github.io/ExtraCells/
Mystcraft;0.10.12.01;http://binarymage.com
OpenMods;0.5.1;http://openmods.info/
ProjectRed;4.3.7.32;http://projectredwiki.com
ProjectRed-Transmission;4.3.7.32;
OpenPeripheralCore;0.4.1;http://www.openmods.info
Extra Utilities;1.0.1;
Forge Essentials;1.3.0.2;https://github.com/ForgeEssentials/ForgeEssentialsMain
Galacticraft Core;2.0.14;http://www.micdoodle8.com/
Galacticraft Mars;2.0.14;http://www.micdoodle8.com/
Greg's Lighting;1.9.1;
Inventory Tweaks;1.56;https://github.com/Kobata/inventory-tweaks
Iron Chest;5.4.1.697;http://www.minecraftforum.net/topic/981855-
MFR Compat Forestry Trees;1.0;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat Extra Trees;1.0;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: Applied Energistics;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: Atum;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: BackTools;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: BuildCraft;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: Chococraft;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: ExtraBiomes;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: Forestry;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: Forestry (part 2);1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: ForgeMicroblock;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: IC2;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: Mystcraft;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: Pam's Mods;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
ProjectRed-Exploration;4.3.7.32;
MFR Compat ProjectRed;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: Railcraft;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: RP2;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: Sufficient Biomes;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: Thaumcraft;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: Thermal Expansion;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: TwilightForest;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: Vanilla;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
MFR Compat: XyCraft;1.6.4R2.7.8;http://minecraft.curseforge.com/mc-mods/minefactory-reloaded/
Modular Force Field System;3.6.2;http://www.calclavia.com/mffs/
Numina;0.1.2-55;http://machinemuse.net/
MachineMuse's Modular Powersuits;0.10.0-91;http://machinemuse.net/
NEI Plugins;1.1.0.6;https://bitbucket.org/mistaqur/nei_plugins/wiki
OpenCCSensors;1.6.4.4;http://www.computercraft.info
OpenPeripheralAddons;0.1.5;http://www.openperipheral.info
Power Converters;1.6.4-2.4.0.18;http://www.minecraftforum.net/topic/1695968-
Andrew's Modular Powersuits Addons;@VERSION@;
Project Bench;1.8.0;http://www.minecraftforum.net/topic/1550010-142132sspsmp-project-bench-forge/
ProjectRed-Transportation;4.3.7.32;
ProjectRed-Compatibility;4.3.7.32;
ProjectRed-Integration;4.3.7.32;
ProjectRed-Illumination;4.3.7.32;
ProjectRed-Expansion;4.3.7.32;
qCraft;1.1;http://www.qcraft.org
Redstone Arsenal;1.0.0.0;
Remain In Motion;1.1.7;
JAKJ_RedstoneInMotion_HollowCarriages;1.0;
Simply Jetpacks;0.1.4;
Steve's Carts 2;2.0.0.b10;
Trade Booth Mod;0.6.4.2;
Treecapitator;Forge 1.6.4.r09;http://bspk.rs/Minecraft/1.6.4/treeCapitatorForge.version
Vending;1.1.1;
Balkon's WeaponMod;1.6.2 v1.13.5;www.minecraftforum.net/topic/211517-bwm
WR-CBE Core;1.4.0.6;http://www.minecraftforum.net/topic/909223
WR-CBE Addons;1.4.0.6;http://www.minecraftforum.net/topic/909223
WR-CBE Logic;1.4.0.6;http://www.minecraftforum.net/topic/909223
Minecraft Multipart Plugin;1.0.0.250;https://github.com/Chicken-Bones/ForgeMultipart
Forge Microblocks;1.0.0.250;https://github.com/Chicken-Bones/ForgeMultipart

I realize this is a old version, but it would be amazing if this could be fixed or if someone knows if it's something I did wrong.

**Comment by helinus** [comment]
You are not running the latest FE version for MC 1.6.4
Get that from here http://minecraft.curseforge.com/mc-mods/74735-forge-essentials-74735/files/2217815
As we've moved on to MC 1.7.10 there's nothing else we can do
