### ISSUE TITLE
Overwrite deny protection with allow | missing permission-strings

### ISSUE THREAD

**Issue by NitroxydeX** [ForgeEssentials/ForgeEssentialsMain#1361]
Hey guys,

first of all: great work with the forge-version of Essentials. There are two problems I recognized during Essentials setup:

First: I didn't found a string to give an "admin"-group permissions to promote/demote user's to a group. Is there one or is this not implemented yet?

Second: Is there a way to set a weight for a permission string? e.g. We have a modpack-based server with MrCrayfishFurnitureMod on it. We protect areas and set deny to _ALL_ for break, place and interact but now we want to allow interaction with one block/item the door bell. So we set allow to _ALL_ for interact with the door bell with the string in the Permission List textfile but the user still can't use it. Any solutions so far?

Thanks for help :)

**Comment by DPxKnightxZero** [comment]
I would like all users who don't auth login be considered guests. not players.

**Comment by olee** [comment]
> We protect areas and set deny to ALL for break, place and interact but now we want to allow interaction with one block/item the door bell. So we set allow to ALL for interact with the door bell with the string in the Permission List textfile but the user still can't use it. Any solutions so far?

1. Use `/protectdebug` and / or `/p debug` to check if the permissions are correctly set.
2. A permission placed higher in the hierachy like `fe.protection.break.*` always has lower priority that for example `fe.protection.break.tile.stone.*`

**Comment by olee** [comment]
> First: I didn't found a string to give an "admin"-group permissions to promote/demote user's to a group. Is there one or is this not implemented yet?

Something like "sub-admins" with fewer access to permissions is not possible yet.
For that see #1355.

**Comment by olee** [comment]
As there does not seem to be any more activity on this and all questions should have been answered, I'm closing this one.
If there are still problems, ask again on IRC or here.

**Comment by NitroxydeX** [comment]
Yeah, Sorry. Your solution worked @olee :)
The strings in the list just ends with the block e.g. doorBell - but ingame it recognize it as doorBell.0 
/protectebug was the clue to fix this problem :)
