### ISSUE TITLE
Permissions Not Saving - Tried with new forge release 460

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentialsMain#1362]
After being told to update I cannot save permissions anytime the server shuts down and boots up all my permissions are gone.

**Comment by luacs1998** [comment]
Logs?

**Comment by DPxKnightxZero** [comment]
Okay here https://drive.google.com/file/d/0B1fY2sKXiHd7bmJPYk9TZnRuMUE/view?usp=sharing

**Comment by DPxKnightxZero** [comment]
The log was too big to post I sent you the full log because I never crashed :(

**Comment by luacs1998** [comment]
Seems like a dupe of #1354

**Comment by DPxKnightxZero** [comment]
What does that mean?

**Comment by olee** [comment]
This issue and #1354 are the same - it's a duplicate.

**Comment by DPxKnightxZero** [comment]
How is it the same?!!! Mine is not saving permission NO CRASH and his is CRASHING?~.~
