### ISSUE TITLE
Question about Scripting

### ISSUE THREAD

**Issue by FloxRoxX** [ForgeEssentials/ForgeEssentialsMain#1363]
Hello,
is there any further documentation for "Scripting" at ForgeEssentials ?
I try to make a teleport event for the group _GUESTS_ on player join but i dont know how to accomplish this without any documentation. I also searched the wiki but could not find a piece...

**Comment by luacs1998** [comment]
Create a file named _GUESTS_.txt in ForgeEssentials/Scripting/login/group.

The file should contain the command you want to run.
