### ISSUE TITLE
Fe Server crash on startup

### ISSUE THREAD

**Issue by Fundaris** [ForgeEssentials/ForgeEssentialsMain#1366]
Hi with FE Server 444+ my server crashes, when world gets loaded. There is a netherportal in spawn range.

http://pastebin.com/SsD3sv7f

dd1f898ea00795905e207ca4831aef2a0980c1be

**Comment by luacs1998** [comment]
Seems like a dupe of #1333

**Comment by Fundaris** [comment]
Lol this has nothing to do with the other ... i dont use mariculture or have problems with sanitychecker

**Comment by luacs1998** [comment]
Or some other issue...

**Comment by Fundaris** [comment]
When B:Teleport=false is set server crashes

**Comment by Fundaris** [comment]
is fixed with today builds
