### ISSUE TITLE
Permissions reset after server restart

### ISSUE THREAD

**Issue by Biofusionz** [ForgeEssentials/ForgeEssentialsMain#1367]
After restarting the server it crashed on startup with a crashlog mentioning FEPermissions. After starting it a second time it fully started but deleted the permissions and the backup of them,

Crashlog: http://paste.silvaniastudios.com/paste/view/a0a153b6

**Comment by liach** [comment]
I think that deleting those permissions also deleted the duplicated timer which caused the crash.. Hope for a fix.

**Comment by olee** [comment]
Should be fixed with 830e8ff72dff113f588c6c564e93458daf903186
