### ISSUE TITLE
Unexpected behavior from IRC Chat bot

### ISSUE THREAD

**Issue by Raniy** [ForgeEssentials/ForgeEssentialsMain#1369]
In chat.cfg if suppressEvents=true then no chat from the server will be relayed to IRC, but /me will be relayed. 

Setting suppressEvents=false results in Chat and server events being sent to the server.

I believe chat being caught in suppressEvents to be unintended behavior.

Forge 1291, ForgeEssentials FE 1.4.0-beta5 Server downloaded from:
http://minecraft.curseforge.com/mc-mods/74735-forge-essentials-74735/files/2227431/download

**Comment by luacs1998** [comment]
Update to a build from ci.forgeessentials.com
