### ISSUE TITLE
Crash report:  Exception in server tick loop 

### ISSUE THREAD

**Issue by Tar-Gilkaltar** [ForgeEssentials/ForgeEssentialsMain#1370]
Hello, Today I got up and met me this crash-report. You advise me with a solution? 
[link to pastebin.com!](http://pastebin.com/HYs7Ksd3)

Im using forgeessentials-1.7.10-1.4.0-beta5-server.jar
Thank you :)

**Comment by liach** [comment]
So you mean it's fixed in fe beta 6?

**Comment by Tar-Gilkaltar** [comment]
Probably the problem came after the creation of the project.I deleted DB with PROTEKT and everything is ok. :)
