### ISSUE TITLE
Server won't start with AppleCore installed (FastCraft incompatibility)

### ISSUE THREAD

**Issue by ultrasn0w** [ForgeEssentials/ForgeEssentialsMain#1372]
Hey FE Team,
Just grabbed the latest build and tried to run a Server, however the server crashes soon after starting.
I tried to disable FE again just to test and everything was fine.
Crash Report:
http://pastebin.com/0RF45LYT
AppleCore:
http://minecraft.curseforge.com/mc-mods/224472-applecore

Greetings
ultrasn0w

**Comment by luacs1998** [comment]
Give them a yell.

**Comment by ultrasn0w** [comment]
Okay.
https://github.com/squeek502/AppleCore/issues/17

**Comment by DPxKnightxZero** [comment]
Okay I have apple core installed and I don't have this problem.

**Comment by ultrasn0w** [comment]
@DPxKnightxZero Interesting, which build of FE do you have installed? It did work for me with an older build of FE, too.
However newer ones run in the issue described above. I can't exactly tell what build is the starting point, I wasn't able to test all.

**Comment by DPxKnightxZero** [comment]
470

**Comment by luacs1998** [comment]
So this is a problem between Fastcraft and AppleCore, from what I understand? Not our problem?

**Comment by valveo** [comment]
Looks like that. Temporary fix is disabling fastcraft.

**Comment by sfPlayer1** [comment]
The root problem is within ForgeEssentials, the Mixin code has to be loaded way earlier to not break class loading when it moves objweb.asm to the system class loader. Anything else is just relying on lazy linking by the jvm, which doesn't universally apply.

**Comment by luacs1998** [comment]
Which means I'll have to adjust the TweakOrder (but does FML acknowledge it?)

Will do some testing.

**Comment by luacs1998** [comment]
@sfPlayer1 is it possible for you to send me a copy of FastCraft with the following annotation added to fastcraft.core.LoadingPlugin:

`@IFMLLoadingPlugin.SortingIndex(value = 100)`?

**Comment by luacs1998** [comment]
Alright, seems that either Mixin upstream needs to change things, or a FML PR is needed.

**Comment by DPxKnightxZero** [comment]
The creators of fastcraft noticed this issue as well.

**Comment by luacs1998** [comment]
Yeah, kinda obvious since I spent an evening with Player debugging this...

We concluded that neither he nor I could do anything on our end to fix this.

**Comment by SakuraTheBabyfur** [comment]
Perhaps it would be worth noting that I was using a fairly old version of forge essentials, a beta 5 version, and it worked with fastcraft. perhaps that is useful?

**Comment by olee** [comment]
The reason is that FE uses mixin since beta6.
So actually the incompatibility should be Mixin <--> FastCraft

**Comment by luacs1998** [comment]
Yeah, I'll put in a note.

**Comment by melekaiah** [comment]
This is not just with fastcraft. Im getting this with beta 7 since somewhere mid beta6 dev when you added the mixin. ive been trying to figure out which mod crashes with it. or i dunno something. 

Having to use the beta 5 release until this is rectified somehow.

**Comment by luacs1998** [comment]
Moved to #1449
