### ISSUE TITLE
Permprops for difficulty

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentialsMain#1373]
I need to know in copy paste format what I would input to make it so when a user enters a zone it changes there difficulty to peacful. I am not sure how to type it.

**Comment by luacs1998** [comment]
Not sure if we have this... don't think so. Will mark as request.

**Comment by olee** [comment]
Just use `fe.protection.gamemode` permission.
Allowed values:
````
survival / s / 0
creative / c / 1
adventure / a / 2
````

**Comment by olee** [comment]
Oh sorry I have somehow mistaken your question for gamemode and not difficulty.
Difficulty is a server-wide flag and it is (without brutally forcing our way into MC) not possible.

**Comment by DPxKnightxZero** [comment]
Okay that would be greatly appreciated.

**Comment by olee** [comment]
For further help, it would be great if you join the IRC and ping me there.

**Comment by DPxKnightxZero** [comment]
Irc?
