### ISSUE TITLE
Unable to build project after ./gradlew setupDecompWorkspace

### ISSUE THREAD

**Issue by Loscillo** [ForgeEssentials/ForgeEssentialsMain#1378]
Hi,

After downloading your project, I installed following the procedure ForgeGradle ie `./gradlew setupDecompWorkspace`. I get Build Successful for this step.

But when I wanted to make the next step (`./gradlew idea`), I get Build failed with this message : 

    > Could not resolve all dependencies for configuration ':testCompile'.
        > Module version com.forgeessentials:ForgeEssentialsMain:1.4.0-beta6, configuration 'testCompile' declares a dependency on configuration 'default' which is not declared in the module descriptor for ForgeEssentialsMain:Mixin:unspecified

For your information I'm on Debian. I hope you can help me !

Have a nice day.

**Comment by luacs1998** [comment]
You need Git to setup the Mixin submodule. Building FE is not for the faint of heart.

**Comment by olee** [comment]
For a bit more help:
Run `gradlew eclipse` in the Mixin subdirectory after checking it out with `git submodule init` or so.th. like that.
