### ISSUE TITLE
Dimension Permissions

### ISSUE THREAD

**Issue by SakuraTheBabyfur** [ForgeEssentials/ForgeEssentialsMain#1385]
Is it currently possible, or will it ever be possible to assign permissions to dimensions, such that certain dimensions can have the permission system that a zone would, but encompassing a dimension instead of a zone?

**Comment by olee** [comment]
What do you mean with that?
> such that certain dimensions can have the permission system that a zone would

**Comment by SakuraTheBabyfur** [comment]
for example if i want to set a dimension named "creative" to force players into creative upon entry, i could use "/p global dimension creative value fe.protection.gamemode 1"

**Comment by olee** [comment]
Read the wiki.... :unamused: 
https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Permissions-tutorial#zones
