### ISSUE TITLE
how to delete a home?

### ISSUE THREAD

**Issue by lightning02** [ForgeEssentials/ForgeEssentialsMain#1388]
Well, i've set a home with the command /home <here|x, y, z> but i don't know how to remove it, the command /delhome doesn't work..someome can help me? :)
Ty in advance

**Comment by helinus** [comment]
I don't see a scenario where deleting a home is more useful than setting it to a new location or stop using the command.

**Comment by halvors** [comment]
Indeed. If you're a server administrator, you could always manyally delete the entry in the json file. It is in world/FEData/json/PlayerInfo/youre-uuid-here.json

**Comment by lightning02** [comment]
well, i have a server and i'm the administrator, i would like to give to my players the possibility to delete their home if they have to set another one and it becomes useless.
just a command for all players like the /delhome for vanilla server.

**Comment by halvors** [comment]
@lightning02 Well, you have only 1 home at time time right? So if you want to set a new one, just go somewhere else and type /home set no need for removal of the old first :+1:

**Comment by lightning02** [comment]
yes, right! but there is no way to remove it? :)

**Comment by halvors** [comment]
No ther isn't. But as @helinus said, just don't use it then. Or remove in the json file.

**Comment by lightning02** [comment]
ok! really thanks for your patience and availability

**Comment by evernife** [comment]
So, there is no way for me to set the VIP players have more than one home?

**Comment by olee** [comment]
That's what private-warps are for!
Home is just home.

**Comment by evernife** [comment]
Make sense :V
