### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by evernife** [ForgeEssentials/ForgeEssentialsMain#1389]
Where did the dialog files are stored, i want to translate them to my language (brazilian) but i cant find them.

Or best question, there is a way to translate them?

**Comment by luacs1998** [comment]
Dialogs cannot be translated, sorry, it's quite a mess, honestly.

**Comment by liach** [comment]
I really think you should support custom localization in Unicode. That makes sense for poor-English guys. Or .lang files?

**Comment by luacs1998** [comment]
We did support them, but then nobody added localization strings, nobody bothered to upkeep the current localization strings, and then porting the entire localization baking-in process to gradle was too much of a pain.

Hence removed.
