### ISSUE TITLE
Spawning mobs with eggs still possible after denying permission

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1390]
Restricting forced mob-spawn (e.g., spawn eggs) with permissions does with work.
Also natural spawn protection does only seem to work for hostile mobs.

**Comment by luacs1998** [comment]
Is this a problem with the FML event, or is this a problem with us?

**Comment by olee** [comment]
Ok it seems there have been some mistakes with the spawn events.
Checking the code, I've seen that SpecialSpawnEvent is **NOT** for spawn eggs, etc.
This means it would actually be better to just merge the `forced` permissions of this event and the `natural` of the CheckSpawnEvent to make it simpler for users.

Also this means that to disable spawn-eggs, the admins just need to deny the usage of the spawn-egg item (See #1357).
