### ISSUE TITLE
Permissions file

### ISSUE THREAD

**Issue by groveham** [ForgeEssentials/ForgeEssentialsMain#1397]
I believe I have all the settings set correctly but I cannot find the Permissions files anywhere. I'd rather edit them using a text editor if possible, it makes it easier for me to keep track of what groups have access to what commands. 
Follwing what the Github wiki states: "Permissions are stored in <world-dir>/FEData/permissions directory" no such directory has been created. I've mananged to create a 'members' group, assign a prefix and add my player into it, all which I can see when I join the server and chat, but I can't find any such file that reflects this. 
There are no errors in the logs and ForgeEssentials states that permissions saved sucessfully when I do /p save. It also comes up when I edit or add any permissions. 
I've coped my dir/ForgeEssentials/Permissions.cfs file below for reference which was generated by default. 

Permissions {
    # Choose a permission persistence backend (flatfile, sql, json)
    S:persistenceBackend=flatfile
    SQL {
        # If this is true, settings will be taken from the parent, most probably the Main or Core config. This is only taken into effect with remote databases.
        B:checkParent=false
        #  valid types: H2_FILE, MySQL
        S:chosenType=H2_FILE
        H2_FILE {
            # this may be a file path as well.
            S:database=.\ForgeEssentials/permissions
        }
        MySQL {
            S:database=ForgeEssentials
            S:host=localhost
            S:pass=password
            I:port=3306
            S:user=FEUSER
        }
    }
}

Am I missing something or is this a genuine bug of the files not being created?

**Comment by helinus** [comment]
The wiki says that permissions are stored in ``<world-dir>/FEData/permissions`` and that dir can not be missing. What page didn't have the ``<world-dir>`` part?
