### ISSUE TITLE
Afterlife Potion Effects + other small things

### ISSUE THREAD

**Issue by ultrasn0w** [ForgeEssentials/ForgeEssentialsMain#1399]
Hey there,
I set up the Afterlife module to apply some debuffs to my players when they respawn, however these are only applied on the first death. After a server restart they are applied again for only one time.

~~Also Bed respawning sometimes chooses some weird positions around the bed.~~

~~And the setting how many users need to sleep to get the majority is ignored.~~

~~Additionally, respawning in other dimensions sometimes glitches: A player respawns correctly at the custom set respawn, but appears to be respawned at 0/0 Coordinates for other players (only visually), interacting with something fixes this.~~

~~Last thing: Is there a way I can disable spawning of mobs in a certain dimension?~~

Greetings
ultrasn0w

**Comment by olee** [comment]
Please make separate issues if you have more than one problem that have nothing to do with each other.
[For mob-spawn control, read the wiki.](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Protection-%28world-guard%29#mob-permissions)

**Comment by ultrasn0w** [comment]
Thank you for the help and I'm sorry but I didn't want to spam the git. I'll do so.

**Comment by olee** [comment]
No problem!
(OT: I could never get angry with an Evangelion fan anyway :smile:)

Anyway:
I completely rewrote a lot of the Afterlife code and it seems to work perfectly now (see https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/70cc770c5adfd3edbe18b6fc2a8d89b55b9d44f4).
However the configuration of respawn-debuffs and deathchests are now handled by permission-properties and the [wiki](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Afterlife-Module) has not been updated yet.

So here's a short help (you should read the perm-tutorial wiki first though):
For example `/p global value fe.afterlife.debuffs 1:60:2,3:30` will apply two potion effects on respawn:
- Effect ID 1 (speed) for 60 seconds with amplifier set to 2
- Effect ID 3 (haste) for 30 seconds with amplifier 0 (default)

The other settings for afterlife can be configured in the same way.
Just take a look at PermissionList.txt

**Comment by ultrasn0w** [comment]
Awesome!
I already know a lot about the permission system, so this is just perfect.
BTW I'm rather thinking of some debuffs.

`(I love Rei)`

**Comment by olee** [comment]
Thank you for telling me - I did not notice it.
On Java 8 in my dev enviroment, it was running fine - however building it on Java 7 seemed to fail.
Anyway, it's been fixed: https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/18b08ca493305345b190a6960ef455c753aa3c0d
