### ISSUE TITLE
Block Itens?

### ISSUE THREAD

**Issue by evernife** [ForgeEssentials/ForgeEssentialsMain#1400]
Is there a way to block itens from be used?

Or a way to block itens from be used in specified groups or dimension.

I actually dont know if the ForgeEssentials offers a way to block itens, but, if doesnt' i suggest it to be in a next version because there is no other mod that do it in a good way.

**Comment by luacs1998** [comment]
We don't have item blocking per se, but we have prevention of item use.

@olee would it be feasible to do an inventory check on zone change regarding banned items?

**Comment by olee** [comment]
You can practically ban items with the `fe.protection.inventory` permission.
It will prevent you to pickup the banned items and if you enter a zone with items that are denied in it, they will be automatically dropped.

**Comment by olee** [comment]
Sorry, seems I forgot to add this to the wiki - it should have been in the PermissionList.txt however.

Now it is added and can be found here: [Protection (world guard) - Item permissions](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Protection-%28world-guard%29#item-permissions)

**Comment by evernife** [comment]
ty

**Comment by luacs1998** [comment]
copypaste from #1402

Hello, i tried to use the following perms:

fe.protection.inventory.[itemname].[meta]
fe.protection.use.[itemname].[meta]

I tried in the item: TwilightForest:item.iceBomb The id of the item is: 5191

fe.protection.inventory.TwilightForest:item.iceBomb=false
fe.protection.use.TwilightForest:item.iceBomb=false

fe.protection.inventory.iceBomb=false
fe.protection.use.iceBomb=false

fe.protection.inventory.5191=false
fe.protection.use.5191=false

But in any way it works, what i am doing wrong?

**Comment by olee** [comment]
Use `/protectdebug` and `/itemperm` to get the correct permissions.
And of course: **READ THE WIKI FIRST**
Seeing you asked these questions tells me you definitely didn't read it.
[Protection (world guard)](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Protection-%28world-guard%29)
