### ISSUE TITLE
Requesting long support for Economy module

### ISSUE THREAD

**Issue by ultrasn0w** [ForgeEssentials/ForgeEssentialsMain#1401]
Hello,
Yeah this may be a bit odd but would it be possible to make the money of players be stored in a long than an integer?
I have a Item Currency on my server and tried to build a Bank where these Items can be exchanged to currency, but the coin that is worth the most extends the Int limit:
https://i.imgur.com/fDwHZ4J.png

Greetings
ultrasn0w

**Comment by olee** [comment]
You are definitely doing something wrong if you reach wallet sizes greater than int-range :confused: 
However it still might be a good idea to change it to long.

BTW: How come you have such huge wallet values?

**Comment by ultrasn0w** [comment]
First of all thank you.
It's because I set up a coin system on a base of 64 potences;
	1x Starcoin =		1'073'741'824 NG
	1x Xe =			16'777'216 NG
	1x Kr =			262'144 NG
	1x Ar =			4'096 NG
	1x Ne =			64 NG
	1x He =			1 NG
I know this is mabe a bit overkill, but balancing the prices of various stuff on a hard-mode Server was hard.
