### ISSUE TITLE
Visual desync with custom set respawns

### ISSUE THREAD

**Issue by ultrasn0w** [ForgeEssentials/ForgeEssentialsMain#1407]
Respawning in other dimensions sometimes glitches: A player respawns correctly at the custom set respawn, but appears to be respawned at 0/0 Coordinates for other players (only visually), interacting with something fixes this and makes the player correctly appear at his actual position.

**Comment by olee** [comment]
While investigating #1396 I noticed that this might be a problem of MC / forge itself.
The respawn event is fired only **after** the MC respawn has been handled.
That is probably why you sometimes see players somewhere else for a moment.
