### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by SakuraTheBabyfur** [ForgeEssentials/ForgeEssentialsMain#1409]
I am not sure if this is forge essentials, and can not reliably replicate the results as this does not happen to me, but seems to happen to 80% of my player base on my server. I am posting this here as forge essentials is the only mod I can think of  that touches inventories. My issue is that whenever the server restarts, most of my players lose their inventories. I have look through logs, and have not seen anything related to inventories, nor any errors relating to player data in general. This has been happening for the last few days and I can not for the life of me find out why this is happening. As I said, I am not 100% sure it is forge essentials, but if there is anything that could help to either identify why forge essentials is doing this, or eliminate forge essentials as a suspect, it would be greatly appreciated

**Comment by olee** [comment]
If you did not set any special configuration for FE, there is no way it messes with inventories.
You should at last have added a list of the mods you use - though this is still nor our problem / fault.
Sorry.
