### ISSUE TITLE
/kit

### ISSUE THREAD

**Issue by evernife** [ForgeEssentials/ForgeEssentialsMain#1412]
the /kit dont work well

I make a kit naed /kit nb
I give the player the permisson and they can take this kit. The problem is:
I set the time for reuuse to 1200 seconds, (20 min) but, this time is not real, it is like 20 seconds, i will take a print later, i am going to school now, sorry for the lack os details

**Comment by olee** [comment]
The code for kits is very old and crappy.
The cooldown is handled by ticks.
So a kit cooldown of 10 is about 200ms.
Will change this to use actual time values and get rid of that nasty tick handler, too.
