### ISSUE TITLE
[Request] /home permission

### ISSUE THREAD

**Issue by Biofusionz** [ForgeEssentials/ForgeEssentialsMain#1414]
Would it be possible to have a seperate permission for /home instead of the full permission home.set. What we want to do on our server is have people not be able to set there home, but have an admin set it for them but they can still use the /home command. Also the ability to set peoples home. So I could do /home here Geoff, or something like that.

**Comment by olee** [comment]
And again.
As it has been said quite a few times, /home is for **player use**.
It servers as a simple, individual home location for each player that they can set themselves.
If you need some configurable teleport locations, you better look at `/warp` and `/pwarp`

**Comment by Biofusionz** [comment]
Can they be set so only one person can access that warp? What I want to do on our server, is have the user pay an ingame fee to get there home set, and then added to a permission group which allows them to use the /home command when they want. We had to do this to prevent people setting there home in a town, and just tp'ing there whenever they please to

**Comment by luacs1998** [comment]
Get the person to set a personal warp (/pwarp)?

**Comment by Biofusionz** [comment]
I'm not at my pc at the moment,  but it's not that pretty much the same as /home? We don't want people to set it themselves as they abuse it and set it in enemy towns so that can just to there anytime they want and raid it.  That's what we're trying to prevent by making them pay using the intake currency,  for an administrator to set there home in there own town or away from other people's.

**Comment by luacs1998** [comment]
How about a .nowarp additional perm node that prevents people from setting pwarps within a zone? Would that solve your use case?

**Comment by Biofusionz** [comment]
We don't use FE for towns, we use MyTown. And even if we could do that, there's the possibility of them setting the warp 1 block outside the town, which is why it needs supervision when being used

**Comment by olee** [comment]
Permission is `fe.teleport.home.other`.
Command is `/home set <playername>`.

**Comment by Biofusionz** [comment]
Does this include people not being able to set their home, but still being able to tp to it?

**Comment by olee** [comment]
https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Teleport-Module#home

**Comment by Biofusionz** [comment]
That's great,  thanks

**Comment by Biofusionz** [comment]
I've just managed to get this onto a server, fe.teleport.home does not do anything and does not show up in the permissions list file. Having fe.teleport.home.set to true, allows the /home command

**Comment by olee** [comment]
Of course it shows up in the [permission list](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/PermissionList.txt)!
````
fe.teleport.from                           # (default: true) Allow bypassing teleport cooldown
fe.teleport.home.other                     # (OP only: true) Allow setting other players home location

**Comment by Biofusionz** [comment]
On the wiki page, Command /home with permission [fe.teleport.home]
That isn't in the permissions list at all, and what I am expecting is to set that perm for them to be able to teleport, instead of fe.teleport.home.set which allows them to teleport and set home.

**Comment by olee** [comment]
Sorry, my bad.
It somehow misunderstood your question.
This was actually a bug and I fixed it now.

**Comment by Biofusionz** [comment]
So, I don't know if it's a bug or if I'm doing something wrong but, fe.teleport.home=false doesn't seem to block people from doing /home

**Comment by helinus** [comment]
that is because FE doesn't check the perm when using just ``/home``, something @olee missed when adding the permnode.

**Comment by olee** [comment]
@helinus you are right, there is no permission check *inside* the `processCommandPlayer` function.
But this is not a bug. Instead the permission `fe.teleport.home` is used for the whole command.
So if a player does not have this permission, he cannot use the command at all.

@Biofusionz You probably did not set the permission correctly.
Try using `/p debug` and then teleport yourself or stand next to someone using the command.
It will show you the permissions that are checked.
