### ISSUE TITLE
NickName not processing

### ISSUE THREAD

**Issue by evernife** [ForgeEssentials/ForgeEssentialsMain#1415]
I didnt know why, but i cant use a comand to this player: ZzBodyszZ
I tried to use tp command, and invsee, the same error, i post the error that i saw when i type 'invsee'

http://pastebin.com/mnsneAG3

**Comment by olee** [comment]
This does not seem to be the whole error message.
Please send us the whole error message from the logfile (not from console)

**Comment by olee** [comment]
About the command not working with this player:
You must have spelled his name wrong in one or another way.
Maybe this player used some irregular characters in his name.

You can try the following:
Type in `/p user Zz` (the first letters of this player's name) and then press TAB to let the command complete his name. You should be able to copy the TAB-completed name and use it for other commands correctly.
