### ISSUE TITLE
Backups not being pruned

### ISSUE THREAD

**Issue by xenoflot** [ForgeEssentials/ForgeEssentialsMain#1416]
Hi folks,

I've added forgeessentials-1.7.10-1.4.0-beta6 to my FTB Infinity 1.3.4 server (running under Windows 7x64). The backups appear to be being created correctly (not actually tried a restore, I should one day...) however they're not being pruned. In backups.cfg, enabled=true and I've set maxBackupLifespan=36 however I have backup zips in there that are several days old. It doesn't take long before the disk space is all used up so I'm having to manually prune things at the moment.

I have set the permissions on the forgessentials/backups folder to allow Everyone modify, read and write privs.

I notice in the logs that it seems to only be erroring on a subset of dimensions however DIM_0 is definitely affected despite the apparent lack of error.

Yes, I've read the readme, no I haven't modified anything in the backups folder other than Windows level permissions.

Are there any known conflicts with essentials and Infinity? Is there something I've overlooked?

Thanks 

Log: http://pastebin.com/ETLQqvhQ

**Comment by Flukethoughts** [comment]
this is a recurring issue lucas has fixed plenty of times it's best to prune them yourself and make sure u post the backups config file so lucas can also see that too

**Comment by xenoflot** [comment]
Thanks for the info. Backup config file per suggestion. http://pastebin.com/wajbrukc

For reference, after opening this ticker, I deleted the FE folder in its entirety and ensured I was on the latest version. Still happening.

Might also add that there's a typo on the last line of the backup config, "minimun"

**Comment by luacs1998** [comment]
Note that it needs to meet ALL the necessary criteria (meaning, your backup has to be at least 24 hours old, and you must have lesser than 20GB of space on your HDD).

Though, the minimum free space thing may be bugged - I don't have a small enough HD to test it...

**Comment by luacs1998** [comment]
Nothing? Reopen if it's still a problem.
