### ISSUE TITLE
Invencible permission.

### ISSUE THREAD

**Issue by evernife** [ForgeEssentials/ForgeEssentialsMain#1417]
Is there any permission to set a person invencible ?

I make a spawn, and set a zone, i remove the entitie damage, but, there is still the falling damage and some other by some mods. If there is a way to make them be in GodMod i will be really more easy.

Is there isn't a way to make is, this can be a request.

**Comment by olee** [comment]
https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Protection-%28world-guard%29
