### ISSUE TITLE
Add command manager to allow disabling / renaming commands for compability with other mods

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1419]
FE has a lot of commands that can possibly collide with commands from other mods.
That is why we should add a command manager class that takes care of registration of all commands and possible name collisions.

That way we can probably also simplify aliases and allow admins to rename FE commands themselves.

The reason for this feature is that a server owner reported a name collision of FE's mail command with forestry's `/mail` command.

**Comment by luacs1998** [comment]
Should we really do this, and so soon?

**Comment by olee** [comment]
Definitely - it should replace what was tried half-assed in commands module before.

**Comment by olee** [comment]
Fixed by https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/6b489608fd597e7f6126e411c2aac4073fc8dc25

**Comment by olee** [comment]
Only one thing was not added yet: Renaming of existing commands.
This would require changing *all* commands so they set a string variable in their constructor to the command name and **do not** overwrite the `ForgeEssentialsCommandBase.getCommandName()` functions. Then the config loader could easily change that string value to rename commands.
