### ISSUE TITLE
Removing "Teleporting. Please stand still for 03 seconds"

### ISSUE THREAD

**Issue by Nkaskaj** [ForgeEssentials/ForgeEssentialsMain#1420]
Hi again, I am sorry for annoying you, but I have problem. I need to remove "Teleporting. Please stand still for 03 seconds". Thanks :)

**Comment by olee** [comment]
Set `fe.teleport.warmup` permission property to the timeout you want or 0 / false to disable warmup.
`/p global value fe.teleport.warmup 0`
