### ISSUE TITLE
Server crash during startup with beta6

### ISSUE THREAD

**Issue by utoc** [ForgeEssentials/ForgeEssentialsMain#1421]
Good morning,

I have replaced beta5 with beta6 and get the following output upon start: http://pastebin.com/MndDemvF

For posterity, I also removed the worldedit jar from the mods folder and still crashed.  Putting beta5 back in place resulted in a clean load.

[minecraft@cubby] /home/minecraft/bbqsauce > java -version
openjdk version "1.7.0_76"
OpenJDK Runtime Environment (build 1.7.0_76-b13)
OpenJDK 64-Bit Server VM (build 24.76-b04, mixed mode)

Please let me know if I can be of further assistance.

**Comment by olee** [comment]
Please remove fastcraft if installed.
IIRC it is incompatible with FE since beta6.

**Comment by utoc** [comment]
Removing fastcraft and mariculture resulted in a proper load.  Thank you for the assistance.
