### ISSUE TITLE
Crash on PlayerLogger.serverStopped

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentialsMain#1422]
Alright so I had a fatal crash when testing forge essentials. https://drive.google.com/file/d/0B1fY2sKXiHd7OWtWVExzUW5yMTg/view?usp=sharing Please check it out and look into it.

**Comment by olee** [comment]
This exception should be literally impossible to happen at this place.
````java
    @SubscribeEvent
    public void serverStopped(FEModuleServerStoppedEvent e)
    {
        logger.close();
    }
````
What exactly did you do?

**Comment by DPxKnightxZero** [comment]
I will look. I understand it didn't look right to me either. I will give you the full log. Its rather huge though you have been warned. https://drive.google.com/file/d/0B1fY2sKXiHd7RDFPMzVDMmxxR1U/view?usp=sharing Its hard to decipher. Also if you want a copy of my server let me know.

**Comment by olee** [comment]
Please post logs where we can easily read them next time.
For example http://gist.github.com

**Comment by DPxKnightxZero** [comment]
Roger that! Okay so ... I lost the irc information you gave me and I forgot how to connect. Sorry sometimes I am super busy and I am simply waiting on fixes. Apologies.

**Comment by olee** [comment]
Test with latest version please.

**Comment by olee** [comment]
As long there is no more reply to this one, I'm closing it.

**Comment by DPxKnightxZero** [comment]
Sorry I was in the hospital for two days. I will make sure it works now.

**Comment by olee** [comment]
No problem :wink:
