### ISSUE TITLE
Return Of Fastcraft Issue? - Wierd Issues With Fastcraft

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentialsMain#1423]
Okay I posted this on their site but I am curious of anyone else has any of these issues when using fastcraft. https://drive.google.com/file/d/0B1fY2sKXiHd7YW4tOTlkN013Tm8/view?usp=sharing Please read carefully.

**Comment by olee** [comment]
Duplicate of #1372
