### ISSUE TITLE
/god

### ISSUE THREAD

**Issue by evernife** [ForgeEssentials/ForgeEssentialsMain#1426]
I want my moderators can make themselves invencible, but not have Creative.

But i want than to be invencible only for a period of time, only when they type the command /god for exemple.

If doesn't exist, make as request.

**Comment by olee** [comment]
You can achieve god-mode by permissions:
`fe.protection.damageBy.* = false`

However there is no way right now for players to give themselves this permission.

**Comment by Flukethoughts** [comment]
maybe in game method of redstone and command block where only mods and staff can go?

**Comment by luacs1998** [comment]
Actually, a /god command to allow players to set this permission themselves would be a better way. This would also allow players to "de-god" themselves if they decide they want to go back to being affected by mobs in the normal way, also without admin intervention.

**Comment by olee** [comment]
> However there is no way right now for players to give themselves this permission.
That's why I have written it that way.

I would say #1432 can take care of this.
The config for `/god` is already there as a sample.

**Comment by luacs1998** [comment]
Use the upcoming shortcut command system.
