### ISSUE TITLE
Prevent players with spaces in name (3rd party launchers) joining the server

### ISSUE THREAD

**Issue by evernife** [ForgeEssentials/ForgeEssentialsMain#1427]
I am having players with nicknames that has " SPACE " in them.

For exemple: Hyudy  habs

And when  i try to use a command on him i get a few problems.
I think it will be really good to have a way to restrict what type of nickames players can register (*AuthLogin*), like in the plugin AuthMeReloaded.

**Comment by olee** [comment]
Found on the web:
> The only way to get a username with spaces in it is with a cracked no-authentication client. Voting to close as off topic

We will not support offline-servers for players with cracked clients.

**Comment by evernife** [comment]
This make sence. But is still necessary, later or soon...
But Ty.

**Comment by olee** [comment]
It is not necessary, because names of minecraft players **do not** contain spaces.
Also not even one comand that needs a player name in any mod or minecraft itself could handle names with spaces.

**Comment by evernife** [comment]
"The only way to get a username with spaces in it is with a cracked no-authentication client. Voting to close as off topic" 

This ain't true.

There is a way to use a nickname like this (With space bars) with ORIGINAL LAUNCHERS.
For exemple, take a look in what i did.

******Using MultiMC, an no-cracked and authenticated client.******
https://github.com/MultiMC/MultiMC5/wiki/FAQ 
The First question solve the problem of the PIRATE LAUNCHER.
************************************************************************************

+++++++
+Now, to the bug itself.
+What had i done to test it:
+
+First Step --->   I launch in my original Minecraft account.
+http://prntscr.com/6wncuq
+
+Second Step ---> Press to play in Offline Mod. And put a nickname who has SPACE BARS. In this +case, i used "For Exemple"
+http://prntscr.com/6wnf6d
+
+Third Step ---> Join the server.
+http://prntscr.com/6wni0b
+++++++
Maybe, in the past, the only way to have SPACE in the nickname was with cracked launchers, but not today.

So, here is my suggestion, make rules for nicknames, For Exemple, block space bars in them.

**Comment by luacs1998** [comment]
There are rules, Mojang enforces them.

If you play offline you avoid the Mojang checks.

**Comment by olee** [comment]
As I already said:
> Also not even one comand that needs a player name in any mod or minecraft itself could handle names with spaces.

So what whole Minecraft does not support, we will not support as well.
What we can do however is an option to automatically kick players with spaces in their name.
That kick message can then tell them to fix their name.
That way you do not need to fear to have players that you can't interact with.

**Comment by evernife** [comment]
This will solve my problems. Thank You.
