### ISSUE TITLE
AuthLogin / Requested Changes

### ISSUE THREAD

**Issue by evernife** [ForgeEssentials/ForgeEssentialsMain#1428]
I have a mod called CustomNPCs, and, even when the player is not logged, the player can access an NPC with the NPC staff. Look, in otherwise than fix this problem isolatedly, it will be really nice to have two things implemented in the AuthLogin.

First, when not loggged, the player stay at the SURVIVAL, for exemplo, a moderator who previoulsy was in creative, when login again becames survival till finish the login.

Second, create an ''false inventory'' just for people dont see what itens other people have.

Third, set a (CONFIGURABLE) limit time for people login, for them dont get stuck filling a place in the server, for exemple, someone join my account and say not logged just for me dont login. ( I dont know if this exist, or something like, but i write here because i remember it was important.)

If its possible, of course.

**Comment by luacs1998** [comment]
All of it should be possible, but it depends when I have time to write it :P

**Comment by evernife** [comment]
Yeah :D
I will be really gratftul, i have Original Minecraft, but, there is a large ammout of players who dont have, and if you see, the most part who will use this mod is non original. Your work is really appreciated by myself.

**Comment by olee** [comment]
@luacs1998 
As for inventory, we should be able to use some events / send some packages to prevent the player from opening it. I have a few ideas where to look for that so if you are going to do this and get stuck, ask me.

As for interaction, we should make players who are still logging in have permissions set to `* = false`. This will prevent them from doing anything and should suffice.

The timeout would be easy as a CFG variable of course...

**Comment by olee** [comment]
Moved from #1434 here
Also make player invulnerable until he is logged in.
Should happen automatically if permissions are set to `* = false` because that way `fe.protection.damageBy` is also `false`

**Comment by luacs1998** [comment]
There are *ZERO* inventory events in Forge. Mixins will most likely be required.

**Comment by olee** [comment]
Ok as #708 is planned, this issue will become useless.
Therefore I am closing this and we will take care of it by auth-rewrite instead.

PS: As for inventory events, these will be taken care of in #1394.

**Comment by evernife** [comment]
Can you re-open this. As the #708 is actually not viable and need to wait a bit more, this should be fixed, in my vision, since it is a dupe bug.

As i suggested before:
-Make a pseudo-inventory before the player login. This shoul take care of #1394 too

**Comment by evernife** [comment]
Gentlemens, any progress in this?
As i said before, this is a dupe bug... really, this is making me spend much time controling the players to not kill themself and dupe the items....

**Comment by olee** [comment]
If you would just enable and use default Mojang authentication, it would be soo much easier...
Currently I have my hands full with other important stuff to fix so I don't know when I will have time to fix this. Someone else might have time though...

**Comment by evernife** [comment]
I know you are busy... sorry.
I am just asking...
(
A few exemples for the "someone" who will fix this, 
http://prntscr.com/75vvrl
http://prntscr.com/75vvm3
)

("If the module exists, we should use it :D" )

**Comment by olee** [comment]
As I said: Deactivate the offline-mode of your server if that is such a problem for you, until this has been fixed...
Even if you keep complaining, there's other important stuff we need to fix that possibly affects way more players. Please refrain from asking for progress on this issue. We already invest a lot of our free time into FE and try to clear issues asap and as we see it fit.

**Comment by olee** [comment]
Will cover this as part of #1514 as it aims at preventing any player interactions as well
