### ISSUE TITLE
Auto AFK KICK

### ISSUE THREAD

**Issue by evernife** [ForgeEssentials/ForgeEssentialsMain#1431]
A system that kick players for inactivity.
For exemple, a player got automatically afk after a determined time, and after another determined time het get kicked from the server (this should be made in permission system, and, for exemple, VIP player dont get kicked)

Another point, controle de frequency players can get afk, because this FLOOD the chat with mensagens...

NOTE: I saw the AFK system existent. but i didnt notice the auto afk, or afk kick, this is why i am creating this ^^

**Comment by olee** [comment]
Considered for addition.
Please wait until we have time to add this feature (though I'm quite interested in it)

**Comment by evernife** [comment]
Okey dokey

**Comment by luacs1998** [comment]
Simple enough. We have auto-afk, the same mechanism can be enhanced for afk kicking.

**Comment by luacs1998** [comment]
You can deny fe.commands.afk.notice if you don't want player AFK notices to show in chat.

**Comment by evernife** [comment]
But, I am just telling that this is problematic, I don't think that server owner well keep this "function" if the players start to flood his chat.

It is just boring. This is what i am trying to saying :D 

It would  be nice to have a ''Cooldown" for players to use this command [/afk]. 

This change is not too necessary.... but, in my vision, the way it is now is not too functional.

**Comment by olee** [comment]
Players can flood the chat just with chat messages which is even easier....

**Comment by evernife** [comment]
So, you discover. An anti flood system would be useful. (any way,  Actually, when a player try to flood the chat he get kicked from the server)

We should use the tempban system #1424 to fix this. When a player flood the chat with a lot of mensagens he get banned from "X" min.

**Comment by luacs1998** [comment]
We don't have auto-AFK???

Will be adding it.
