### ISSUE TITLE
New scripting system / pattern commands

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1432]
Proposal for a new shortcut command system.
Draft description in second post.

**Comment by olee** [comment]
Shortcut commands are saved in the FE data folder.

Each shortcut command has a command name and one or more matching patterns with assigned actions.

## Sample /god command

````
{
	"command": “/god”,
	"permission": “fe.commands.god”,
	"patterns" {
		"on @1p": [
			"permcheck multicmd.god.others",
			"/p user %1 deny fe.protection.damageBy.*",
			"/heal @player",
			"echo God mode turned ON for %1"
		],
		"on": [
			"permcheck multicmd.god.others",
			"/p user @player deny fe.protection.damageBy.*",
			"/heal",
			"echo God mode ON"
		],
		"off @1p": [
			"permcheck multicmd.god.others",
			"/p user %1 clear fe.protection.damageBy.*",
			"echo God mode turned OFF for %1"
		],
		"off": [
			"/p user @player clear fe.protection.damageBy.*",
			"echo God mode OFF"
		],
		"": [
			"echo Usage: /god on|off [player]",
		]
	}
}
````

The order of the patterns is important so if it is lost during load, because there might be cases where more than one pattern matches.

## Patterns

General syntax should be like "@<ID>[modifier]".

The ID is always needed and will be inserted into executed actions with String.format().

The modifier is optional and it can influence matching and perform additional checks.

If we manage to add a little bit of tab completion as well, these will come in handy.

* p → Match a player
* g → Match a group
* d → Match decimal
    * Maybe allow specifying value ranges after the modifier in some way
* f → Match a float
    * See decimal

## Actions

In all actions the matched arguments from the pattern are usable.

We should also provide some modifiers / functions to allow modification of arguments (e.g., "echo Your player ID is uuid(%1)" or something like that.

* `echo <message…>`
    * Prints a message
    * Matched arguments and color codes are usable
* `/<cmd>`
    * Run a minecraft command
* `permcheck <perm> [message]`
    * Checks a permission
    * Maybe allow an optional message to be shown if the check fails
* Permission modification
    * Either make a specialized action that acts the same as **/p**
        * perm player %1 allow fe.protection.damageBy.*
    * Or directly use **/p** but make sure **/p** does not check permissions
* `timeout <name> [duration] [message]`
    * Check and start a PlayerInfo.timeout()
    * Display message if failed
* Maybe: Mathematical operations
* Maybe: Conditionals

## Setup command
A command to configure shortcuts is really optional and should probably be left out. However I want to specify how it could look like if implemented in this draft.

The user would setup the command step-by-step
````
/shortcut <name> create
/shortcut <name> pattern				// Lists patterns with IDs
/shortcut <name> pattern add <pattern….>		// Add a pattern
/shortcut <name> pattern del <id>			// Delete a pattern
/shortcut <name> pattern <id> actions		// Lists actions with ID
/shortcut <name> pattern <id> add <action…>	// Add action to pattern
/shortcut <name> pattern <id> del <action-ID>	// Delete action
/shortcut <name> pattern <id> clear			// Clear all actions
````

**Comment by olee** [comment]
There will probably be no command for this, as it is too complicated to set up and better be done by editing files.

**Comment by evernife** [comment]
There is a date for this new shortcut command system ?
I find this one a bit more easy to use than the actual.

**Comment by olee** [comment]
Today. But in the future please don't ask for ETA. We will finish stuff as we have time for it.

**Comment by evernife** [comment]
sorry :D

**Comment by olee** [comment]
Updated the description in the second post.

**Comment by olee** [comment]
Fixed by https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/cf2250580b09d86d673e4601a180589a334f9b5e

**Comment by olee** [comment]
If you have any suggestions for scripting / pattern commands, please post them here.
I will leave this issue open for about two weeks until we got some suggestions and will close it all has been finished.

**Comment by olee** [comment]
Wiki has been updated at https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Scripting
