### ISSUE TITLE
Kit/ probably user error.

### ISSUE THREAD

**Issue by evernife** [ForgeEssentials/ForgeEssentialsMain#1433]
I am trying to set a kit: /kit <name> set <time>

I tried it: /kit nb set 1200   -->Didnt work.

Then, i tried it: /kit nb set --->Work fine, cooldown set to 0-1 sec

Was the command changed ? Or the time cooldown was deactivated?

(USING BUILD #5​14)

**Comment by olee** [comment]
@luacs1998 please check.
Probably some mistake from https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/102eaf62cdb7d371a843da39ba62ea85a87971fd
