### ISSUE TITLE
AuthLogin Dupe Itens

### ISSUE THREAD

**Issue by evernife** [ForgeEssentials/ForgeEssentialsMain#1434]
Before the player loggin the server, there exist two of him. 

And, if you kill one of the two, you can take the itens.
After you take the itens, the player effetue login and have his items back.

The dupe consiste on the duplication of the players itself, This does't occurs everytime, but if you try 4 ou 5 times you cant get it.

**Comment by olee** [comment]
Please check your English.
That way I cannot understand what you want.

**Comment by liach** [comment]
>Before the player log in the server, two players of the same guy exist. 
>
>And, if you kill one of the two players, it drops items.
>After you take the items, the player re-login and have his items back?
>
>The dupe consists(depends?) on the duplication of the players itself, This doesn't occur every time, but >if you try 4 to 5 times you can find it out.
> - evernife
Is it?

**Comment by evernife** [comment]
Yes yes, sorry, it was my brother who wrote this.
In any case. What's going on is what you said.

**Comment by olee** [comment]
Moved
