### ISSUE TITLE
Some Players cant join The server

### ISSUE THREAD

**Issue by evernife** [ForgeEssentials/ForgeEssentialsMain#1435]
Getting this error: http://pastebin.com/D9frjKWJ

Client side response: was forced to cancel an existing connection by the remote host (or something like)

**Comment by olee** [comment]
@luacs1998 it's your weird welcome-kit code.
Please just remove the config-variable and just use a static name "starterkit" to make it easier to manage.
We should try to reduce required CFG editing.
