### ISSUE TITLE
Idea  / MyTown2

### ISSUE THREAD

**Issue by evernife** [ForgeEssentials/ForgeEssentialsMain#1436]
I have both ForgeEssentials and MyTown2.
Both are great mods, and i think the protection system of MyTown2 really good.
What do you think about implement (co-work) MyTown2 and ForgeEssentials, it could be make as an alternative module.

I am just a user, i dont know if they will like the ideia, or either you. But, for me, being an server admin, i will make really more easy.

(NOT SO IMPORANT, JUST AN IDEIA)

**Comment by olee** [comment]
MyTown will become useless and you can remove it when plots is finished, because FE's protection is way better (#1189).
Just wait for that.

**Comment by evernife** [comment]
Turn town for what.... Amazing, your work is really amazing :D 
Nice work team :D

**Comment by StoneLegion** [comment]
@olee ha
