### ISSUE TITLE
Why remove sqldb

### ISSUE THREAD

**Issue by Goten87** [ForgeEssentials/ForgeEssentialsMain#1438]
If I can ask why did you remove this it was a nice function for logger and permissions
I used to do it all from my website atleast read out the logger and permissions was w8ting for a update to 1.7 to continue the website but if you removed all the database options I don't need to anymore
I used MySQL

**Comment by olee** [comment]
It was only removed for FE data.
Permissions and PlayerLogger are still usable with SQL.
