### ISSUE TITLE
Rename repository to ForgeEssentials

### ISSUE THREAD

**Issue by halvors** [ForgeEssentials/ForgeEssentialsMain#1439]
Rename repository to ForgeEssentials? Why is it called ForgeEssentialsMain?

**Comment by olee** [comment]
Becuase.

**Comment by halvors** [comment]
Ok... If there is no reason, i suggest that you rename it, i think people find it confusing...

**Comment by olee** [comment]
Because *just* renaming the repository causes a **huge load of problems** and is totally **unnecessary**.

**Comment by luacs1998** [comment]
Renaming the repository is not as hard as you think.

Github is nice enough to setup HTTP redirects for you (though I'm not sure how long they las)
