### ISSUE TITLE
Rename repository to ForgeEssentials

### ISSUE THREAD

**Issue by halvors** [ForgeEssentials/ForgeEssentialsMain#1440]
@olee You locked the conversation?

@luacs1998 I know.

**Comment by halvors** [comment]
#1439

**Comment by luacs1998** [comment]
@halvors that is no way to be talking to people, honestly.

It just never crossed our minds.

**Comment by halvors** [comment]
@luacs1998 I'm sorry, that came out wrong. I'm only asking you to consider it. :) By lazy, what i actually meant to say was that it sound to me like you're avoiding to rename it because there is some refactoring etc that may need to be done, and i think you guys prioritize development and as you say:

```
If it ain't broke, don't fix it.
```

**Comment by halvors** [comment]
Also sorry for creating an new issue. But was unable to discuss this further since @olee locked it.

@luacs1998 Should i close this or leave it open?

**Comment by liach** [comment]
Why need to change its name? You'd better update mixin instead of changing its name :shipit:
