### ISSUE TITLE
NOOB - Persmissions 1.7.10

### ISSUE THREAD

**Issue by slicksniperkills** [ForgeEssentials/ForgeEssentialsMain#1441]
Hello all,

once again I would like to say forgive me for being a noob at this stuff. But my question today is how does one create or access permissions or groups without being on the server. I would like to make [FOR EXAMPLE] an admin group but I dont know how to make it since I do not see a file for the permissions or groups only a permissions.txt

**Comment by evernife** [comment]
Seek in the: /"world"/FEData/permissions/groups

"world" Your named world.

**Comment by slicksniperkills** [comment]
Wow thank you. Told you I was a noob

**Comment by evernife** [comment]
(better close)

**Comment by olee** [comment]
@slicksniperkills If you want to modify permissions while the server is running, without connecting as a player, I can recommend you to use [FE remote](https://github.com/ForgeEssentials/FERemoteClient) instead. It features a powerful permission editor (WIP - but this one works already)

**Comment by olee** [comment]
@slicksniperkills Also about your question, the solution was just here:
https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Permissions-System-and-Zones#flatfile-formats

**Comment by slicksniperkills** [comment]
What does FE remote do mate?

**Comment by olee** [comment]
Remote server management tool.

**Comment by evernife** [comment]
"
JavaFX based client to use the ForgeEssentials remote API.

It allows easy management of FE-based servers, without the need to log into the server.
"
