### ISSUE TITLE
Chat Range

### ISSUE THREAD

**Issue by evernife** [ForgeEssentials/ForgeEssentialsMain#1445]
I was thinking that should exist a way to control the range of chat, for exemple, what the player say is only shown for them who is in a "X" distance from him.

For exemple, 50 blocks from him.

And maybe: (DIM CHATS) (ZONES CHATS)  (GROUPS CHATS)

[I read some time ago that the CHAT was a bit complicated to manage, but, it is just a suggestion. This could be really useful for servers that hade a lot of players.]

**Comment by olee** [comment]
Would be done if I get some time to do #1345.
Otherwise I will do it when I get time to review the chat module.

@luacs1998 Want to take care of this? The whole chat module needs a lot of cleaning up.
