### ISSUE TITLE
Request /reload

### ISSUE THREAD

**Issue by Nkaskaj** [ForgeEssentials/ForgeEssentialsMain#1446]
Please add new command /reload like in Essentials

**Comment by liach** [comment]
The command could reload FE, Forge or Other mods?

**Comment by evernife** [comment]
there is one, /feperm reload
It reloads the permissions...
}Really useful.
But, in fact, i dont find this (/relaod for the entery mod) really necessary, most of the FE things can be done in game...

**Comment by Nkaskaj** [comment]
When you write /reload it will reload FE, Forge and mods and you can also write /reload fe   /reload forge    /reload mods

**Comment by liach** [comment]
Um. It's very nice to reload mods and configs, in the way that bukkit plugins does.

**Comment by evernife** [comment]
Just to say, but forge is a bit more difficult than bukkit, but lets see what they say about it.

**Comment by Nkaskaj** [comment]
(y)

**Comment by olee** [comment]
@Nkaskaj what should `/reload` do?
We have the command `/feinfo reload` which reloads FE config if that is what you want.

**Comment by liach** [comment]
I mean /reload could make other mods reload their configs...

**Comment by olee** [comment]
First:
We don't care about **other** mods and we will not start to do so (or our work would never end).

Second:
We already provide `/feinfo reload` to reload FE configuration.
We will **not** take care of stuff other mods do because there is nothing like a common configuration API.

**Comment by luacs1998** [comment]
The way you want it to be done, it has to be done by forge.

We could do it, but here's why not:

1) We have to ASM into forge, and that is high treason

2) cpw and friends already experimented with reloading mods, it blew up in their faces

3) Why don't you think about why Cauldron removed it...

**Comment by evernife** [comment]
"Headshot, Headshot, Headshot, Unbelievable...."
