### ISSUE TITLE
Player item trading

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1454]
Allow players to sell items to each other for money

**Comment by luacs1998** [comment]
I implemented this halfway in the old economy... not sure if you removed it.

**Comment by olee** [comment]
Sorry, didn't deem that code as really useful for item trading (noticed that it was supposed to be used for that kind of thing later) so I removed it.
I already have trade functionality present for plot trading so I can transfer that functionality over to item trading.
