### ISSUE TITLE
Question - Does forge essentials use the vanilla "team method"

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentialsMain#1457]
I am working with a creator of pokecube and he was wondering if you use the team method.

**Comment by luacs1998** [comment]
Team method? No I don't think so.

**Comment by liach** [comment]
That's net.minecraft.scoreboard.team?

**Comment by olee** [comment]
Please explain in more detail what you want to ask.
What team method are you talking about and for what should we use it?

**Comment by DPxKnightxZero** [comment]
I am not sure tuhtmose asked me to check because I use forge essentials on my server and now pokecube and he asked me to ask you this question because his mod will ignore your anti-spawn method if you don't.

**Comment by liach** [comment]
Then let him come for further explain.

**Comment by olee** [comment]
That should be better because I could not really understand you (sorry) bad English description.
