### ISSUE TITLE
Protection permissions / IC2

### ISSUE THREAD

**Issue by blkwind** [ForgeEssentials/ForgeEssentialsMain#1464]
I am having a issue banning items on the current build of FE, the Item  in question is the digital miner from mod Mekanism.
Its /itemperm is tile.MachineBlock.DigitalMiner.4. So i use the /p group _OPS_ deny fe.protection.place.Mekanism.MachineBlock.DigitalMiner.* and it doesnt work. I tried /p group _OPS_ deny fe.protection.place.Mekanism.DigitalMiner.* and .4 and neither work. I tried the autocomplete after the "Mekanism." and it never lists the digital miner, this is also true if i do it under inventory. 

So I tried preventing placement of another item from mekanism, the SlickPlasitcBlock /itemperm tile.SlickPlacticBlock.9 using the /p group _OPS_ deny fe.protection.place.Mekanism.SlickPlasticBlock.* and it works fine. however that block is listed via autocomplete feature.

**Comment by blkwind** [comment]
I also tried using "/p group _OPS_ deny fe.protection.use.Mekanism.MachineBlock.DigitalMiner.4" the digital miner nor machineblock is listed under the autocomplete also.

**Comment by blkwind** [comment]
I am having the same issue with Inustrialcraft 2 Mod. the item in question is the advanced miner /itemperm ic2.blockAdvMiner.11. It also doesnt ever show up in autocomplete however is i do "/p group _OPS_ deny fe.protection.place.IC2.blockMachine2.*" it works and i cannot place the item, agian it prevents most of the machines from being placed, which is again bad.

**Comment by olee** [comment]
I am currently on a trip, but I will try to find some time to check this out. 

I have a server running IC2 and Fell so it should be easy.

**Comment by blkwind** [comment]
Thanks Olee!

**Comment by olee** [comment]
I don't know if any change to the protection permissions fixed this already.
@blkwind do you know, if there are still problems banning block placement like these in latest versions?

**Comment by olee** [comment]
As there has been no more activity and as far as I know the block protection works reliably for now, I am gonna close this for now.
