### ISSUE TITLE
Server Crash FTB Infinity

### ISSUE THREAD

**Issue by rhwilr** [ForgeEssentials/ForgeEssentialsMain#1465]
I'm using the latest FTB Infinity pack. As soon as I put forgesessentials into the mods folder, the server crashes immediately.

Crashlog: http://pastebin.com/N8535Snf

**Comment by evernife** [comment]
remove "fastcraft"

**Comment by rhwilr** [comment]
This works. But I hope this gets fixed. I'd love to use fastcraft since it is a great improvement to the tps.

**Comment by evernife** [comment]
Take a look here: #1449
They are already working on this.

**Comment by luacs1998** [comment]
https://twitter.com/luacs1998/status/592513216963432448

Grab the fixed Forge 1395 from there.

**Comment by evernife** [comment]
This custom forge creats an error. http://pastebin.com/cjJkhah7 : c

**Comment by liach** [comment]
1399 has already come out. Yummy...

**Comment by olee** [comment]
@evernife Can you confirm this only happens with the custom forge version?
I had that same crash on my server as well once and it seems to be related to fluid changes in forge maybe.

**Comment by olee** [comment]
Also found this one:
http://www.minecraftforum.net/forums/support/modded-client-support/2405760-client-crash-upon-searching-for-ender-tank-in-nei

**Comment by evernife** [comment]
i will try to update the mod version.

**Comment by olee** [comment]
@evernife See https://github.com/Chicken-Bones/EnderStorage/issues/29
I already checked it myself - a fixed version has not been released yet.
Just have to deal with it and tell users to not use NEI / EnderStorage too much.

**Comment by evernife** [comment]
ty bro, this helped me :D
