### ISSUE TITLE
World Edit Issue Causes Timeout - Does not create crashlog

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentialsMain#1466]
03.05 09:11:31 [Server] Server thread/WARN [FML]: =============================================================
03.05 09:11:31 [Server] Server thread/WARN [FML]: Use FMLCommonHandler.exitJava instead
03.05 09:11:31 [Server] Server thread/WARN [FML]: Offendor: antlr/Parser.panic()V
03.05 09:11:31 [Server] Server thread/WARN [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
03.05 09:11:31 [Server] Server thread/WARN [FML]: =============================================================
03.05 09:11:31 [Server] Server thread/INFO [ForgeEssentials]: WorldEdit selection provider started.

**Comment by olee** [comment]
As already said before, this is just a *warning* which is caused by loading the Hibernate ORM library and does not affect the game in any other way.
