### ISSUE TITLE
Permissions with zones/areas not working?

### ISSUE THREAD

**Issue by Mandelsage** [ForgeEssentials/ForgeEssentialsMain#1467]
Hi,

I'm trying to set an area to be protected against breaking and placing blocks. First, I chose the area with the wand, and defined it. I then created a new group, and put in this command to set permissions for it:
`/p group mygroupname zone myzonename deny fe.protection.break.* fe.protection.place.*`

I then added a user (a friend of mine) to this group, to test things. He could place and break blocks. He was opped at first, so I deopped him. He could still place and break. I then put /p debug on and it was saying that he was in the zone _ALL_ and in the group _OPS_ (He was definitely not opped anymore. I checked the ops.json file).

Am I doing something wrong or... ?

EDIT: I just tried the commands `/group mygroupname zone myzonename` and `/user myfriendsusername zone myzonename` ... The first one seems to work fine, but the second one says: "An unknown error occurred while attempting to perform this command."

I checked the server logs: 

````
03.05 17:03:08 [Server] INFO at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
03.05 17:03:08 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
03.05 17:03:08 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
03.05 17:03:07 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
03.05 17:03:07 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
03.05 17:03:07 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
03.05 17:03:07 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
03.05 17:03:07 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
03.05 17:03:07 [Server] INFO at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
03.05 17:03:07 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
03.05 17:03:07 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
03.05 17:03:07 [Server] INFO at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
03.05 17:03:07 [Server] INFO at com.forgeessentials.permissions.commands.CommandPermissions.func_71515_b(CommandPermissions.java:56) ~[CommandPermissions.class:?]
03.05 17:03:07 [Server] INFO at com.forgeessentials.permissions.commands.PermissionCommandParser.parseMain(PermissionCommandParser.java:105) ~[PermissionCommandParser.class:?]
03.05 17:03:07 [Server] INFO at com.forgeessentials.permissions.commands.PermissionCommandParser.parseUser(PermissionCommandParser.java:255) ~[PermissionCommandParser.class:?]
03.05 17:03:07 [Server] INFO at com.forgeessentials.permissions.commands.PermissionCommandParser.parseUserInner(PermissionCommandParser.java:311) ~[PermissionCommandParser.class:?]
03.05 17:03:07 [Server] INFO at com.forgeessentials.permissions.commands.PermissionCommandParser.parseUserInner(PermissionCommandParser.java:278) ~[PermissionCommandParser.class:?]
03.05 17:03:07 [Server] INFO java.lang.NullPointerException
03.05 17:03:07 [Server] INFO [17:03:07] [Server thread/ERROR]: Couldn't process command: 'p user noblesix117 zone hillsofriven'
````

**Comment by olee** [comment]
About the OP problem:
Check it again if he really is no OP (i.e. use `/deop` again) and also try to remove him from the group manually (maybe you added him yourself?) with `/p user <name> group remove _OPS_`.

The other thing seems to be a bug and I will take care of it.

**Comment by Mandelsage** [comment]
Hi olee! ... I've found out what's going wrong.

I went into the FEdata folder, inside the world folder, and went to permissions/world_0/mygroupname
There I found the area.xml file. Looking at it, I noticed all the position values (x1, x2, z1, z2 and y1 and y2) had values of "0" .. I changed them manually to the positions I wanted, and it seems to work now! So the bug is actually that, selecting a region with a wand and then defining it doesn't work. =)

**Comment by olee** [comment]
Seems like you did not select it properly for some reason.
If you use FE normally with the bundled WorldEdit, it should work perfectly.

**Comment by Mandelsage** [comment]
I checked it out and I just couldn't understand what I was doing wrong... Until I realised I was using the normal //wand from WE instead of binding //fewand to something....... *sheepish grin*

About the other issue with "/user myfriendsusername zone myzonename" ... Can I do this manually by copying a "players" folder into the area I want? For example, setting a user's individual permissions and then pasting their player permissions file into a "players" folder inside "world_0\myareaname\" ?

**Comment by olee** [comment]
Normally if WorldEdit is loaded, FE will not register `//fewand` and instead use the WorldEdit selections.
Did you use the latest FE?
