### ISSUE TITLE
Massive Block break event Leak From other mods?

### ISSUE THREAD

**Issue by KaneHart** [ForgeEssentials/ForgeEssentialsMain#1468]
I found this issue: http://i.imgur.com/namlwwS.jpg
That is all the world has a dozen or so Quarrys fresh world etc. AE system and chests..

Anyways it seems like FE is going insane block breaking event checks?
http://i.imgur.com/frtCo56.png

Idk how you plan on fixing this. But I'm more worried even improved the overall impact. Can we have a option to disable block break checking period? Since I don't use it on my server nor do I think I will use the protection system.

**Comment by KaneHart** [comment]
To confirm this I removed FE and tps was 20 I could add dozens of more quarries without issues. Damn this is a nasty one I hope you can figure it out.

Best setup just setup like 30+ BuilCraft quarries with energy cell / ender chest.

Just throw them all into a AE system or null them that should work.

Once again confined multiple times :(

@olee

**Comment by evernife** [comment]
LOL, nasty problem :/
In my server carry is blocked, i was planning to set it free.

Not anymore --'

**Comment by KaneHart** [comment]
I talked to asie and BC one the few mods and I remember this added ages ago fires the correct events. So block break fake player etc. I know for sure I ran server past using bukkit style mods for logging and block actions permissionsex. It ran fine with many dozens of them running at 20 TPS.

But this is not a big deal I don't think anyone stress tested FE with tons of events and its still new.

I did more testing so easily a dozen quarry's start showing their stress to the sever with FE at 202 on the dot 20 TPS I gave up without FE Installed lol. But you get the point.

**Comment by olee** [comment]
I already said this on IRC but just to have this here on github as well.
The problem has nothing to do with the checks of break / place events for protection, but with the playerlogger.
If you need more TPS, you will have to disable playerlogger for now.

I am working on improving the performance of playerlogger atm, but this can take quite a while.
