### ISSUE TITLE
Worldborder knockback ignores shape

### ISSUE THREAD

**Issue by rhwilr** [ForgeEssentials/ForgeEssentialsMain#1469]
The knockback effect for the worldborder seems to be ignoring the shape of the border.
I have a square border but the knockback teleports me back to where a round border would be.

**Comment by luacs1998** [comment]
Does this still happen with the latest build? We revamped worldborder...

**Comment by rhwilr** [comment]
It seems to be working fine. I really love the new worldborder.
Thank you guys!
