### ISSUE TITLE
issue with /sellcommand beta 7

### ISSUE THREAD

**Issue by blkwind** [ForgeEssentials/ForgeEssentialsMain#1474]
Hello I am having an issue setting up a command block shop using the /sellcommand.

In beta 6 `/sellcommand @p diamond 1 0 addtowallet @p 100` worked perfectly. I know in beta 7 the `/addtowallet` is now `/wallet @p add #` and it works, however the part after the `/sellcommand` is not. Firstly if you use `/sellcommand @p` you get "player cant be found"  secondly if you set it up like this `/sellcommand Blkwind diamond 1 0 /wallet @p add 100` it works but it takes all diamonds from inventory not just one.

 On a side note if you do just `/sellcommand` in the command block and activate is gives this formula to use `[10:49:17] Invalid Syntax. Instead use /sellcommand <player> <['amount'x]item[:'meta']> <command [args]>`
I tried setting it up that way and it still failed.

I am hoping I am just missing something and its not a command bug. If you could please give me an example command based on a Player sells 1 Diamond and recieves 100 in game currency it would really  help clarify.

**Comment by olee** [comment]
I will take a look at it. Did a lot of changes to economy and could not test it all.

**Comment by olee** [comment]
Fixed it.
It works when using `/sellcommand @p diamond 1 0 /wallet @p add 100` now.

**Comment by blkwind** [comment]
Thanks again Olee everything works great. Thanks again for the speedy fix.
