### ISSUE TITLE
Grave doesn't account for items not storable (because of full inventory + armor, or more)

### ISSUE THREAD

**Issue by Malkierian** [ForgeEssentials/ForgeEssentialsMain#1475]
Just died with one free slot in my inventory and when I got back the grave head had only my boots in them from my armor set.

**Comment by olee** [comment]
I tested it again and it worked perfectly for me.
Even with full inventory + armor, I got all my stuff back.

**Comment by Malkierian** [comment]
Yeah, for some reason I got it to work again, too.  Must have been a mod conflict.
