### ISSUE TITLE
Nickname colour support and permission bug

### ISSUE THREAD

**Issue by Paul17041993** [ForgeEssentials/ForgeEssentialsMain#1476]
When setting a nickname with colours, a message will say it has been set correctly with the colours. However, when the player then chats, their name will display the non-parsed codes.
Fix should involve the colour code parsing for nicknames, after the name the current code should be reset to what it was beforehand, so the '<' and '>' (or whatever is in the chat config) are the same regardless of the prefix. Lastly there needs to be a permission entry for nickname colours, if they don't have permission just cut out the codes on setting or deny the name entirely.

Second bug involves there being two nickname commands, first one works with the permissions (nickname.others) correctly, second doesn't, which should be removed.

![fe nickname colours and errors](https://cloud.githubusercontent.com/assets/3912867/7466480/041209da-f327-11e4-907a-7783bdcf482e.png)
![fe nickname colours and errors 2](https://cloud.githubusercontent.com/assets/3912867/7466551/975cfcda-f328-11e4-9639-36708093b544.png)

extra question; where are the nicknames stored? I know they're not in world\FEData.

**Comment by olee** [comment]
Setting colors for players by using `/nickname` is not supported and cannot be supported as it will break coloring of other messages.
Use chat prefix and suffix permissions:
````
/p user test prefix &5
/p user test suffix &f
````

**Comment by Paul17041993** [comment]
prefix is pretty obvious, its what's being used in the picture. But I assure you its not hard at all to allow colours in nicknames, all that's needed is to revert to the previous format at the very end of the name/nickname, and this has been a feature in many chat plugins for years, even since heyO if I remember correctly...

**Comment by luacs1998** [comment]
It's to be done.

**Comment by Paul17041993** [comment]
also note that there's normally an extra permission for colours in the nickname, eg; '.nick.colour', of which if the user doesn't have this permission the colour codes are just cast out or the setting is denied.

**Comment by olee** [comment]
@luacs1998 well if you want to deal with all the special cases that need to be considered adding this (pretty useless) feature as coloring can already be done with user prefix / suffix....

**Comment by Paul17041993** [comment]
@luacs1998 I think you're missing the point that nicknames and prefix's/suffix's are completely different things. If a user wanted two colours in their nickname for example, that's not at all possible to do via the prefix. The prefix is also supposed to be determined by the rank of the player, so for example it will nominally determine the colour of the < and > and the name, possibly some extra characters at the start, but nothing more. If the nickname has colour then only the < and > should have the prefix colour.

**Comment by luacs1998** [comment]
@olee do you know what a nickname is? It's different from prefix/suffix.

**Comment by olee** [comment]
Fixed as part of #1532
