### ISSUE TITLE
Personal warps

### ISSUE THREAD

**Issue by evernife** [ForgeEssentials/ForgeEssentialsMain#1478]
I was trying to make my VIP players have "/pwarp" 
But, i wanted for the normal ones to have 2 "/pwarp" Plus "/home"

The home permission is ok by default, but, how can i set a limited number of /pwarps ?

I tryed to use the permission: "fe.teleport.personalwarp.2"

Is there a way to make this, or am i making something wrong ?

**Comment by helinus** [comment]
You need to set the correct permission property for normal players with ``/p group <GROUP> zone <ZONE> value fe.teleport.personalwarp.max 2``
