### ISSUE TITLE
Server ignoring  S:currency Setting

### ISSUE THREAD

**Issue by ultrasn0w** [ForgeEssentials/ForgeEssentialsMain#1479]
Hey guys,
I just noticed that my custom set
```
    S:currencyPlural=NG
    S:currencySingular=NG
```
In Economy.cfg are replaced with "coin".

Greetings
ultrasn0w

**Comment by ultrasn0w** [comment]
Oh wait, I see they are now set with permission nodes.

**Comment by olee** [comment]
Sorry for not updating the wiki yet so it's not really your fault :wink:
