### ISSUE TITLE
help (and ?) command permission fault

### ISSUE THREAD

**Issue by Paul17041993** [ForgeEssentials/ForgeEssentialsMain#1481]
- _GUESTS_ set to deny all (deny-by-default policy),
- a group named trusted or similar with all the permissions required, including cmd.help, cmd.tps, etc
- the trusted group then links back to the guests (guests includes trusted) so that all new users have the trusted permissions successfully (white-listed server), without having any extra permissions they shouldn't.

However, the help command/s are broken in that they don't get the required permission despite being set to true like all the others.

- all other commands work correctly as they should.
- blocked commands/permissions (ie; ones not listed or set to true in trusted) are also blocked correctly.
- So this just seems to be with /help and /? commands.

**Comment by olee** [comment]
I don't understand your question (please try to fix your English a bit :wink:)
Please give some more explanation to exactly what you did (what commands did you use?) and what does not work.

**Comment by Paul17041993** [comment]
Didn't notice how much the periods in the permissions confuse the sentence, so separated it into points.

Also note the '_'s in GUESTS are there, github is parsing them out...

**Comment by Paul17041993** [comment]
ok, oddly enough the help and ? commands have started working again after adding more permissions to the trusted group, however, the /home command is blocked where it shouldn't be...

**Comment by olee** [comment]
Ok let me warn you: 
DENY ALL by default is a very complicated thing to do and there are many small permissions you need to set correctly to have players be able to play like that.

Other than that - does it work correctly for you now?
Because then I am closing this issue.

**Comment by Paul17041993** [comment]
yes and no, because this wasn't user-error, something odd is with the permission system and it's quite possibly due to reloading permissions. I did not touch the help permission, or any permission closely related to it, for the behaviour to change.

**Comment by olee** [comment]
I intend to fix some of the permission saving these days so these kinda issues should go away, too.
