### ISSUE TITLE
spawn command not able to tp the player to the world spawnpoint

### ISSUE THREAD

**Issue by Paul17041993** [ForgeEssentials/ForgeEssentialsMain#1483]
When firing the /spawn command without arguments, the player is presented with an error 'There is no spawnpoint set for that player'. The expected behaviour is to be teleported to the (active, main) world spawnpoint, unless a player is entered as an argument, of which it should either mention that that player has no specific spawn set, or if that player does, TP to it.

**Comment by olee** [comment]
Yeah this is a known issue.
It can only teleport to spawn, if a spawn has been set manually (overriding the default MC spawn mechanism).
I need to add some code to teleport the player to the vanilla spawn, if none is set.
