### ISSUE TITLE
Personal warps

### ISSUE THREAD

**Issue by evernife** [ForgeEssentials/ForgeEssentialsMain#1484]
I am having a few problems with Pwarps.

Players who set the same name for a "pwarp", one of the two players get his "pwarp" deleted in the next server restart.

Exemple
<John> use the command "/pwarp add home"
&
<Marie> use the same command, "/pwarp add home"

Before the server restart, both of them had his own pwarps normally, but when the server restart one of the two pwarps dessapear.

I was looking at the json>pwarps folder.
I get a bit confused because the "pwarps" are set there with a their own name. 
For exemple: 
If i use the command "/pwarp add myhome" 
This will create in the pwarps folder a file with the name "myhome" with cords. But, if other person try to use the same "pwarp name" this old file is substituted.

(At first i was expecting to look at a folder with the players's nicks and in this folders of players's nicks their pwarps --' (or something similar...But i remmembere to read in some where that there exist a few files that are stored in other place... so, I don't bother myself)

**Comment by olee** [comment]
I had some problems with warps as well and will investigate this soon.

**Comment by evernife** [comment]
ty

**Comment by olee** [comment]
Completely rewrote both commands, `/warp` and `/pwarp`.
You will need to recreate your warps though or copy them over to the new format.

**Comment by evernife** [comment]
Thanks
