### ISSUE TITLE
/tpa

### ISSUE THREAD

**Issue by scootashy** [ForgeEssentials/ForgeEssentialsMain#1486]
I have added the fe.teleport.tpa fe.teleport.tpahere fe.teleport.tpa.sendrequest fe.teleport.tpahere.sendrequest  still get you dont permissions to do that. if you feel this is an error tell a server admin. is there differant permission nodes that aint showing in my perms list somewhere?

**Comment by olee** [comment]
What is the exact error message you get when trying to use the command?
Did you do a deny-all (`* = false`) permission on the group you set this for?
Please give more details or I cannot tell what went wrong.

**Comment by olee** [comment]
Try using `/p debug` to figure out which permission is missing.
If there is no more response on this issue, I will close it these days.

**Comment by olee** [comment]
If there was any issue, it has been fixed as part of #1521
