### ISSUE TITLE
[Question] Essentials to FE

### ISSUE THREAD

**Issue by Time6628** [ForgeEssentials/ForgeEssentialsMain#1488]
Alright, so if I switch from Essentials(the bukkit plugin) to FE, will I still be able to use the playerdata, worldgaurd(WG-6-Beta3) data, and other plugin data? Also, would this conflict with PEX? 
Thanks-
Time

**Comment by liach** [comment]
Hmm... Essentials and ForgeEssentials are not related at all. Forge mods never use plugin data. Might be some mods that could read it. Basic player and game data will be stored. By the way, what's PEX?

**Comment by olee** [comment]
He was talking about [Permissions EX](http://dev.bukkit.org/bukkit-plugins/permissionsex/).

@Time6628 ForgeEssentials and the Bukkit mod Essentials are two completely different mods, though they have basically the same purpose (though ForgeEssentials has a lot for features).
Also features like the ones from PEX are also already part of FE.
Basically it's a whole server toolkit that provides any feature a server needs apart from game content.
