### ISSUE TITLE
[Bug] Can't use 'area select <anything>'

### ISSUE THREAD

**Issue by Zoryn4163** [ForgeEssentials/ForgeEssentialsMain#1498]
Title. Error from console: http://pastebin.com/WPCr9JmB
Using: forgeessentials-1.7.10-1.4.0-beta6-server.jar

**Comment by olee** [comment]
Was already fixed in latest versions of FE.
Also that command is a bit useless anyway as long as #1458 is not fixed.

**Comment by Zoryn4163** [comment]
Just so you know I still receive the same error as I posted in #1498 after updating to the latest Jenkins build. I saw olee marked it as 'usererror' but I don't believe I'm doing anything wrong... Tried both with and without the FE client. http://pastebin.com/EUMusZaK Latest test just now but fairly certain it is identical. (Copied from #1525)

**Comment by aschmois** [comment]
@Zoryn4163 I don't want to flood the other issue, you posted beta6 and we have been in beta7 for a long time now, that is why I stated that you posted an issue for an older version. Issues can be reopened by a collaborator if deemed to be an actual issue.

**Comment by Zoryn4163** [comment]
@aschmois
![](http://i.imgur.com/xpJlcrm.png)
15 hours is a long time...?

**Comment by aschmois** [comment]
No, your main comment is for beta6. That's what I'm referring to.

**Comment by Zoryn4163** [comment]
Which was 7 days ago... Beta 6 was the only available, Beta 7 was released a mere 15 hours ago according to that image...

**Comment by luacs1998** [comment]
@Zoryn4163 he's getting builds from the [beta test server](http://ci.forgeessentials.com/job/ForgeEssentials/). I recommend you get that "15 hours ago" release and try with it.

**Comment by Zoryn4163** [comment]
@luacs1998 That is the one that the more recent post after olee marked it as solved was. The same problem still occurs. (http://pastebin.com/EUMusZaK)

**Comment by luacs1998** [comment]
Linking me the same cutoff log will not help you. I want your *FULL FML LOG*

**Comment by Zoryn4163** [comment]
Alright apologies. https://drive.google.com/file/d/0B-_iReN21PiIUlpLQUdhN3ZEZjg/view?usp=sharing (Too big for pastebin)

**Comment by luacs1998** [comment]
Alright, I see where's going wrong.

@olee for reference this is a different bug.

**Comment by olee** [comment]
Thanks @luacs1998 and sorry @Zoryn4163 - nearly the same error happened somewhere else and I fixed it which is why I had mistaken this one for the other.

**Comment by Zoryn4163** [comment]
@luacs1998 Beta 8 build 621 fixed it. Thank you very much.
