### ISSUE TITLE
[Request] /tp and /tpa able to use shortened names

### ISSUE THREAD

**Issue by LassyKongo** [ForgeEssentials/ForgeEssentialsMain#1503]
As far as im aware this isn't a thing, can't see it documented anywhere.

For example
/tpa SkilledSniper1 could become /tpa sniper1 or /tpa skilled, or even just /tpa skilledsniper1. 

Having to type full names with caps is a bit of a pain.

Thanks

**Comment by helinus** [comment]
I'm fairly certain you can just press tab after typing ``/tpa Ski`` to autocomplete the rest of the playername, even less if there's just a few players online.

**Comment by LassyKongo** [comment]
Well this somewhat solves the problem for now, thanks.
