### ISSUE TITLE
Group suffix chat color coding

### ISSUE THREAD

**Issue by skittishtrigger** [ForgeEssentials/ForgeEssentialsMain#1504]
When using `/p group suffix arg[arg]%arg` the second line of chat clears the color code set. am assuming it is the %message in chat config that does that?

**Comment by olee** [comment]
This is a general Minecraft issue iirc that resets color codes on line break, right @luacs1998 ?
I have an idea for a solution which I will apply when I get around fixing chat module, which I plan to do this week.

**Comment by skittishtrigger** [comment]
Even if it was that bug, thanks for the fast response and letting us know there might be a workaround.

**Comment by olee** [comment]
Well I have an idea how to fix that issue, however it will take some time.
I recommend you to always use white for the message color and only color the prefix / postfix of player names.

**Comment by evernife** [comment]
You can improvise, like me:

Use the code again at the end of every line.
For exemple:

%darkgreen[%yellowFinal%darkblueCraft%darkgreen] Server  =%greenO [FinalCraft] é um servidor totalmente %greengratuito, portanto, dependemos dos vips para nos manter %greenonline, se você quer ajudar o nosso servidor, %pinkcompre vip! :D

**Comment by skittishtrigger** [comment]
this can be closed or moved to a feature request section.
