### ISSUE TITLE
/zone info command broken

### ISSUE THREAD

**Issue by brandaop** [ForgeEssentials/ForgeEssentialsMain#1509]
Whenever I try to input "/zone info" I get "Unknown command argument" regardless of the parameter.

**Comment by olee** [comment]
Actually, that command was never added.
Didn't really find a use for it as (normally) `/area select` would make it quite useless...
However because of #1458 I might better add it these days...

**Comment by brandaop** [comment]
I tried "/area select plotname" and got an "an unknown error ocurred while trying to perform this command".
