### ISSUE TITLE
Portals not working correctly when patch is unable to load + portal improvement

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1510]
If the Mixin is unable to load which can happen together with some mods, the portals will cause some weird bugs. In this case it's better they get replaced with another block.

Also the `/portal` command needs to be improved.

**Comment by luacs1998** [comment]
@olee Mixin has a hook for removing mixins at runtime, I can see if I can look into it.

In retrospect it was a bad idea - breaking so much for an aesthetic change. I only let you have it because you whined so much...

**Comment by olee** [comment]
Actually it was the other way round - I thought it was ok with glass panes for example and players wanted to have it differently and so on...
Anyway, need to check to code for this sometime and add a check if the Mixin was unable to load.

**Comment by liach** [comment]
@olee It seems that the portal's patch is not on forgeessentials_at.cfg?

**Comment by luacs1998** [comment]
@liach run /feinfo debug and tell me what you see.

**Comment by liach** [comment]
Like #1579 ? I'm just wondering why some mixins are not on the AT list.

**Comment by luacs1998** [comment]
ATs are one thing. Mixins are another. forgessentials.mixins.json
