### ISSUE TITLE
"invalid name. please change your name."

### ISSUE THREAD

**Issue by Starless2001** [ForgeEssentials/ForgeEssentialsMain#1511]
I started a new world and suddenly I can't enter the server with my name (which is Gumball), I just get this error and my client gets disconnected from the server. If i remove ForgeEssentials I can enter my server normally.

**Comment by evernife** [comment]
Are you with AuthModule turned on?
This should kick players who have invalid characters in the name, like "SPACE"...

**Comment by Starless2001** [comment]
I have that module on, but my name wasn't invalid before, why is it now? it's just Gumball. No spaces or anything weird, just Gumball.

**Comment by olee** [comment]
If you get that message it means your name must contain a space somewhere.
Maybe you accidentally set your name to "Gumball " or " Gumball" ?

**Comment by Starless2001** [comment]
The only way to change my name that I know of is going to Mojang's website and I only did that once. My name was not Gumball when I created my Minecraft account a long time ago. I changed it to Gumball a few months ago and never touched it again. Is this the only way to get this error? Because if it is, then I think there's a bug.

**Comment by olee** [comment]
If you think there can be a bug in this simple code...
````java
    @SubscribeEvent(priority = EventPriority.LOWEST)
    public void checkPlayerName(PlayerLoggedInEvent e)
    {
        if (e.player.getDisplayName().contains(" "))
        {
            ((EntityPlayerMP) e.player).playerNetServerHandler.kickPlayerFromServer("Invalid name. Please change your name.");
        }
    }
````

**Comment by Starless2001** [comment]
maybe the caller code isn't passing the correct parameter. I am completely sure I didn't change my name in months. And I only changed it once, the same week Mojang began to allow name changes.

**Comment by olee** [comment]
@luacs1998 please take a look at this - you know a bit more about some MC internals in some places....

**Comment by luacs1998** [comment]
@Starless2001 I need you to update to the latest build of FE from ci.forgeessentials.com and give me the kick message you get.

**Comment by Starless2001** [comment]
Sorry I couldn't answer before! I get just a java.io.IOException on my client, but this shows on the server console as the reason why I'm being disconnected:

Invalid name "Gumball" containing spaces. Please change your name!

**Comment by luacs1998** [comment]
@Starless2001 can you try with the latest build, I've changed the way we detect spaces in usernames so it shouldn't happen to you anymore.

**Comment by Starless2001** [comment]
I'm sorry I couldnt test it before. I'm at my grandma's and I downloaded minecraft and all my mods to her pc and also this new build. it works! thanks a lot :D

**Comment by luacs1998** [comment]
Good to hear that.
