### ISSUE TITLE
JSON crash

### ISSUE THREAD

**Issue by CourtArtanis** [ForgeEssentials/ForgeEssentialsMain#1512]
Possibly unrelated, but I keep getting a GSON stackoverflow when a certain player logs out, here's the crash report:https://gist.github.com/CourtArtanis/b723e1f0f8cf436cbe7a

And the file in question is that player's root/world/fedata/json/playerinfo/.. file
```  
 {
    "ident": "(playersIDishere|AA_RoBoT)",
    "home": {
        "dim": 0
```
There seems to be a missing closing brace on the end? Could this cause the GSON crash?

A normal PlayerInfo file doesn't have that issue:
```
{
  "ident": "(playerUIDhere|vikingcourt)",
  "lastTeleportOrigin": {
    "dim": 6,
    "pitch": 6.750049,
    "yaw": -54.749706,
    "xd": 598.5191747433566,
    "yd": 84.59546041618928,
    "zd": 1740.7720299757484
  },
  "namedTimeout": {},
  "selDim": 0,
  "timePlayed": 167064379,
  "inventoryGroups": {},
  "activeInventoryGroup": "default",
  "firstJoin": 1431904090926
}
```
Apologies for the crudity, I'm trying to find a crash.
EDIT: Just found a 2nd player with the same incomplete JSON.

**Comment by olee** [comment]
You probably have an old version of FE where this bug was not fixed (it tried to persist a world object there)

**Comment by CourtArtanis** [comment]
I have beta7 from jenkins, also reverted to beta6 just now - no change.

**Comment by olee** [comment]
Fixed in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/fd8850deb612127f907a02f98ac38d34f831aa0e

**Comment by olee** [comment]
Sorry - there was a bug which really looked exactly like this in earlier versions.
It should work perfectly now.

**Comment by CourtArtanis** [comment]
Thanks @olee 
Not a problem.
