### ISSUE TITLE
Filler not working as intended - beta7#592

### ISSUE THREAD

**Issue by Nightreaver** [ForgeEssentials/ForgeEssentialsMain#1513]
Yesterday I downloaded latest ForgeEssentials-Server-beta7 Build #592 on forge-1.7.10-10.13.3.1408 

I've setup the Borders and started the Filler.

First - it brought up an Error

Whenever I type in "/filler 0 start" is brings me a message (an unknown error ocurred while trying to perform this command), I checked the log - sadly nothing else is written here
But the filler started to do anything

CONSOLE: thread/ERROR]: Couldn't process command: 'filler 0 start'
CONSOLE: != java.lang.String

Second - Its not population the world correctly
![filler_bug](https://cloud.githubusercontent.com/assets/3270156/7743703/8989230a-ff9d-11e4-83ab-9e27ce110078.JPG)
As you can see, the whole screen is generate, but almost anything without any vegetation or special landmarks or so, just simple "green"
I use the new 1.7.10, ATG, so the landscape itself seem to be generated fine, but nothing else.
So i've teleported in the middle to see how it looks now and then the chunks are (re)generated, with everything necessary, vegetation and so on

Since this "filling" i also get this message in my logs
[Server thread/DEBUG] [FML/]: Gathering id map for writing to world save World
[Server thread/DEBUG] [FML/]: The world 74791b4f (World) may have leaked: seen 645 times.

its more than 2000 times now. not good

**Comment by evernife** [comment]
The "Gathering id map for writing to world save World" i get too, but, i used the "fill" when i created the world, so i didn't get a look on this, but, if you are saying, this is a point that need to be tested :D

**Comment by luacs1998** [comment]
Where's that screenshot from? Ingame minimap?

Last I checked we generate land in a similar way to MCEdit - you have to actually go there for the server to generate the terrain features (what's called "decoration" internally)

**Comment by Nightreaver** [comment]
The Screenshot is from Dynmap, full-world-render right after the regeneration.

But that explains why the world has only terrain generated.

Don't forget the Command bug here.


I do the "pregeneration" of the world to reduce the server-load when players are online and moving around to find other biomes or so. If I only generate the terrain, there is still lost of work for my CPU when the decoration is generated, so this will not really do, what i want - totally remove world-generation-lag.


Maybe a config paramter can do the trick here? So I can switch to full generation (terrain + decoration) for every filler run, to toally remove that i need additional CPU-load for that.
Because with every change in a chunk dynmap is refreshing the map too, causing additional load.

**Comment by olee** [comment]
@Nightreaver read at https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1508
Part of it is the same problem and I already posted there what that problem is about.

**Comment by Nightreaver** [comment]
Beside this, i can't replicate the -z space error... here is a image of my whole world (3300 block "radius") Red marked is manually/player generated terrain. rest is made from filler.

![mc_map](https://cloud.githubusercontent.com/assets/3270156/7768352/9a369c68-007a-11e5-8a4f-80c71b740418.jpg)


I also added the two lines crossing 0,0 in the middle. So everything in the world is generated here .
The -z space error might be something with very large radius,huge amount of blocks and maybe some kind of overflow with normal INT or whatsever is used here, if you know what I mean.

**Comment by spannerman79** [comment]
@Nightreaver is this still current in build [#655](http://ci.forgeessentials.com/job/FE/655/) ?

**Comment by Nightreaver** [comment]
Grabbed #655 

10:10:24 CONSOLE: [INFO] NOTICE: --- WorldBorder for WORLD_0 ---
10:10:24 CONSOLE: [INFO] NOTICE: Enabled: atrue
10:10:24 CONSOLE: [INFO] NOTICE: Center: [0, 0, 0]
10:10:24 CONSOLE: [INFO] NOTICE: Radius: 3300
10:10:24 CONSOLE: [INFO] NOTICE: Shape: round
10:10:24 CONSOLE: [INFO] NOTICE: -------------------------------
10:10:53 CONSOLE: [INFO] An unknown error occurred while attempting to perform this command
10:10:53 CONSOLE: thread/ERROR]: Couldn't process command: 'filler 0 start'
10:10:53 CONSOLE: != java.lang.String
10:10:54 CONSOLE: [INFO] WARNING: Filler finished after 1 ticks.

**Comment by Nightreaver** [comment]
also an small addition to this... blow 1 minute the filler message becomes weired

19:37:28 CONSOLE: [INFO] NOTICE: Filler for 7: Todo: 0-8 minutes 0-49 seconds at 1 chuncks per ticks.
19:37:41 CONSOLE: [INFO] NOTICE: Filler for 7: Todo: 0-9 minutes 0-14 seconds at 1 chuncks per ticks.
19:37:53 CONSOLE: [INFO] NOTICE: Filler for 7: Todo: 0-9 minutes 0-39 seconds at 1 chuncks per ticks.
19:38:06 CONSOLE: [INFO] NOTICE: Filler for 7: Todo: 0-10 minutes 0-4 seconds at 1 chuncks per ticks.
19:38:18 CONSOLE: [INFO] NOTICE: Filler for 7: Todo: 0-10 minutes 0-29 seconds at 1 chuncks per ticks.
19:38:31 CONSOLE: [INFO] NOTICE: Filler for 7: Todo: 0-10 minutes 0-54 seconds at 1 chuncks per ticks.
19:38:43 CONSOLE: [INFO] NOTICE: Filler for 7: Todo: 0-11 minutes 0-19 seconds at 1 chuncks per ticks.
19:38:54 CONSOLE: [INFO] WARNING: Filler finished after 11940 ticks.

**Comment by luacs1998** [comment]
Use latest build - includes reworked filler.

**Comment by Nightreaver** [comment]
using  build#743

"filler" was renamed to "pregen" ?

/pregen start 0 - not enough arguments
/pregen start 5 0  - no worldborder defined
/pregen start auto 0 - invalid number "auto"

/wb - you dont have permission to do that (from console!)


so its still not working?!

**Comment by spannerman79** [comment]
If you wish to use /wb edit Commands.cfg
Look for;
`worldborder` and add `wb`

**Comment by Nightreaver** [comment]
it's already inside

    worldborder {
        S:aliases <
            wb
         >
    }


but as mentioned above

"you dont have permission to do that"

**Comment by spannerman79** [comment]
Then you have a permission issue as I just added in the `wb` alias myself, stopped and started my server and was able to issue a `/wb` and have the following response

    /wb enable|disable
    /wb center here: Set worldborder center
    /wb size <xz> [z]: Set worldborder size

**Comment by Nightreaver** [comment]
But this is the server console, everything should be permitted by console...
the wb command itself is working, yes

maybe i have to reset permissions... anyway...

**Comment by olee** [comment]
The `/wb` command only works correctly when run from a client.
The reason is that I did not have much time and concentrated on getting the command finished, which is easier when using a player for specifying location and dimension.
Just use a client connected to the server to setup WorldBorder and it will work just fine.

**Comment by Nightreaver** [comment]
anyhow, why is the  pregen command not working? please see above or

"filler" was renamed to "pregen" ?

/pregen start 0 - not enough arguments
/pregen start 5 0 - no worldborder defined
/pregen start auto 0 - invalid number "auto"

except for the second, why i cant use the others?

**Comment by spannerman79** [comment]
>/pregen start 0 - not enough arguments
/pregen start auto 0 - invalid number "auto"


Just do a `/pregen start`.  I don't see any noticable impact TPS wise, either via `/forge tps` or in my case `/cofh tps` in performance degradation.  Yes I know ForgeEssentials has its own `/tps` and it can be defined within the configs but sometimes using a different mod to display the tps can be helpful

**Comment by Nightreaver** [comment]
The problem is not performance impact, but the fact that im actually in the console, not in the game/on the server, so /pregen start will generate what dimension? 0 ? -1? 

I just need to pregen any dimension from console without joining the server

**Comment by spannerman79** [comment]
`/pregen start` in console won't do anything.
As @olee stated [here](https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1513#issuecomment-112716403)
>The reason is that I did not have much time and concentrated on getting the command finished, which is easier when using a player for specifying location and dimension

**Comment by Nightreaver** [comment]
That was about worldborder... 
"Just use a client connected to the server to setup WorldBorder and it will work just fine."


Anyhow, may be the same for filler/pregen, so just reopen to make sure no one will forget about this.

**Comment by olee** [comment]
Setting up worldborder needs a player, but I'm not sure about the `/pregen` command...
Let me check it and correct it if necessary.

**Comment by Nightreaver** [comment]
back again ;)

can you please explain latest pregen command?
/pregen start [full-pregen] [dim]

"full-pregen" means including tree and such? what do I need to type there?

/pregen start yes ? 
/pregen start 1 ?

who do I activate the "full-pregen" ?


thanks
