### ISSUE TITLE
Chance to setup a "Set"-file for Permissions?

### ISSUE THREAD

**Issue by NitroxydeX** [ForgeEssentials/ForgeEssentialsMain#1515]
Hey folks,

is there a way to setup something like a "set" of Permission-Strings? 

e.g.: I want that a group have no break, place, interact or use on a zone but serveral sub-permissions: e.g. use a chair, or use a doorbell - something like this.

Is there a way that I can say /p group _ALL_ zone XYZ allow "the-Set". Just to prevent retyping it all the time for different areas and it would be nice if it depends on that Set-File, so that when I change something in the Set-File its for all zones that use this file for players or groups.

If there is at this time no way to do this: Maybe something for the future?

**Comment by olee** [comment]
You can use group inclusion for this:

````
/p group perm_set create
/p group perm_set allow .....
/p group myGroup include add perm_set
````

This will make `myGroup` use the permissions of `perm_set` group as well.

**Comment by NitroxydeX** [comment]
@olee I think you got me wrong. This is not what I want. I want to have a real file for this, not a group, that I say "okay, you do the same as x"
I want this for zones that I can say /p group XYZ zone ZXY include "my-set"

**Comment by olee** [comment]
Creating that group will give you that kind of file to edit.

**Comment by NitroxydeX** [comment]
Okay, so this works: /p group xyz zone zxy include "myset"?

**Comment by olee** [comment]
IIRC, yes.
If not I will have to fix it.
