### ISSUE TITLE
crash with startup

### ISSUE THREAD

**Issue by Goten87** [ForgeEssentials/ForgeEssentialsMain#1516]
hello i get a crash when i start FE up
Build #593
http://pastebin.com/6yPyx2hg

when i disable FE in my server it works again

**Comment by olee** [comment]
Fastcraft issue again.
PEOPLE PLEASE! Before posting any issue here - first try running the whole thing **WITHOUT FASTCRAFT**.

Add `-Dfastcraft.asm.permissive=true` to launch args or something like that.
@luacs1998 ^ should be added to a readme + we should throw some kind of RuntimeException or a **HUGE** warning if someone uses fastcraft on his server so they know to add this launch arg.

**Comment by Goten87** [comment]
@olee i alrdy have that in my startup args thats why i posted it here

**Comment by luacs1998** [comment]
@olee I can reproduce this. Is it just me, or is Fastcraft not respecting the environment variable, or something else? @sfplayer1

**Comment by sfPlayer1** [comment]
If you change them programmatically it may be after FC queried them. Version 1.22 should fix it regardless, test builds are at the end of the FC thread.

**Comment by olee** [comment]
As it seems @sfPlayer1 has already taken care of it, I am closing this now.
