### ISSUE TITLE
Server crash on backup + player leave

### ISSUE THREAD

**Issue by ThuGie** [ForgeEssentials/ForgeEssentialsMain#1518]
Seems server was doing backup while a player left and server crashed.

http://pastebin.com/R17mq4Xa

Forge: 1408
essentials beta7 latest.
modpack ftb infinity 1.5.1
java 8 x64

**Comment by DPxKnightxZero** [comment]
Why do you think forge essentials was the culprit? If you notice there are a ton of asm issues. Also fast craft doesn't play nice with forge essentials.

**Comment by olee** [comment]
Might be that a player left the game just when it tried to save entities.
There is not much we can do as this is more a problem of minecraft itself.

**Comment by luacs1998** [comment]
Closing as invalid, if this happens again make a new ticket.
