### ISSUE TITLE
Simple Question - How do I unbind an item set by farwand?

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentialsMain#1519]
I have tried all known tutorials. I cannot unbind the AXE as a wand and now I have seeds and Axe and I only wanted seeds! In all honesty I am going to say it should by default use the arrow since a simple fact you don't use an arrow by itself! Anyways I am a lost.

**Comment by skittishtrigger** [comment]
it youu mean the wooden axe as far as selections are concerned its //wand  If its a tool I believe it is /tool none.   holding tool in hand and typing /tool should give you options.  also doing /help command either tells you or gives you a clue as to what to do also.

**Comment by olee** [comment]
@DPxKnightxZero See worldedit help --> http://wiki.sk89q.com/wiki/WorldEdit
E.g. http://www.minecraftforum.net/forums/archive/legacy-support/1840462-unbinding-commands-on-tools-in-worldedit

**Comment by DPxKnightxZero** [comment]
It doesn't work!!

**Comment by olee** [comment]
Still it is not our problem - check World Edit help.
The wooden axe and stick bindings are controlled by WE alone.

**Comment by DPxKnightxZero** [comment]
Guess what they told me its on your end.

wizjany 23 May 2015, 12:32
go ask the FE people, /none works fine in base WE
Related Changes
Resolved Date
None→55 minutes ago (12:32)
State
New→Invalid

**Comment by DPxKnightxZero** [comment]
Olee I don't mean to accuse you guyes but this was not an issue till after beta 584 I know you don't want to hear this and I know you don't like to hear it but I need you to fix this its important. Please I can't understand why this is happening.

**Comment by aschmois** [comment]
@DPxKnightxZero Provide the issue reference rather than just text, it gives the developer team a reference to be able to talk to the WE team. It's hard to find compatibility issues, if it's really important you should be very specific about your errors. WE build number, FE build number, test cases such as WE installation without FE, etc. The more information your provide us, the better we can help with your issue.

**Comment by luacs1998** [comment]
Update worldedit yourself from http://builds.enginehub.org/job/worldedit?branch=master

If it still happens, it's a valid issue.

**Comment by RealHypnoticOcelot** [comment]
/none should unbind anything from a tool

**Comment by Doge4674356754477** [comment]
skittishtriger should be banned from github for saying those fake commands that dont work
