### ISSUE TITLE
Crash/restart on leave

### ISSUE THREAD

**Issue by skittishtrigger** [ForgeEssentials/ForgeEssentialsMain#1522]
Getting a crash on player leaving. 
Might be related to the earlier ticket (Backup was not involved in this case)

ThuGie commented 4 hours ago
Seems server was doing backup while a player left and server crashed.

http://pastebin.com/R17mq4Xa

Forge: 1408
essentials beta7 latest.
modpack ftb infinity 1.5.1
java 8 x64

crash log:  http://paste.ubuntu.com/11275322/
Lastest_Log: http://paste.ubuntu.com/11275390/

Forge: 1401
McV: 1.7.10
FE beta7 latest
modpack: http://technicpack.net/modpack/technainteasy.650138  (server pack not updated yet. Client pack is)
Host: Hosthorde

If there is any other info/help I can provide to figure this out even if I need to take the ticket elsewhere let me know :)

edit: Don't know if this will help but this started popping up in console also.
http://paste.ubuntu.com/11275939/

**Comment by olee** [comment]
Can players reconnect to your server?
You posted a lot of random logs, but didn't tell what actually happened after that player left the server during backup.

**Comment by olee** [comment]
Should be fixed now!
(You left IRC a bit too early :wink: )
