### ISSUE TITLE
Merge servervote into remote module

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1523]
Seeing as servervote is rarely used, and it duplicates remote to a certain extent, why not merge the server vote handler into the remote module?

Adding the ability to call a script in the remote module should replace the server vote module's reward framework.

**Comment by olee** [comment]
What do we need to support?
- Remote command to give players an item / XP / whatever
- ...?

**Comment by luacs1998** [comment]
Will leave to further discussion.

**Comment by olee** [comment]
Merging them is not an option.
Also has been kinda fixed by https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/fe33f38a7eed7460e3f53775f34a5421c9a615b6
