### ISSUE TITLE
Re-implement MCStats/PluginMetrics support

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1524]
It was removed in the 1.7 update as PluginMetrics' support library needed updating and I couldn't locate the dev.

Now that there's a PluginMetrics Forge for 1.7.10, support should be re-implemented in order to resolve this regression.

**Comment by olee** [comment]
Related links:
- https://github.com/Hidendra/Plugin-Metrics/blob/master/mods/forge/metrics/src/main/java/org/mcstats/Metrics.java
- https://github.com/ForgeEssentials/ForgeEssentialsMain/blob/1.3.0.4_f964_mc164/src/main/java/org/mcstats/Metrics.java
- https://github.com/ForgeEssentials/ForgeEssentialsMain/blob/1.3.0.4_f964_mc164/src/main/java/com/forgeessentials/core/compat/CompatMCStats.java

**Comment by luacs1998** [comment]
Done by olee

**Comment by olee** [comment]
Somehow I forgot to close a lot of issues I fixed.
Sorry and thanks for fixing this @luacs1998 :smile:
