### ISSUE TITLE
Network issues if FEclient and FE are installed together

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1525]
Self explanatory.

A fix would be to move the network stuff to the commons package so that both the client and the server are on the same network instance.

**Comment by Zoryn4163** [comment]
Just so you know I still receive the same error as I posted in #1498 after updating to the latest Jenkins build. I saw you marked it as 'usererror' but I don't believe I'm doing anything wrong... Tried both with and without the FE client. http://pastebin.com/EUMusZaK Latest test just now but fairly certain it is identical.

**Comment by DPxKnightxZero** [comment]
Yeah olee did the same to me with this issue. https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1519#issuecomment-104944791 I am starting to lose respect for FE. I don't bother reporting things without an issue.

**Comment by aschmois** [comment]
@Zoryn4163 You reported an error with an outdated version, just comment on the issue saying that the error still applies on build #XXX and things should get back on track.

@DPxKnightxZero Wrong place to post this. You posted this comment at the same time you responded. Developers can't answer your issues so quickly.

**Comment by Zoryn4163** [comment]
@aschmois It actually wasn't outdated... I was using the latest build for the time from the jenkins. Also how does the issue become re-opened?

**Comment by luacs1998** [comment]
@Zoryn4163 don't censor your logs. If it crashes, give us the crash report. If it doesn't, give us the FML log.

**Comment by luacs1998** [comment]
Continue in #1530
