### ISSUE TITLE
Teleport System

### ISSUE THREAD

**Issue by spitfire1081** [ForgeEssentials/ForgeEssentialsMain#1526]
I am having a huge issue with the teleportation.
I am new to FE, and don't have enough skills to idenfy by myself the configurations tricks.

What happens: teleport commands such as /tpa /back /home are currently active for ALL THE PLAYERS.

What i want: i want that ONLY operators will be able to teleport with commands, without items (we have a module called telepad that does the teleportation and i want that players can be able to teleport ONLY by that way).

As i manage to understand, this is a somple PERMISSION configuration, but i couldn't figure out the teleport config file or how to set this in the permission config file. There is no TRUE or FALSE items to be set in PermissionsList,txt or Permissions.Cfg nor a teleport.cfg file.

Somebody could help me please?

**Comment by olee** [comment]
Well, first you should check the [Wiki pages](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki) where you can find a [Permission Tutorial](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Permissions-tutorial) that will give you a short introduction.

**Comment by spitfire1081** [comment]
@olee i did read the tutorial.
But nowhere in the tutorial it was said that FE comes with OP commands for regular players activated by default.

As far as i read, the teleport module is NOT anywhere where i can DISABLE what it does.
And your answer was very unpolite.

And it is NOT an userror.

I want to revoke the teleport permissons. HOW can I do that?

**Comment by skittishtrigger** [comment]
read the updated permissions list on the wiki. not only that but the groups. This is a group/user permissions configuration error. I suggest making a group with no permissions and add ONLY the ones you want. the permissions are in there for teleport.

**Comment by spitfire1081** [comment]
I want NOBODY but the OPs to have permissions to teleport.
And i have NO IDEA in how to configure permissions.
I read the wiki but was obviously intend to other purposes, not survival mode.

Can somebody PLEASE, help me to DISABLE the permissions to teleport? It is ruinning my game.

**Comment by luacs1998** [comment]
/p group _ALL_deny fe.teleport.*

/p group _OPS_ allow fe.teleport.*

Enter those commands into your server.

**Comment by olee** [comment]
To add one thing:
If you do not configure any groups anyway, it's easier if you just disable teleport for guests:
````
/p group _GUESTS_deny fe.teleport.*
````
Then you don't have to especially allow it for _OPS_ again.
