### ISSUE TITLE
LoaderException crash on load using FE 1.4.0-beta7 Server

### ISSUE THREAD

**Issue by brbrainerd** [ForgeEssentials/ForgeEssentialsMain#1527]
Hi there! I just recently tried to upgrade to beta7 from beta6 on my TPPI2 v0.1.5 server.  Unfortunately the server would continue to crash on load.  Here is a log: http://pastebin.com/ejzezVnD

Though the TPPI2 modpack uses fastcraft, I did use the "-Dfastcraft.asm.permissive" option.  Should I try removing fastcraft completely?

**Comment by luacs1998** [comment]
You seem to be running into the PL classloading issue. Can you try disabling playerlogger?

**Comment by brbrainerd** [comment]
After googling the issue some more, I removed my forgeessentials/lib folder, removed worldEdit and rebooted.  The server is loading just fine now!
