### ISSUE TITLE
Cooldown timer for kit

### ISSUE THREAD

**Issue by skittishtrigger** [ForgeEssentials/ForgeEssentialsMain#1528]
Still doing more testing but when kit is used in command blocks (circumvented using /doas @p kit name)  after setting /kit name set 38000000 .  Users can use the kit multiple times bypassing the cooldown. suggested fix? Maybe add a check that references the kit name/cooldown of that kit so no matter where the command comes from only an op or those with kit.cooldown bypass perm can use multiple times.

**Comment by luacs1998** [comment]
@olee I was under the impression that you fixed this?

**Comment by olee** [comment]
I am sure I fixed this and the cooldown is applied to the same user as the user who receives the kit.
So it *should* be impossible for the cooldown not to work.

This leaves us with two possibilities:
Either @skittishtrigger set the cooldown incorrectly or there are some problems with using it in a command block.

@skittishtrigger did you actually try using the command directly and see if the cooldown applies?
