### ISSUE TITLE
Commands module / general cleanup

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1533]
The state of the code in that module is (and no word fits here better) horrible.
Needs a lot of cleanup and proper structure before we can go out of beta and consider #1141

List of currently know things that need to be improved:
- [x] Add proper command registration manager for ALL commands (see #1419)
  - [x] KILL FEcmdModuleCommands
- [x] Fixing package structure
  - Group commands by feature category for example
- [x] Check what the hell [BlockPoweredOreMod](https://github.com/ForgeEssentials/ForgeEssentialsMain/blob/develop/src/main/java/com/forgeessentials/commands/util/BlockPoweredOreMod.java) is
  -> Was used nowhere at all -> removed
- [X] AFK
- [x] Weather / time control
- [x] Vanish (see #1346)
- [x] **Test virtual chest to work 100% - no bugs allowed on this one!**  
  Has been reported to not work!
- [x] Move LoginMessage / MOTD to chat module and connect it with the rest there
- [x] Remove CommandDataManager and properly split its code to where it belongs
- [x] Check all config loaders and if they are OK, remove the "experimental" message from `/feinfo reload`. This command is VERY useful and should then be encouraged to be used as restarting the server just for a small config change is very bothersome.

There's probably a lot more and we will extend this list when we find something.
If any FE user noticed some other problems like getting "An internal error occurred while attempting to perform this command" on some commands, please report here.

**Comment by luacs1998** [comment]
The "admin" package was a first step to sorting out the commands by feature category. I didn't have time to finish it.

**Comment by olee** [comment]
Though it should not be called `admin` because that is not a feature.
It should be more like "world", "player" and "server" depending on what the commands affect and not who can use them (which is not fixed)

**Comment by luacs1998** [comment]
Those commands are used mainly for administering the server, hence the package name

**Comment by luacs1998** [comment]
Don't touch commands module from now on - I have something planned.

Namely, you'll get the ParserCommandBase you like so much - and I have an extra solution in mind for FEcmdModuleCommands.

**Comment by olee** [comment]
Added proper command manager in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/6b489608fd597e7f6126e411c2aac4073fc8dc25

**Comment by luacs1998** [comment]
Should we completely kill /vanish?

**Comment by olee** [comment]
Removed vanish and did some more cleanup in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/d834308b3df97c33df875fc4fb9c98086727c197

**Comment by AnrDaemon** [comment]
"split its code"…
Not "split it is code".

**Comment by AnrDaemon** [comment]
Sorry for hijacking, but it seems to be relevant question.
Is the 5 or so //calc command, two //center commands, and so on a normal thing or they are scheduled for cleanup?

**Comment by olee** [comment]
There are no such duplicate commands... at least not as part of FE and WE.
Why do you think so?

**Comment by AnrDaemon** [comment]
Because they appeared only after installing of FE/WE, and are obviously a part of either.
I'll try to get the pack to the more current version (It is 1291/FEb5 ATM), will get back to you after that.

**Comment by olee** [comment]
FE beta 5 is way too old!
Should work properly with latest.

**Comment by AnrDaemon** [comment]
Got better with beta-7. Only 42 pages of commands >.>

**Comment by AnrDaemon** [comment]
Beta-8 - 29 pages. o.o
Though,
```
[04:21:41] [Server thread/INFO]: //fepos1 [<x> <y> <z] or [here] Sets selection positions
[04:21:41] [Server thread/INFO]: //fepos2 [<x> <y> <z] or [here] Sets selection positions
```
doesn't make much sense.
If these are two distinctive commands, they need more distinctive labels.

**Comment by luacs1998** [comment]
Completed by olee

**Comment by olee** [comment]
lol I didn't even realize that :smile:
