### ISSUE TITLE
Backup Module resets blacklist in Backups.cfg at server startup

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentialsMain#1537]
if i add any dimensions here like so:
````
autoBackup {
        # Don't make automatic backups of these dims. Can still be done via command.
        I:blacklist <
          DIM1
         >
````
the server will reset and empty this list. i have tried several formats with or without ""

Anybody an idea ?

**Comment by luacs1998** [comment]
You don't need the dim.

So, your config should look like this:

autoBackup {
# Don't make automatic backups of these dims. Can still be done via command.
I:blacklist <
1
>

**Comment by jogi01** [comment]
thx luacs1998 ! i will try it as soon as possible :)

**Comment by luacs1998** [comment]
Does it work?

**Comment by luacs1998** [comment]
Haven't heard anything - assuming fixed, closing.
