### ISSUE TITLE
Improve /help

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentialsMain#1538]
Hello there :)

is there any way to edit a help.txt file like in the plugin version of essentials ? I want to edit my own help pages if they type in /help.

thanks in advance!

-Jogi

**Comment by olee** [comment]
There's actually a lot of stuff I intended to add to `/help` - good that you remind me.
- Showing customizable help page when running `/help`
- Allow to search for commands by their usage text with `/help <text>`
- Otherwise show default `/help <page>` if a number is specified
