### ISSUE TITLE
galacticraft compatability

### ISSUE THREAD

**Issue by jaz000** [ForgeEssentials/ForgeEssentialsMain#1543]
Are we incompatable with galacticraft ?

When I also have galacticraft loaded - and a player touches a nether portal - and only on server (no problem in single player)

I get disconnected from the server with
net.minecraft.util.ReportedException: Colliding entity with block

forgeessentials-1.7.10-1.4.0-beta7-server
tried a couple of the latest galacticraft versions
tried forge 1388 1400 1408

I have multiworld enabled 

server console:
http://pastebin.com/6vPZ6nvv

complete modlist:
http://pastebin.com/rxHCH1hS

**Comment by luacs1998** [comment]
Dupe of #1510

**Comment by olee** [comment]
Update to latest FE version - that bug should have been fixed

**Comment by jaz000** [comment]
confirmed fixed! you guys rock - thank you!
