### ISSUE TITLE
[Bug] Join/leave/death messages not showing in IRC

### ISSUE THREAD

**Issue by Biofusionz** [ForgeEssentials/ForgeEssentialsMain#1547]
As the title says
<addr>    

    IRC {
        # List of priviliged users that can use more commands via the IRC bot
        S:admins <
           
         >

        # If enabled, allows usage of bot commands
        B:allowCommands=true

        # If enabled, allows usage of MC commands through the bot (only if the IRC user is in the admins list)
        B:allowMcCommands=true

        # Bot name
        S:botName=BioBot

        # List of channels to connect to, together with the # character
        S:channels <
            #channelname
         >

        # Enable IRC interoperability?
        B:enable=true

        # Header for messages sent from IRC. Must contain one "%s"
        S:ircHeader=&c[IRC] %s: 

        # Header for IRC events. Must NOT contain any "%s"
        S:ircHeaderGlobal=&c[IRC] 

        # Header for messages sent from MC to IRC. Must contain two "%s"
        S:mcHeader=<%s> %s

        # Delay between messages sent to IRC
        I:messageDelay=0

        # NickServ password
        S:nickPassword=

        # Server port
        I:port=6667

        # If enabled, ingame messages will be sent to IRC as well
        B:sendMessages=true

        # Server address
        S:server=irc.esper.net

        # Server password
        S:serverPassword=

        # Show IRC events ingame (e.g., join, leave, kick, etc.)
        B:showEvents=true

        # Show chat messages from IRC ingame
        B:showMessages=true

        # If set to true, sets connection to twitch mode
        B:twitchMode=false
    }

**Comment by olee** [comment]
Update to latest version and let the game update your config files.
There is a `showGameEvents` option now.
