### ISSUE TITLE
Playerlogger logs 2 events for one block placement

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1550]
When a player places a block, not only the block placement is logged, but also the interaction with the block against which the other block was placed.

The Playerlogger needs to check some stuff to be able to ignore that interact event:
- Is equipped item an ItemBlock?
- Is `event.useItem` granted?

This should be fixed quickly as it makes logger files grow unnecessary large.

**Comment by olee** [comment]
Ok this does not really work.
A possible "fix" would be
````java
    @SubscribeEvent(priority = EventPriority.LOWEST)
    public void playerInteractEvent(PlayerInteractEvent event)
    {
        if (FMLCommonHandler.instance().getEffectiveSide() == Side.CLIENT || (event.useBlock == Result.DENY && event.useItem == Result.DENY))
            return;
        ItemStack itemStack = event.entityPlayer.getCurrentEquippedItem();
        if (event.useItem != Result.DENY && itemStack != null && itemStack.getItem() instanceof ItemBlock)
            return;
        logEvent(new LogEventInteract(event));
    }
````

However that would also log no interact events at all, as long as the player holds a block item in his hands. As this is not acceptable, we will have to live with a lot of logged interact events for now...
Only solution would be adding a new interact event with Mixin to `ItemInWorldManager.activateBlockOrUseItem(...)`.

**Comment by luacs1998** [comment]
And how do you want me to add the event?

**Comment by olee** [comment]
Just don't add it.
This would be too much a hack to do via Mixin I think.
It should be part of forge instead so making a PR might be better.

**Comment by luacs1998** [comment]
Can't we add a check for "don't log this if event.action == Action.LEFT_CLICK_BLOCK"?

**Comment by olee** [comment]
I already tried it.
Read my post (4 above) which explains exactly why this is not possible.

**Comment by luacs1998** [comment]
Looking into the possibility of doing this as part of #1686.
