### ISSUE TITLE
Make names non-case sensitive

### ISSUE THREAD

**Issue by TerabyteTim** [ForgeEssentials/ForgeEssentialsMain#1551]
So I recently switched from a Bukkit server to a Forge server, and I'm loving ForgeEssentials. It basically covered for all the plugins I lost in the transfer.

One small issue I have though, is that all names are case sensitive. In Bukkit, you could type "/tp terabytetim" and it would work. However with ForgeEssentials, you must type "/tp TerabyteTim" or else it says there is no player with that name.

I imagine this would be as easy as casting all names to a lowercase string before comparing them.

Also I'm a bit new to GitHub, how do I label this as a request, and not an issue?

**Comment by olee** [comment]
You can use TAB completion when typing commands.
This will complete the names correctly for you.
Also there should only be few commands that are case sensitive I think, but we will check it.

@luacs1998 Do you know if it is really safe to match user names case-insensitive?
Is it really not possible for two players with same case-insensitive user names to join?

**Comment by luacs1998** [comment]
I'm not so sure, but I don't think Mojang even lets you have the same username as another player, even if the difference is only in case.

**Comment by olee** [comment]
Then it would be ok.
This means we will probably need to check a lot of code.
But most of it should work if we at least patch the methods in UserIdent which are used most times.

**Comment by TerabyteTim** [comment]
Luacs is correct, Mojang is case insensitive with their usernames. TerabyteTim is the same as terabytetim. That's great to hear that you can patch it! It shouldn't be too difficult, just need to cast some things to lower case using Java's string method. Any idea when a patch would be out?

**Comment by olee** [comment]
As I will go to sleep now, probably sometime in 12h.

**Comment by luacs1998** [comment]
23c20381676e16bf30dcfd5c523d8061a4e4f483
