### ISSUE TITLE
Hide Names

### ISSUE THREAD

**Issue by spitfire1081** [ForgeEssentials/ForgeEssentialsMain#1552]
I am using the mod Hide Names.
The command line for this mod is com.tlf.HN.commands.CommandName
How do I give permissions to non opperators to use this command freely?

**Comment by spitfire1081** [comment]
I already tried /p group _GUESTS_ allow com.tlf.HN.commands.CommandName

**Comment by olee** [comment]
1. Use `/p debug` to find out permissions of stuff you do not know
2. All other mods not supporting FE permission system will have permissions like `mc.<commandname>`
3. Take a look in your own PermissionList.txt to find these permissions

**Comment by spitfire1081** [comment]
When you answer my questions, you answer like you think i am an idiot.
Sorry, i don't want to be rude and i appreciate you answer so fast.

But you are answering in a way to try to force me to understand the system, and when i ask, believe, i already tryed that.

I already took a look in permissionlist.txt and i didn't find the command /name in the mc.* commands. and in the other fe permissions.

I have this mod, called HIDE NAMES, i should type /name hide and it HIDES the name tages of the players.

When we try that, if we have no operator privilegies, there's a message: "you don't have permission to use this command".

I already tried
/p group GUESTS allow fe.internal.player.name*
/p group GUESTS allow fe.internal.player.uuid*

didn't solve.

So i need a more experienced person to tell me what is the permission i have to allow to permit the command 
com.tlf.HN.commands.CommandName

to be performed by non opeator players.

Can you help?

**Comment by olee** [comment]
Sorry I have very much to do so I tend to keep my answers really short.
1. If you have taken a look at PermissionList.txt, it should say about `fe.internal` permissions "do not touch" - so you better do so :wink: 
2. As I said, you should try using `/p debug` which will exactly tell you the permission you need to set

To do so type in `/p debug` and after that enter the command you want to test (i.e. `/name`). There will be a few messages in the chat about the checked permissions. The one you need will be one of them (it should probably be `mc.name`).
After you got the permission, run `/p debug` again to disable debug mode.

**Comment by spitfire1081** [comment]
The command that showed in debug is

cmd.name

I tryed /p group _GUESTS_ allow cmd.name*

didn't work, players without OP can't use /name yet.

Please, can you tell me what to do?

**Comment by olee** [comment]
You forgot a "." there...
It should be either `cmd.name` or `cmd.name.*` but not `cmd.name*`
