### ISSUE TITLE
Worldborder Crash - Exception caught firing event

### ISSUE THREAD

**Issue by Nightreaver** [ForgeEssentials/ForgeEssentialsMain#1555]
forge 1.7.10 10.13.3.1408, FE 1.7.10-1.4.0-beta8-server ~#655

I obviously passed the border somehow and this is what i get now
-> The crash comes from traveling with a boat and passing the border!

[FML/]: Exception caught during firing event com.forgeessentials.util.events.PlayerMoveEvent@710d5b2d:
java.lang.NoSuchFieldError: field_70117_cu
	at com.forgeessentials.worldborder.Effects.knockback.execute(knockback.java:37) ~[knockback.class:?]

full "log" here

http://pastebin.com/HLBrx6KX

The set shape is a square, but the server seem to kick me at the range of circle-shaped object (far away from border edges. So maybe a conflict with shape-types

For now, shape type not recognised - i've seen an other ticket with this.

Cheers

**Comment by luacs1998** [comment]
Full FML log?

**Comment by Nightreaver** [comment]
alright, haven't checked server-side, updated log above

Cheers

**Comment by luacs1998** [comment]
Try updating FE, you're at least 40 builds out of date.

**Comment by Nightreaver** [comment]
changed nothing - i'm on build #700 now

**Comment by luacs1998** [comment]
Try with latest build.

**Comment by luacs1998** [comment]
*Should* be fixed by new worldborder - reopen if it isn't.
