### ISSUE TITLE
Null pointer exception from PlayerLogger

### ISSUE THREAD

**Issue by TerabyteTim** [ForgeEssentials/ForgeEssentialsMain#1559]
So I was running my server, and suddenly it started lagging a ton. I looked on the console, and hundreds of this message were getting posted to the console every second:
````
[19:15:52] [Playerlogger/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: org.hibernate.TransactionException: rollback failed
[19:15:52] [Playerlogger/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.rollback(AbstractTransactionImpl.java:217)
[19:15:52] [Playerlogger/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.hibernate.jpa.internal.TransactionImpl.rollback(TransactionImpl.java:108)
[19:15:52] [Playerlogger/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 2 more

**Comment by TerabyteTim** [comment]
Every time I launch my server it keeps spamming that error. Is there any way for me to disable PlayerLogger? What is it?

**Comment by TerabyteTim** [comment]
I'm using build #711  currently. It was working fine all day, but just randomly started to do this

**Comment by olee** [comment]
Hi, sorry for replying this late.
There seems to be some problem with your playerlogger database.
If you did not configure anything, you can first try just deleting `./ForgeEssentials/playerlogger.h2.db`.
If that still does not work, you can temporarily disable playerlogger in `main.cfg > Modules`.

**Comment by olee** [comment]
Try with this new build. It should now at last definitely prevent your server from stalling and will disable playerlogger itself in the worst case.

**Comment by TerabyteTim** [comment]
Yeah I updated to build #712 when I saw you release it last night, that seems to have fixed it for now. I never touched the PlayerLogger database, it just randomly started doing this.

**Comment by TerabyteTim** [comment]
So I'm still having issues. My playerlogger.h2.db is 500mb in size, and whenever certain users join in it spams error messages about chunks for some reason.

**Comment by olee** [comment]
1. Please send me log
2. Did you try deleting playerlogger database as I recommended?

**Comment by TerabyteTim** [comment]
I did, it seems the initial issue with the player database caused my server to crash and corrupted a few chunks, removing those seems to have stopped that server spam. However now when i'm trying to launch my server I get the following error, and I can't launch my server at all.

http://pastebin.com/9ENYMp1X

I have everything about backups disabled, so I'm not sure why it's doing stuff with backups.

**Comment by TerabyteTim** [comment]
Also why is the playerlogger database half a gig? that seems kind of huge, considering the rest of the folder together is just under a gig.

**Comment by olee** [comment]
Of course the dabase gets quite big as it logs all player interactions.
Anyway as this issue was solved, I'm closing this now.
PS: After updating to latest FE, delete Backup.cfg which was created by accident.
