### ISSUE TITLE
Add /dechant command / fix /enchant

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1560]

**Comment by luacs1998** [comment]
Why would you want to de-enchant an item?

**Comment by olee** [comment]
I personally could really need it on my own server as well so why not?
There are some items that already come with enchantments when crafted and sometimes one wants to remove an enchantment for other reasons as well.
The enchant command has some (really) small issues as well so I will do both at the same time.

**Comment by olee** [comment]
Fixed in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/1668052f2910e921db0e442b68c2eacc93e85902
