### ISSUE TITLE
Backup not backup up correct files

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1561]
Somehow on a modded server, backup generated backups not containing the region files they should have. This needs to be fixed ASAP!

**Comment by luacs1998** [comment]
I am unable to recreate this on build 731.

Taking it as the fix worked, closing.

**Comment by olee** [comment]
This was not fixed at all.

**Comment by olee** [comment]
But with https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/7666a3953c8971e502feb934a52f817690bebced
