### ISSUE TITLE
Setting AFK timeout should be easier

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1563]
As powerful as the permprop system is, there should be no need to venture into the permprop system for trivial things like changing the AFK timeout.

To align more closely to community norms, and make life easier for admins, an /afk timeout <group> <timeout> should be added.

**Comment by olee** [comment]
Same thought - I would like to change some of these things to make them easier.
I thought of adding a `/fesetting <name> <value>` command. The names would be special permission aliases which we can configure.

For example we can make `afktimeout` map to `fe.commands.afk.autotime` and many others.
Simple to implement and it can do useful things like listing all available settings.

**Comment by olee** [comment]
Same thought - I would like to change some of these things to make them easier.
I thought of adding a `/fesetting <name> <value>` command. The names would be special permission aliases which we can configure.

For example we can make `afktimeout` map to `fe.commands.afk.autotime` and many others.
Simple to implement and it can do useful things like listing all available settings.

**Comment by olee** [comment]
Same thought - I would like to change some of these things to make them easier.
I thought of adding a `/fesetting <name> <value>` command. The names would be special permission aliases which we can configure.

For example we can make `afktimeout` map to `fe.commands.afk.autotime` and many others.
Simple to implement and it can do useful things like listing all available settings.

**Comment by olee** [comment]
Same thought - I would like to change some of these things to make them easier.
I thought of adding a `/fesetting <name> <value>` command. The names would be special permission aliases which we can configure.

For example we can make `afktimeout` map to `fe.commands.afk.autotime` and many others.
Simple to implement and it can do useful things like listing all available settings.

**Comment by olee** [comment]
Same thought - I would like to change some of these things to make them easier.
I thought of adding a `/fesetting <name> <value>` command. The names would be special permission aliases which we can configure.

For example we can make `afktimeout` map to `fe.commands.afk.autotime` and many others.
Simple to implement and it can do useful things like listing all available settings.
