### ISSUE TITLE
Afterlife deathchest issue

### ISSUE THREAD

**Issue by spitfire1081** [ForgeEssentials/ForgeEssentialsMain#1567]
My issue: The deathchest won't be created.

Server log: 
[13:46:40] [Server thread/INFO] [ForgeEssentials/ForgeEssentials]: Loaded Afterlife
[13:46:40] [Server thread/INFO] [ForgeEssentials/ForgeEssentials]: Registering configuration for FE module Afterlife
[13:46:40] [Server thread/DEBUG] [ForgeEssentials/ForgeEssentials]: Loading configuration files
[13:46:40] [Server thread/DEBUG] [ForgeEssentials/ForgeEssentials]: Loading Afterlife-module configuration
[13:46:40] [Server thread/DEBUG] [ForgeEssentials/ForgeEssentials]: Finished loading configuration files

My configuration in config file:
DeathChest {
        # Enable the deathchest.
        B:Enable=true

        # Gives xp when the skull is destoyed or emplyed
        B:EnableXP=true

        # Put the skull on a spike.
        B:enableFencePost=true

        # Time in seconds a grave is protected. After this time anyone can take all stuff.
        I:protectionTime=300

**Comment by luacs1998** [comment]
It should generate in the world at the nearest possible place to your point of death.

**Comment by olee** [comment]
Deathchest settings were moved over to permissions to allow some players having deathchests and others not for example.
If you would just check the top of afterlife.cfg, you should have seen a **big** information message telling you exactly that.

**Comment by spitfire1081** [comment]
I hope you were not talking about this:

Afterlife {

    ##########################################################################################################
    # DeathChest
    #--------------------------------------------------------------------------------------------------------#
    # Permission needed:
    # fe.afterlife.deathchest.make
    ##########################################################################################################

Because OF COURSE i gave this permissions to everybody in GUESTS group.

I am using Nervemine 2 mod, wich has it´s own XP and an extra inventory.
Have you ever tried this mod? Is there any conflict that could prevent the deathchest to generate upon death?

**Comment by olee** [comment]
No... if you use latest FE it should show up this in the config file:
````
##########################################################################################################
# Afterlife
#--------------------------------------------------------------------------------------------------------#
# Afterlife configuration outdated.
# 
# For afterlife configuration, use the new permission-properties "/p global value fe.afterlife.<perm>".
# Following permissions are available:
#  - fe.afterlife.deathchest
#  - fe.afterlife.deathchest.xp
#  - fe.afterlife.deathchest.safetime
#  - fe.afterlife.deathchest.fence
#  - fe.afterlife.deathchest.bypass
# 
#  - fe.afterlife.debuffs
#  - fe.afterlife.hp
#  - fe.afterlife.food
# 
#  For more information look at the wiki on github.
##########################################################################################################
````
It might be that you just need to delete that file once maybe.

**Comment by spitfire1081** [comment]
Following what you said, i should type in the console:

/p global allow fe.afterlife.deathchest.make

This should enable the deathchest, according to the information you and the wiki provided, right?

Well... i just did that and... no deathchest.

**Comment by spitfire1081** [comment]
Oh, i tried just:

/p global allow fe.afterlife.deathchest

Nothing... no death chest.

**Comment by luacs1998** [comment]
Turn on /p debug and then commit suicide. It should tell you the exact permission being checked to make your grave.
