### ISSUE TITLE
Add /fesetting command

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1573]
Continuation of #1563 

I thought of adding a /fesetting <name> <value> command. The names would be special permission aliases which we can configure.

For example we can make afktimeout map to fe.commands.afk.autotime and many others.
Simple to implement and it can do useful things like listing all available settings.

**Comment by luacs1998** [comment]
Also, for those who like using config files, I think we should have a /fesetting import that allows you to import a file with key-values in the java properties format, that way they wouldn't have to keep entering commands.

**Comment by olee** [comment]
Oh that might even be better than just a command!
A setting file that is always loaded / generated on startup which can provide the default values for the permissions.

**Comment by aschmois** [comment]
Yes! I think that some people don't realize that permissions hold a very large amount of settings. Like me, I'm still stuck in the bukkit days thinking permissions are only for using commands. Thinking out loud, we should also consider maybe putting a disclaimer somewhere

**Comment by luacs1998** [comment]
Closed in 63a01ad4ec4f71b8dabaf58be2b639bbdf07b6ea
