### ISSUE TITLE
[Enhancement] Add generator-settings to Multiworld modul

### ISSUE THREAD

**Issue by BakermanLP** [ForgeEssentials/ForgeEssentialsMain#1576]
Hello there,

Can you please add the option "generator-settings" to the Multiworld modul?

This would be needed for example to generate some Fun Worlds with the FWG mod. That would be absolut great!

Thanks in advance

Michael

**Comment by luacs1998** [comment]
#1163

**Comment by olee** [comment]
@BakermanLP adding these options is planned (#1163), but we currently don't have much time and other issues to take care of so this has a slightly lower priority. As we are only 2 active developers on FE there's just soo much work to do :sweat_smile:
