### ISSUE TITLE
Tickinh Entity in WorldSpawn

### ISSUE THREAD

**Issue by jermangarc** [ForgeEssentials/ForgeEssentialsMain#1580]
I have a CustomNPC entity welcoming new users at world spawn. He's been working fine, but once in a while this crash happens on reboot. I have to load world in single player, then delete him and load it back on server, then it loads up just fine. Not sure what's causing it, permissions? I'll let Noppes know over at his Curse bug report.

http://pastebin.com/NEbYdW3x

Add:
After I tried opening in single player, it also crashed, but I noticed something weird, before it crashed; I was able to see the game load for just a few seconds and I saw the NPC being dupped like crazy. I opened the world-save in MCEdit and sure enough I found a ton of these guys. After I deleted the entities I can start the world.

**Comment by olee** [comment]
Looks like a problem with the is-OP check of permission system.
Did you use (one of the) latest FE versions from jenkins? (or at least latest from curse?)
It probably crashes because of the fake-player but I think I fixed that - will check again...

**Comment by jermangarc** [comment]
I'm using the latest ForgeEssentials beta7 release from curse.

**Comment by olee** [comment]
Try the one from http://ci.forgeessentials.com/

**Comment by jermangarc** [comment]
Helo Olee, I got around to starting up the server in beta8 but I got a "mixins" error before initialization.

**Comment by luacs1998** [comment]
Mixins error? Pastebin it and I'll take a look.

**Comment by jermangarc** [comment]
I installed the latest ForgeEssentials beta8 #769 and it started up just fine. Thanks luacs1998. The Ticking Entity issue hasen't come up anymore so I'm going to close this as tentatively solved. Thanks for all your help guys. I also installed the RemoteClient software and it's pretty cool, now I get to start playing with the permissions system. Thanks again guys, you rock!
