### ISSUE TITLE
Compatibility problem with littleMaidMobX

### ISSUE THREAD

**Issue by whocares0101** [ForgeEssentials/ForgeEssentialsMain#1581]
With "forgeessentials-1.7.10-1.4.0-beta7-server" when a maid gets damaged the server crashes.

Mod
https://github.com/lepakko683/littleMaidMobX

forgeessentials-1.7.10-1.4.0-beta8-server
http://paste.ubuntu.com/11717574/

forgeessentials-1.7.10-1.4.0-beta8-server
http://paste.ubuntu.com/11722655/

Earlier beta versions seem to work
forgeessentials-1.7.10-1.4.0-beta5-server
forgeessentials-1.7.10-1.4.0-beta6-server

**Comment by olee** [comment]
Only when a maid gets damaged or when a player gets damaged by the maid?

**Comment by liach** [comment]
It seems somewhat mods shouldn't create entities out of player.

**Comment by olee** [comment]
Ok for some stuid reason this little maid mob extends EntityPlayer which breaks permissions.
I'd say that's a fault on their side for doing something crazy like that...
I can at least prevent FE from crashing by that, but you won't be able to control damage permissions related to that mob then. Instead it will be treated like a player and the PvP permission will apply.

Edit: Ok after looking at that mod, I REALLY want to make that one work :smile: 
I will sort it out somehow.

**Comment by liach** [comment]
:smiling_imp:

**Comment by olee** [comment]
Ok I managed to fix the hurt-event quickly (added the mod to my dev env), but while playing around with these damn cute maids, I killed a zombie making it's XP drop.
Because the maids are EntityPlayer instances, they pickup XP too, resulting in the next crash in the PlayerPickupXpEvent.... fixing this as well and then uploading new version...

**Comment by olee** [comment]
Aaaand next crash when (please don't blame me >_<) killing a little maid....

**Comment by whocares0101** [comment]
Thanks for fixing this so fast :)

You can tame a maid with cake, you will also need sugar possibly some feathers and a book.
The maid can have multiple jobs
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287042-1-7-10-littlemaidmob-report-any-bugs-to-github

**Comment by olee** [comment]
Yeah I already did that and tested all modes.
For example it also crashed when a maid placed torches.
Also found this crash related to LMMX https://github.com/tterrag1098/ttCore/issues/35
