### ISSUE TITLE
Custom Server Broadcast Message For When Player Joins Server

### ISSUE THREAD

**Issue by RustyJP** [ForgeEssentials/ForgeEssentialsMain#1583]
Would it be possible to add a config option for a custom server broadcast message for when player Joins Server, similar to the config options for MOTD, that allows for color formatting etc? For example: 
"[playername] has joined the land of mining"

**Comment by olee** [comment]
We already have a welcome message for new players.
See Chat.cfg for the options `LoginMessage` and `WelcomeMessage`.

**Comment by RustyJP** [comment]
I can find the "Welcome Message" section of the config, but this only seems to work for new players joining the server, whereas I was suggesting a method that would post the message for all players all the time. Furthermore I can't locate the join message section. Sorry If I'm just being stupid :(

![image](https://cloud.githubusercontent.com/assets/12912890/8204148/51b2ad06-14de-11e5-9ca1-bf3527b2ebe4.png)

**Comment by olee** [comment]
This is the old chat module configuration.
1. Be sure to use latest FE from http://ci.forgeessentials.com/
2. Delete Chat.cfg

After that it will work and you have both a welcome message for new players and a welcome message for every player joining.

**Comment by RustyJP** [comment]
Thanks!!
