### ISSUE TITLE
disable suffocation damage.

### ISSUE THREAD

**Issue by Starless2001** [ForgeEssentials/ForgeEssentialsMain#1584]
I suggest the possibility of disabling suffocation damage. Maybe as a permission, or as a vanilla-like gamerule. Is it possible? people die because of spawning or teleporting inside a block all the time, and I remember you can disable suffocation damage using bukkit. maybe it can't be done with Forge, but I thought it was worth suggesting.

**Comment by jermangarc** [comment]
What happens when they're mining and they have gravel fall on them?

**Comment by olee** [comment]
Please check [PermissionList.txt](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/PermissionList.txt) or the [WIKI -> Protection](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Protection-%28world-guard%29#entity-permissions) before asking if we have some permissions (if you did and could not find it it's ok of course).

````
fe.protection.damageby.inWall                                      # (default: true) 
````

**Comment by Starless2001** [comment]
my bad. I read that file but I didn't pay enough attention because it is a really massive file. I tried a search with "suffocation" and got nothing so I assumed it was not implemented.

**Comment by olee** [comment]
No problem - in a way it's also our fault for not properly updating the wiki yet.
