### ISSUE TITLE
Every version after beta 5 not letting server start.

### ISSUE THREAD

**Issue by tethlah** [ForgeEssentials/ForgeEssentialsMain#1585]
I just tried running beta-8 build 751.  We were having issues with nether portals cropping up and wanted to update to solve the problem.  However, it seems anything other than beta-5 won't load on the server.

Here is the pastebin, any help would be awesome.

http://pastebin.com/TLhxPq9w

**Comment by olee** [comment]
This looks like an issue with other mods using ASM to modify Minecraft.
Could you try starting a small server without any mods except FE and see if it loads?
If so, please post a list of all mods you used.
Also **remove fastcraft** if present.

**Comment by tethlah** [comment]
Ok, so removing fastcraft fixed the problem.  Which is a problem, because fastcraft has done wonders for helping to improve my server performance especially with terrain gen.

Is removing fastcraft going to be the only way I can use forge essentials moving forward?

**Comment by olee** [comment]
Use latest version of fastcraft provided by @sfplayer1. It fixes these bugs.

Also using fastcraft does not necessarily make the server faster - it works quite good on clients but I recommend you just remove it on the server.

**Comment by tethlah** [comment]
I can do that too.  If you don't mind me asking, because I'm unsure.  How does it not help having it on the server?

**Comment by olee** [comment]
From what I know Fastcraft helped performance a lot in old Minecraft, but since about 1.7.10 Minecraft code itself got fixed a lot and by now often Fastcraft causes more problems with compability issues that it fixes with that 1% of performance it increases on a server.

And because that little bit can be ignored, it's easier to just leave it out on the server to ensure there are no problems with FE.

**Comment by tethlah** [comment]
Odd, I mean I can see why you would say remove it to ensure nothing goes wrong with your mod specifically lol.

Any ideas for a good replacement to help with terrain gen?  Or even automatically generate BOP terrain to put on a server?  BTW, we are using the latest version of fastcraft but that didn't fix the conflict.

**Comment by olee** [comment]
As I said - you can still use Fastcraft when updating to the correct - latest - version.

**Comment by tethlah** [comment]
yeah, I did, still isn't working.

**Comment by sfPlayer1** [comment]
Erm MC tends to get worse with every version ;)

The benefit of having FC on the server is quite substantial, it optimizes several common operations and some nasty edge cases.

The version 1.22-ctest10 or later should work, if it doesn't report it to the FC thread with the crashlog.

**Comment by tethlah** [comment]
where do you get it, I've gotten updates from IC2 and the latest is 1.21

**Comment by sfPlayer1** [comment]
Those are preview releases I only release as a post, the direct link is http://files.player.to/tmp/fastcraft-1.22-ctest10.jar

**Comment by aschmois** [comment]
1.8 and its versions definitely improved a lot of the operations. 1.7.10 still needs fast craft, agreed, but it really isn't terrible to not have it. It's not like FE is making Fastcraft incompatible on purpose, it's just a really inconvenient hack.

**Comment by olee** [comment]
And actually it's Mixin that is incompatible with Fastcraft (ie. Sponge has the same problem)

**Comment by tethlah** [comment]
SO it looks like both of your updates work fine.  The new fastcraft works as does the latest FE.  Server is up and running without any issues.
