### ISSUE TITLE
FEClient not working (beta 8 build 751)

### ISSUE THREAD

**Issue by spannerman79** [ForgeEssentials/ForgeEssentialsMain#1588]
While flying, then issue command `/noclip` on client side displays

    You need the FE client addon to use this command.
    Please visit https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/FE-Client-mod for more information.
[FEClient](http://ci.forgeessentials.com/job/FE/751/artifact/build/libs/forgeessentials-1.7.10-1.4.0-beta8-client.jar) present client side

**Comment by olee** [comment]
Yeah we currently have some problems there.
As a workaround, run `/feclient reinit` after connecting to the server to get all FE-client features working again.

**Comment by luacs1998** [comment]
Is it possible to set a delay or something for the handshake packet? Like, 1 second?

**Comment by olee** [comment]
Thought about that - will check it these days.

**Comment by luacs1998** [comment]
Fixed in 5218a5ed7dbf5100c0346f1a64f029552b81d5b4
