### ISSUE TITLE
World border > unknown command

### ISSUE THREAD

**Issue by whocares0101** [ForgeEssentials/ForgeEssentialsMain#1591]
World border command seems not to be registered, tried this on a fresh server with only FE (beta 8 build 752).
There is also no .cfg file generated for the world border in ForgeEssentials/.
Module is enabled in main.cfg (B:WorldBorder=true).

On the server console:
wb
[03:25:25] [Server thread/INFO]: Unknown command. Try /help for a list of commands

log
http://paste.ubuntu.com/11733448/

**Comment by Nightreaver** [comment]
see #1513

**Comment by whocares0101** [comment]
The full command is "worldborder", the alias "wb" was missing and it only works from a client.
Also the wiki and the output of "worldborder" without arguments refer to "wb", maybe this alias should be added to the default configuration file.

**Comment by olee** [comment]
It is - you need to delete Commands.cfg once (happened because of some changes to command registration)
