### ISSUE TITLE
Switching to a rolling release model

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1595]
Since we've been in beta for quite a while now, I think we should consider using a rolling release model after 1.4.0 stable.

Wikipedia defines it as:

> a continually developing software system; this is instead of a standard release development model which uses software versions that must be reinstalled over the previous version.

This change would be administrative at best - the current x.y.z version numbering would be replaced with a a.b numbering system, where:

- a is the most recent milestone release (a la Bukkit's R releases and CyanogenMod's M releases).
- b is of course, the build number.

The concept of "stable" and "beta" builds would be thrown out - every build would be stable, and we'd occasionally post milestone releases on CurseForge.

Thoughts? Comments?

**Comment by olee** [comment]
So after 1.4.0 release we would go to 1.4.760 (or whatever build is current that time) and move on from there. And only if we do some major changes (i.e. mainly completely new features or compatibility breaking changes) we would go to 1.5.XXX?

At least that is what I think would be useful any still comply with the current versioning.

**Comment by luacs1998** [comment]
Probably something like that.

Just that the major version would follow FML's, and the minor version resets every MC version.

Hence, something like:

- 7.1.760
- 7.1.761
- ...
- 7.2.800 (milestone on CF)
- 7.2.801
- ...
- 8.0.840 (initial 1.8 port)
- 8.0.841
- ...
- 8.1.860 (1.8 milestone on CF)

**Comment by DPxKnightxZero** [comment]
This sounds nice ... anyway to program direct updating like microsoft update style? It save me months of headache.

**Comment by olee** [comment]
I actually use something like that for my own server. It's pretty easy.
If you use a start script for your server (like you should) then you only need to add a command to download latest FE from jenkins at the top.

**Comment by DPxKnightxZero** [comment]
Error I am not very code savvy ... if you do that could you just include it instead? I promise it will save me and you a ton of headache.

**Comment by olee** [comment]
We cannot / will not do that as part of FE code.
You can use some start script like
````
wget -N http://ci.forgeessentials.com/job/FE/lastSuccessfulBuild/artifact/build/libs/forgeessentials-1.7.10-1.4.0-server.jar -P mods/
java -Xms128m -Xmx4096m -jar forge-1.7.10-10.13.3.1401-1710ls-universal.jar nogui
````

**Comment by DPxKnightxZero** [comment]
Error you mis-understood me I was just asking if you could include a script template with instructions on usage.

**Comment by luacs1998** [comment]
Open another issue @DPxKnightxZero

**Comment by liach** [comment]
But fml's dead...

**Comment by olee** [comment]
I'd suggest just making versions liike that:
`<MC-version>-<FE-minor><FE-build>'
For example versions would then be 1.7.0.769 or 1.8.812 or something like that.
Because we will only support latest anyway and do continuous development, that would make things easier.

**Comment by luacs1998** [comment]
Well, that'll be (a bit) confusing.

I'm thinking milestones as an unrestricted number that could go wild or something. Something like what IC2 was doing pre-Experimental if you get what I mean.

**Comment by olee** [comment]
Examples please...

**Comment by luacs1998** [comment]
Alright, we'll do it starting with the 1.8 releases.

Refer to my previous examples, except that something like `1.92.1654` would theoretically be possible (1.x never changes, 92 is the milestone, 1654 the build number)
