### ISSUE TITLE
/back from end dont work

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentialsMain#1596]
hey guys!

if i want to teleport back from the end i hang in the void only reconnect solv this.

onother issue:
if i do /back after being teleported from a PORTAL i go back into the portal and use it again. better is that the /back koords are 1-2 blocks before the portal.

greetings
-jogi

**Comment by olee** [comment]
Portals: I will need to change it so you cannot do `/back` with portals (since it's not intended for that and there is already a portal.

End: Will need to test and verify that first - until that I have no idea what could be causing that, if it is really an issue caused by FE.

**Comment by jogi01** [comment]
hi olee! do you have new findings about the /back or /spawn problems from the end into overworld ?
greetings
-jogi

**Comment by luacs1998** [comment]
He asked me to look into it but unfortunately this thing called Cities:Skylines exists.

#lazydevs

**Comment by olee** [comment]
@jogi01 I had this issue happen to me as well and I might know the reason for that.
There is some serious problem with how multiworld is loading worlds.
Currently, if a multiworld unloads for example, it can never be loaded again.
Continued in #1613 - will probably rewrite some stuff that will fix this, but only after 1.4.0 release
