### ISSUE TITLE
Allow setting Gamerules in multiworlds

### ISSUE THREAD

**Issue by luacs1998** [ForgeEssentials/ForgeEssentialsMain#1602]
Could it be something to do with the multiworlds' separate level.dat files?

And should all gamerules be tied to the master list of gamerules or should the be allowed to differ?

**Comment by olee** [comment]
After testing this I can confirm, that normal gamerules only apply to the normal MC worlds - not multiworlds. This is good for us as it means we can add a `/mw gamerule` command to allow individual control of these in every world.

Adding this as feature request.
