### ISSUE TITLE
need fixed spawn point

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentialsMain#1605]
hey guys!

dont know if this is an issue for you but i have set a spawn point and new players gets teleported randomly around my point. i use latest dev builds on native forge server. any ideas ? i have tried my best since 3 hours..

edit:
i have figured out that this is a minecraft preference.
is there a way to bypass this with dorge essentials ? i have tried spawnpoint in _ALL_ group as demonstrated in the guide but without result

**Comment by BLSK** [comment]
I actually use Perfect Spawn Mod just so I could fully control it...I would be interested in an answer to this by far XD.  Maybe just overlooking something after all, mainly cause 'Perfect Spawn' doesn't work in my spawn world, but I know of no other way around it at the moment.

**Comment by olee** [comment]
`/p global spawn here` at some location should correctly make players spawn at this location wherever they die (or by their bed if bed-spawning is enabled).

If it does not work for you, this is probably a bug related to some other mod and needs to be investigated.

**Comment by jogi01** [comment]
hi olee,

i am sorry i forgot to write that i am working on a server spawn so the situation is when a new player joins on the server. We have build now a 20x20 spawn under the sky as needed by minecraft so i would say this issue is not so important :)

-jogi

**Comment by AnrDaemon** [comment]
`config/forge.cfg:general/B:spawnHasFuzz=false`
In short, RTFM!

**Comment by luacs1998** [comment]
As he said.

**Comment by AnrDaemon** [comment]
Alternatively, if you need exact spawn for  ancient Forge versions, http://minecraft.curseforge.com/mc-mods/221418-perfect-spawn

**Comment by olee** [comment]
You can do exact spawn with ForgeEssentials - actually you can *only* do exact spawn with FE.
If you correctly set it, the players should always spawn there.
I guess you just didn't set it correctly.
