### ISSUE TITLE
Possible Improvements: Boundary Boxes as CUI?

### ISSUE THREAD

**Issue by BLSK** [ForgeEssentials/ForgeEssentialsMain#1606]
I have a modpack I use WE in and while setting up some spawn settings with FE I was like... oo... could FE tap into the ability?  Using LiteLoader Mod: WE CUI

![2015-06-28_10 04 43](https://cloud.githubusercontent.com/assets/8443396/8396688/771e0434-1d7e-11e5-8182-3112d6dd9d78.png)

What would be great is when I type in /zone info (Name) it spawned the boundary box for say 5 to 10 seconds for visual viewing of the area... would give great support for not accidently building outside(sure more great things).  I think I read a post about a MC1.8 implementation of this kind of thing but yeah...  Could have something that 'Taps' into WE CUI when mod present?

**Comment by luacs1998** [comment]
We have our own CUI, otherwise this would be cool to have.

**Comment by olee** [comment]
As @luacs1998 said, we actually have this kind of WE CUI built into the **client mod** of FE.
it **does not** have as many features as the WE CUI, but is by far good enough to manage FE areas.

Also you can do `/area select <name>` to select an area and if you use FE client mod / WE CUI, you will then see this selection:

![2015-06-30_19 01 05](https://cloud.githubusercontent.com/assets/6547794/8428564/6c480b12-1f5a-11e5-9316-6a6186e4d192.png)
