### ISSUE TITLE
All permissions being ignored, treated as allowed

### ISSUE THREAD

**Issue by GameDezyner** [ForgeEssentials/ForgeEssentialsMain#1609]
With a fresh install of ForgeEssentials build number 769, all users on my server are being treated as OPs. I've tried erasing all permissions files. They are definitely not opped. Removing ForgeEssentials fixes the issue.

Any idea what could cause this?

**Comment by olee** [comment]
Are you sure they are treated as OPs and your are not just missunderstanding which commands non-OPs can use by default?
See [PermissionList.txt](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/PermissionList.txt) for a reference.

**Comment by GameDezyner** [comment]
Joining with a new user that has never been to the server before, I can op myself. Yes, I'm am sure.

**Comment by Samical** [comment]
We are having the same issue on my server, anyone joining the server can Op themselves. If you DeOP they are still able to OP themselves again. I have tried everything up to and including removing the world file and replacing it with a single player world file with cheats disabled to see if that would fix the problem. Please advise on this issue.

**Comment by olee** [comment]
I cannot replicate this in my dev environment.
Did you try using `/p debug` to see if it checks any permissions when you use `/op` ?

**Comment by MrKRONIC** [comment]
hey olee, i own the server that samical is talking about in the post above and it seems that even guests can op themselves, and so can members and also use the /give command, could this be because we added the forge essentials to our client side modpack to, im going to do some testing today on my test server with your latest 778 build and i report if this issue has been corrected or not, thanks regards MrKRONIC

Keep up the amazing work sir this mod will replace bukkit server for good.

**Comment by olee** [comment]
Yeah it's just bad that we have too few people helping out with FE.
At the moment it's basically only me and sometimes luacs who work on it.
Compared to stuff like sponge / bukkit where dozens of people work on the same set of features that we do here with just the two of us :weary: 

Well back to topic - I really need that `/p debug` information.
It should tell me if the permissions are just configure incorrectly, or not checked at all.
@luacs1998 please take a look at this as well as it concerns the internal implementation of the permission checker (which you and abrar created at first iirc).

**Comment by MrKRONIC** [comment]
Im just booting it in to a test server now Olee, ill be happy to test everything for you with FE whenever you like, i have a great team of admins which got me to wear i am right now and the knowledge between us all gets the job done, your welcome to come alone and test this on out server with us sir as FE will be a massive part of my servers and community, here our test server ip and the modpack you would require to join, also i provide a teamspeak for easy communication if you would like to chat, my team is more then happy to step in and help with this project in tests and code as one of our members has started to right a mod his self , (that would be samical) hope to see you soon, lets get this fixed :)

**Comment by olee** [comment]
Please contact me on IRC :wink:

**Comment by MrKRONIC** [comment]
THIS ? http://www.mirc.co.uk/

**Comment by olee** [comment]
You can use this one for example:
https://client00.chat.mibbit.com/?url=irc%3A%2F%2Fesper.net%2Fforgeessentials
(but a proper IRC client is always better - you will need it as a MC admin)

**Comment by MrKRONIC** [comment]
just says could not connect sir ?

**Comment by olee** [comment]
Please contact me on IRC for modpack / TS information :wink: 
You can use this one for example:
http://chat.mibbit.com/?channel=%23forgeessentials&server=irc.esper.net
(but a proper IRC client is always better - you will need it as a MC admin)

**Comment by luacs1998** [comment]
Alright, what about the permission checker? (btw, that was abrar - I don't touch permissions)

**Comment by olee** [comment]
Fixed by last patch
