### ISSUE TITLE
Cannot use filler command

### ISSUE THREAD

**Issue by Sunconure11** [ForgeEssentials/ForgeEssentialsMain#1610]
I have fastcraft, incase this is involved. When I try to use the filler command, the mod spews out an error, and starts claiming it is filling, but when I try to stop it, it says no filler is running.

http://pastebin.com/F4KKhMM2

**Comment by olee** [comment]
You are using an outdated version of FE.
Please update to latest version which has a completely rewritten `/pregen` command which works properly.

**Comment by Sunconure11** [comment]
What version of FE would you recommend? I use the curse builds, since all the jenkins ones end up throwing out some kind of weird error.

**Comment by Sunconure11** [comment]
I do have Fastcraft, but, I am using the 1.22 builds.

**Comment by Sunconure11** [comment]
This is the current error with the latest build:

http://pastebin.com/Tvdm6Wa8

**Comment by luacs1998** [comment]
Try disabling scripting module for now.

**Comment by Sunconure11** [comment]
That seems to have stopped it.
