### ISSUE TITLE
Permissons with other mods

### ISSUE THREAD

**Issue by micmou** [ForgeEssentials/ForgeEssentialsMain#1611]
Is there any way to register the permission nodes for other mods IE:
Iguantweaks lvluptool
or Thaumcraft  Research
or cofh social

**Comment by luacs1998** [comment]
That depends if you're a modder or a server admin.

### If you're a server admin

FE has hooks into the minecraft command registration process to catch and register permissions for commands - refer to your PermissionsList.txt.

### If you are a modder

The [developer information](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Developer-documentation) and the javadocs you get with FE will tell you what to use. (pretty much, you call CommandHandlerForge.registerCommand with your ICommand and your permission node)

**Comment by micmou** [comment]
The issue is in the latest 796 the permission list has only fe. commands and only one other command mc.help so is there an issue with it then as it does not appear to be populating the lists.

**Comment by olee** [comment]
@luacs1998 I think this might be related to the `/op` issue.
It is probably the CommandHandler patch that does not get applied correctly I think.

**Comment by luacs1998** [comment]
In that case then I will need the output of `/feinfo debug`.

**Comment by micmou** [comment]
Mkay I will get my test server. And see what happens.

**Comment by micmou** [comment]
http://i.imgur.com/QiAgKYH.png

/feinfo debug
output

**Comment by olee** [comment]
Already fixed some builds ago...
It was https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/7c79a8671e248a6cfdee83c81feb62ff1dd683f4
