### ISSUE TITLE
Multiworld loading bug

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1613]
Currently, if a multiworld unloads for example, it can never be loaded again.
Something in the system needs to be changed...

**Comment by jogi01** [comment]
hey all!
i have tested it with build 777, went through vanilla end portal, from the end i tried to get back with /spawn and sadly returned into void again (http://imagizer.imageshack.us/a/img911/7132/xNzL4H.jpg). /back also dont worked. 
greetings
-Jogi
