### ISSUE TITLE
Conflicting Config Files

### ISSUE THREAD

**Issue by RustyJP** [ForgeEssentials/ForgeEssentialsMain#1614]
Does the config options in the "main" config file over-right the config setting in the modules respective config file. For example if I put in the main config to backup every 30 mins does that overwrite backup time I put in the backup config file?

**Comment by luacs1998** [comment]
I have no idea what olee is doing with the configs nowadays - if I remember correctly, unless you're using the canonical config system, module config in the main.cfg is ignored.

**Comment by RustyJP** [comment]
Checked build 775 and main.cfg no longer has the duplicate config sections included in the specific config files (i.e. backup.cfg), So issue is resolved! Thxs for help
