### ISSUE TITLE
Teleport Cooldown

### ISSUE THREAD

**Issue by RustyJP** [ForgeEssentials/ForgeEssentialsMain#1615]
I can't seem to find a way to reduce or even remove the teleport cooldown when using the /tp command, even when the teleport module is disabled? Is there a config option I'm missing or can this be added

**Comment by luacs1998** [comment]
Can you try with [build 775](http://ci.forgeessentials.com/job/FE/775/) and let me know if it still happens?

**Comment by RustyJP** [comment]
Now working with build 775, and still can't seem to find a config option for teleport cooldown

**Comment by luacs1998** [comment]
Teleport cooldown is a permprop, look in settings cfg

**Comment by RustyJP** [comment]
Soryy bit I'm a nooby, how I do I configure it in settings.cfg?
