### ISSUE TITLE
Protection - Exception at harvestDropsEvent

### ISSUE THREAD

**Issue by NitroxydeX** [ForgeEssentials/ForgeEssentialsMain#1618]
https://dl.dropboxusercontent.com/u/41302965/crash-2015-07-03_19.03.37-server.txt

No Informations on the Crash.

**Comment by NitroxydeX** [comment]
ADD: This happens in the Twilight Forest.

**Comment by olee** [comment]
You are using an old version of FE as far as I can see that.
(Line 725 in isItemBanned does not contain the line of code where it crashed in your log).
The bug should already have been fixed in latest versions.
However I found some other potential bugs which I also fixed.

**Comment by NitroxydeX** [comment]
Version was 769 ^^

**Comment by luacs1998** [comment]
By FE standards, 769 is very old :)
