### ISSUE TITLE
Filler command giving error when trying to run

### ISSUE THREAD

**Issue by StephJ2Fan** [ForgeEssentials/ForgeEssentialsMain#1620]
Every time I try to run /filler on the overworld, the server console spits this back at me:

Couldn't process command: 'filler 0 start'java.util.IllegalFormatConversionException: d != java.lang.String	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302) ~[?:1.8.0_05]	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2793) ~[?:1.8.0_05]	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2747) ~[?:1.8.0_05]	at java.util.Formatter.format(Formatter.java:2520) ~[?:1.8.0_05]	at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_05]	at java.lang.String.format(String.java:2925) ~[?:1.8.0_05] at com.forgeessentials.worldborder.TickTaskFill.<init>(TickTaskFill.java:125) ~[TickTaskFill.class:?]	at com.forgeessentials.worldborder.CommandFiller.execute(CommandFiller.java:113) ~[CommandFiller.class:?]	at com.forgeessentials.worldborder.CommandFiller.processCommandConsole(CommandFiller.java:49) ~[CommandFiller.class:?]	at com.forgeessentials.core.commands.ForgeEssentialsCommandBase.func_71515_b(ForgeEssentialsCommandBase.java:42) ~[ForgeEssentialsCommandBase.class:?]	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:370) [lt.class:?]	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:335) [lt.class:?]	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

Help please!
I'm running on Forge 1.7.10-1481 with about 120 mods, if that's needed to know.
I'm running a hosted server, it has approx 3GB of Ram to it

**Comment by JzJad** [comment]
I remember Lucas" mentioning on a reddit thread that filler was kinda broken and they where waiting for 1.8 to fix it.....

**Comment by luacs1998** [comment]
@olee fixed it apparently

**Comment by luacs1998** [comment]
Update FE, fixed in [test builds](http://ci.forgeessentials.com/job/FE/)
