### ISSUE TITLE
Speed requring client

### ISSUE THREAD

**Issue by clienthax** [ForgeEssentials/ForgeEssentialsMain#1621]
Why does /speed require the client mod, you can do it with the following
```
		NBTTagCompound tagCompound = new NBTTagCompound();
		playerMP.capabilities.writeCapabilitiesToNBT(tagCompound);
		tagCompound.getCompoundTag("abilities").setTag("flySpeed", new NBTTagFloat(flySpeed));
		tagCompound.getCompoundTag("abilities").setTag("walkSpeed", new NBTTagFloat(walkSpeed));
		playerMP.capabilities.readCapabilitiesFromNBT(tagCompound);
		playerMP.sendPlayerAbilities();
```

**Comment by luacs1998** [comment]
Its not a particularly big issue, will have to see.

Though you're welcome to PR if you want.

**Comment by olee** [comment]
Don't know myself why @luacs1998 implemented it that weird with the client mod :confused: 
Should be fixed (oh and using NBT is not even necessary).

**Comment by luacs1998** [comment]
Using NBT is necessary - the functions to set speed are not available on the server (which was why the client mod was required at first).
