### ISSUE TITLE
Enabling inventory for guest

### ISSUE THREAD

**Issue by Goju-Sulfam** [ForgeEssentials/ForgeEssentialsMain#1624]
(English is not my native language, sorry for the inconveniences)

I am currently configuring Forge Essential for my server, and I want a "_guest_" default group with minimum rights, so I follow the instructions from the wiki. It's working, but guest's inventory are destroying every things it's come in it.  

I think guest need a permission node to have an inventory (if I remove "*=false" from config it's OK) but I can't find it. I try "fe.protection.inventorygroup.*" and "fe.protection.inventory.*" but the guest inventory still destroying everything.

**Comment by olee** [comment]
Hm I forgot to add it [here](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Protection-%28world-guard%29#item-permissions).
Both "inventory" and "exist" (sorry for bad naming - didn't think of anything better yet) need to be allowed for guests.
