### ISSUE TITLE
Finished Pregen, freezes server.

### ISSUE THREAD

**Issue by JzJad** [ForgeEssentials/ForgeEssentialsMain#1625]
In the latest build #785 once pregen finishes, and you run the command again in the finished world "/pregen start" instead of getting back "pregen finished" or what ever, it times out and then the server just comes to a stop. No errors or anything. Not sure if im the only one or not, just thought id bring it to attention for some one else to possiably try and re-create.

**Comment by liach** [comment]
Full log?

**Comment by JzJad** [comment]
Thats the biggest problem it halts the server completly doesnt save to logs or anything, I went threw my latest log manually then i open all of them from today, and used Notepad ++ to search for when i ran /Pregen, logs are up to the point before i run the command then just stop....

**Comment by luacs1998** [comment]
What I can say is, maybe you're running pregen so fast that your server can't catch up?

I would advise you to configure the pregen throttles, and monitor your server's CPU and disk usage while the pregen is running.

**Comment by JzJad** [comment]
Pregen finished, and i had it at the default speed, and it spiked to around 80% and stayed their. For now im using payed hosting but ill be switching it over to my Dual-quad core xeon machine.
Also the first time after it finished it had given me the Pregen completed/done message back in chat. Ill run another server local and try it again.

**Comment by JzJad** [comment]
Closing it untill then.

**Comment by olee** [comment]
Pregen skips already generated chunks directly.
This means in a fully generated world it will go through ALL chunks without a break.
This is probably freezing up your server.
If you would just wait a while, it would probably continue and give you the "finished" message.
