### ISSUE TITLE
User data dissapearing (where do i find these?)

### ISSUE THREAD

**Issue by Ariazone** [ForgeEssentials/ForgeEssentialsMain#1627]
Hi, i'm running a FTB direwolf 20 1.7 server and one of my users is having an issue.

He told me that he lost almost anything except for his waypoints. (So he told me he lost his hats, his morphs, his inventory and 2 waypoints...). So the first thing i tought was that his player file was reset or something like that. Yet my problem now is that i cannot find these files anymore...

I am used to it that there is a readable file in which i can see a few things like the group the player is in. I could find these in some old files from an old server... but i cannot find them in my current server. All i'm finding is 4 files for each user (Baub(back) and Thaum(back)).

(I am also wondering now i'm writing this... am i asking this question at the right place? >.<)

**Comment by olee** [comment]
FE has nothing to do with storing hats or inventory of players.
I cannot tell you how this happened.
Only thing I can imagine is some error during storage of playerdata by Minecraft for example.
Btw: Playerdata is stored in - who would have thought? - the `world/playerdata` folder.

**Comment by JzJad** [comment]
Also player data now goes by player's UUID, you can use something like this http://mcuuid.net/ to get the players uuid.
