### ISSUE TITLE
starter kit

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentialsMain#1629]
hey :)

short question:
i have created a starter kit with /kit starter set
now i want that a new player get this automated on first startup. is this feature already implemented ?

greetings
-jogi

**Comment by olee** [comment]
@luacs1998 did you already forget that **you yourself** implemented this feature?
I just don't know right now how you did it so I cannot answer that question.

**Comment by luacs1998** [comment]
I don't remember doing it, hence marked as request.

**Comment by jogi01** [comment]
thx !
