### ISSUE TITLE
Galacticraft commands

### ISSUE THREAD

**Issue by JzJad** [ForgeEssentials/ForgeEssentialsMain#1630]
Seems theirs no perms for glacticraft commands, thus players can not participate in the "Space Race".

**Comment by olee** [comment]
Check the PermissionList.txt in the ForgeEssentials directory.
There should be something like `mc.xxxx` where xxxx is the galacticraft command.
If there is none, try using the command once and then check the file again (while the server is running).

**Comment by JzJad** [comment]
I have used gcchunk load as op or as a rank allowed * and it works i have check perms file and still nothing.

**Comment by olee** [comment]
Galacticraft permission nodes do not work with FE - these permissions are for bukkit based permissions. Do the following instead:
 - Use `/p debug`
 - Use the command you want to check permissions for
 - It should show you some checked permissions - one of those will contain the permission for the command

**Comment by JzJad** [comment]
Alright will do thanks.
