### ISSUE TITLE
Is there any way to unprotected specific blocks (just 1 at a time) inside of a protected zone? 

### ISSUE THREAD

**Issue by Hypocrisy** [ForgeEssentials/ForgeEssentialsMain#1631]

**Comment by AnrDaemon** [comment]
It would be easier to answer your question, if you present a use case you have in mind.

**Comment by Hypocrisy** [comment]
Alright, well, I have a building that I want to make protected; a whole area actually (ground included) but inside the building (that is protected) I want users to be able to destroy certain blocks for use with HQM. Essentially, I want to protect an area so they can't cheat and move forward by digging through blocks but there might be some blocks that I do want them to destroy for quests.

**Comment by olee** [comment]
Then just make it like that.
Restrict breaking of only those blocks, you don't want players to break.
See [PermissionList_Blocks.txt](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/PermissionList_Blocks.txt) for those permissions.
