### ISSUE TITLE
Server crash on startup with missing class def's for FakePlayer and EntityPlayerMP

### ISSUE THREAD

**Issue by noahc18** [ForgeEssentials/ForgeEssentialsMain#1632]
Hello, I'm running Forge Essentials 1.4.0 (release) with Forge 1490 and for some reason Forge Essentials causes the server to refuse to startup.

The only log that gets created with Forge Essentials is fml-server-latest.log which you can find here: http://pastebin.com/C3fptGur

The latest.log file doesn't get filled with any info before the crash occurs (the file does get created however) so the crash happens very soon after startup.

Any help would be appreciated!

**Comment by luacs1998** [comment]
Don't use fastcraft, or get the 1.22 test builds at the end of player's thread.
