### ISSUE TITLE
All logging should go to logs/

### ISSUE THREAD

**Issue by AnrDaemon** [ForgeEssentials/ForgeEssentialsMain#1637]
There's a separate directory for logging exists in all server setups for years.
Please use it for all volatile/transient data.
Especially the data that can grow to gigabytes in size.

**Comment by olee** [comment]
Which data are you talking about?
There are no special FE logs.

**Comment by AnrDaemon** [comment]
All data that is not configuration data.
playerlogger.
Chat logs.

**Comment by olee** [comment]
You missunderstand what the logs dir is.
It is for server logs just about recent launches which can be deleted any time - not for data logs.
Playerlogger for example **must never** be in logs directory.

**Comment by AnrDaemon** [comment]
Let the server admin decide, what can be deleted and when.
I, for one, always archive logs and store them for at least a week.

**Comment by aschmois** [comment]
I have to agree with olee here, the log directory isn't meant to store anything but actual logs. FE saves information (think database) which is not a log. A chat log is a log but not a server log so it does not belong in the root log folder.

**Comment by AnrDaemon** [comment]
> Edit: log is no longer a word to me.

That's because you're trying to pull its meaning apart.
Log (in such case) is a "systematic record of events transpired in certain instance/viewed from certain point".
There's no "logs which are not logs". They're all logs by the definition.

**Comment by olee** [comment]
But there's a **great** difference in the importance of these files.
The server logs can be deleted basically immediately.
But what about the chat logs or even worse, the playerlogger DB?
These are completely different matters.

**Comment by AnrDaemon** [comment]
You're asking wrong question.
What these logs can be used for?
Reading? That's all?
If I'm the only person playing on this server, I can't care long enough for any logs to stay.
If I'm hosting multiplayer server, I will preserve logs, any logs.
You can say the same about /var/log/auth.log, that it is "of much different importance", yet it is writtin to common logging directory.
Ultimately, this is not your call, but of the server admin, if he/she care for the logs to stay, or how he/she need to setup logrotate. If at all.

**Comment by olee** [comment]
The difference is that playerlogger is a DB which is **necessary** to be able to revert stuff.
However the logs in the logs directory are useless (except checking for errors) after the server restarted.
The only thing we could move into the logs directory would be the chat logs and this would be kinda stupid to move only these files to another place from the rest of FE data.

**Comment by AnrDaemon** [comment]
Necessary? Fine. As long as you keep it rotated to manageable size, it can be wherever it is pleased. (Although rolling a backup is way easier, than trying to play logs back.)
But chat logs I don't understand. "That would be kinda stupid to move logs to logs." That's strange argument to hear from you. What should I do? Move them manually each time? I can't think about possible comment explaining this action, that doesn't look stupid or offensive. Or both.

**Comment by luacs1998** [comment]
Chat logs are already a part of your server.log. If you really don't need it, you should be able to turn it off.
