### ISSUE TITLE
Repost request (to a Chinese forum)

### ISSUE THREAD

**Issue by liach** [ForgeEssentials/ForgeEssentialsMain#1639]
Hi luacs1998 and olee!
As the title says, I am gonna repost ForgeEssentials mod to [a forum] (http://www.mcbbs.net/) which is in Chinese.

What will I do:
Include the link to https://www.forgeessentials.com/ (Is it hosted in Japan?);
Include the link to curse page;
Include the link to this repository;
Update the version there as soon as possible and might repost some bugs find by them...
Always clarify that you are the origin author.(I'll write down your names, and github link)
Prevent modifying FE source;

Questions:
Do I need to provide the link to your paypal (I forgot its link)? Or patreon? (I don't know whether you have it)
Can I put the file on another server in China on account of the poor internet condition? (Free download, ad free)

**Comment by luacs1998** [comment]
As long as you follow the terms of the EPL. The website is hosted in Germany, but we post stable releases on the Curse CDN, and IDK where that is. There should be a decent enough connection from Curse.

For sources, link to github.

**Comment by liach** [comment]
Thanks a lot.

**Comment by liach** [comment]
I've posted like this:
http://www.mcbbs.net/thread-473138-1-1.html
Anything wrong?

**Comment by luacs1998** [comment]
- I'm not Japanese, I'm ethnic Chinese :)
- Also, please remove the note about me and Forge.
- aschmois is not with the FE team, and I'm the lead dev, not olee.

But otherwise everything seems to be OK.

**Comment by olee** [comment]
OT: @luacs1998 well you are team lead, but one might argue about me being lead dev :wink:

**Comment by olee** [comment]
@liach Did I read that correctly on that page that you posted about the 1.8 version?
I'd rather you not add that yet or if so, include a **HUGE** note that it's not officially supported **yet**.

**Comment by liach** [comment]
@olee Added that "huge" notice on the page that this's not officially supported. And I have fixed all the issues pointed out by luacs1998. By the way, can I consider the repost as "has the repost permission granted by the dev team"?

**Comment by olee** [comment]
Hm it's ok - it's not that we particularly care about it.
You asked - we didn't say anything against it = OK.
