### ISSUE TITLE
Request - Auto updating for all future forge essentials releases 

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentialsMain#1640]
I really enjoy the mod and at the request of Lucas I made a separate thread.

**Comment by olee** [comment]
Will never be added as ForgeEssentials feature.
However I will later provide an update script for linux based systems (which I use on my own server, too).

**Comment by olee** [comment]
The following script is an example for how to always update ForgeEssentials before launching your server:
````
rm mods/forgeessentials-*-server-dev.jar
wget -N http://files.forgeessentials.com/forgeessentials-1.7.10-server-dev.jar -P mods/
````
Just add these before your call to `java -jar forge-universal.jar`.

**Comment by aschmois** [comment]
Word to the wise! That script will delete the mod and redownload everytime you launch, I'd be very cautious of the server being reachable before running it.

If whoever stumbles on that script wants to write something a little nicer, download the jar file to a tmp directory, then replace it.

**Comment by olee** [comment]
Oh yeah thanks for noticing!
I actually only used the second line before but I added the above one when I thought about changing version numbers (which is actually needless now that I added the http://files.forgeessentials.com site).
So the correct one would be the following only:
````
wget -N http://files.forgeessentials.com/forgeessentials-1.7.10-server-dev.jar -P mods/
````
Be sure to name your downloaded version of ForgeEssentials like the one above then (`forgeessentials-1.7.10-server-dev.jar`). Also you can leave out the `-dev` to get only "stable" release, but usually recommend to go with the dev builds.

**Comment by olee** [comment]
For reference: http://forgeessentials.com/downloads/
