### ISSUE TITLE
[1.8] doesn't allow WE //set to come through

### ISSUE THREAD

**Issue by kreezxil** [ForgeEssentials/ForgeEssentialsMain#1645]
Depending on ones point of view not allowing all of World-Edit's commands to come through could be either minor or major.

**Comment by olee** [comment]
Please explain "come through"
- does it say something like "permission denied"?
- does the command just do nothing?
- are you sure you made a proper selection beforehand?
give INPUT!

**Comment by kreezxil** [comment]
Your description days that world edit is included, but most of the world edit command ate not present. I solved it on my end by reinstalling the 6.1 version of world edit I had previously. Which works great with your version 12.

-----Original Message-----

**Comment by olee** [comment]
Maybe when you installed it the first time it extracted that wrong WE version.
If you setup a new server with FE now, it properly extracts the correctly working newest build.
Which means there's no issue any more.

**Comment by kreezxil** [comment]
I just watched it do it again. Really weird. I think that it would be easier to not have your mod actually give out world edit and instead just direct the mod installer to get their own copy of it from sk89q. More that I've deleted the snapshot versions and using my own copy of WE out is working great again. Send to happen when I first install it on mod server where it hasn't been before.

-----Original Message-----

**Comment by aschmois** [comment]
I believe this issue should be fixed now, there was a bug extracting libraries from the FE jar. Hopefully there will be less issues.

**Comment by kreezxil** [comment]
The version that ends in 12 still does it. I have to delete the snapshot versions it extracts then restart the server. It'll q fine but the next reboot it'll do it again and I'll have to do what I just started all over again. Hopefully you've decided to not even extract the libraries but instead leave the onus of downloading and installing the right versions of it to to us.

-----Original Message-----

**Comment by olee** [comment]
The extraction fix was not merged into 1.8 yet.
Wait for next release.

**Comment by kreezxil** [comment]
Will do.

Btw, noticed that FE is allowing players to op themselves. What's the ideal solution? The wiki appears designed for 1.7.10.

-----Original Message-----
