### ISSUE TITLE
[scripting] Client side scripting / macros

### ISSUE THREAD

**Issue by olee** [ForgeEssentials/ForgeEssentialsMain#1646]
https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Scripting

It would be nice to support creating own simple macros on client side as well.
Suggested on IRC.

**Comment by luacs1998** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1275039-macro-keybind-mod-0-10-12

**Comment by olee** [comment]
Uhm ... sounds good.
No need to do that on our side.
