### ISSUE TITLE
[help] [1.7.10] Commands for setting worldborder

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentialsMain#1647]
hey guys,

today i want to set a square world border in the main world.
In the latest dev builds it seems that the commands have been changed as you described as outdated :)
can i have the actual commands or is this modul actual under construction ?

Greetings

-jogi

**Comment by aschmois** [comment]
Please be a little more specific here. Which dev build are you currently using? What Minecraft version are you running? 

Someone else should come along in a few hours since I don't have the knowledge for this but I'm just trying to make sure that they can answer the question when they get to it.

**Comment by jogi01** [comment]
sry youre right!!
i am using dev build: forgeessentials-1.7.10-1.4.1.801-server.jar
what i am searching for:
syntax to set border shape to square
syntax to create border

thanks in advance

**Comment by olee** [comment]
How about you try `/wb` (or `/worldborder`) just once?
It shows you the syntax then like almost every FE command:
````
/wb enable|disable
/wb center here: Set worldborder center
/wb size <xz> [z]: Set worldborder size
````

**Comment by jogi01** [comment]
haha that was my first try -.-

no command worked. i will try it again soon and post you the exact input, i thoght this is known or somebody is actual working on it but if nobody knows.. i post details soon

**Comment by jogi01** [comment]
but how to set the shape type eg. square ?

**Comment by olee** [comment]
https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/81c5f4f11e172d9d5e46f4f35aa008694aa85044
Has been added after your request.
`/wb shape box|ellipse`

**Comment by jogi01** [comment]
ok thx! thats nice
