### ISSUE TITLE
Backup world exclusion....again..

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentialsMain#1648]
hey guys :)

somebody has changed the backup module (in actual dev builds) a while ago and now i have the same problem than before.
I want to exclude all other worlds like -1 +1 and so on.
i have tried in backup,cfg but it dont works. Need shot help here :)

Worlds {
        B:-1=false
        B:-28=false
        B:-29=false
        B:-30=false
        B:-42=false
        B:0=true
        B:1=false
        B:10=false
        B:11=false
        B:12=false
    }

**Comment by aschmois** [comment]
Please be a little more specific here. Which dev build are you currently using? What Minecraft version are you running? This helps developers know exactly which code-base they need to better assist you.

**Comment by olee** [comment]
Use the default configuration and set default backup to false.
That should backup only overworld then.
````
Backup {
    B:backup_default=false
    Worlds {
        B:0=true
    }
}
````

**Comment by jogi01** [comment]
hey olee, thanks so much it works very fine :)
sry aschmois I'll try to improve next time!
