### ISSUE TITLE
[1.7.10] Permissions being ignored

### ISSUE THREAD

**Issue by DoxProx** [ForgeEssentials/ForgeEssentialsMain#1650]
I was testing around and found out that even when I wasn't opped I could still do /fly, then I realized that was the case with all commands. Was there a setting I was supposed to change? if not then this is a very big issue.

**Comment by JzJad** [comment]
Yes i found the same thing happened with me as well.

**Comment by olee** [comment]
Is this about 1.7.10 or 1.8 release?
Also does this happen on a fresh server?
You could also try purging permissions by deleting `./world/FEData/permissions`

**Comment by DoxProx** [comment]
This is on the 1.8 Release, I guess I should've included that information. The server is very fresh, I ran it once or twice before that. I will try purging the folder and report the results later.

**Comment by LemonLake** [comment]
On the 1.7.10 release, my players are able to op themselves, even with command.op=false. Not sure if this belongs in this issue - it  seems to be a related problem.

**Comment by olee** [comment]
I've tested it right now and permissions properly apply on 1.8 builds as well as 1.7.10 builds.

**Comment by LemonLake** [comment]
Thank you!

**Comment by olee** [comment]
Ok it seems the "fix" got it working in dev environment, but it does not work on an actual server yet.
I am currently investigating this and a fix will probably be out in the next hour or so.
