### ISSUE TITLE
[playerlogger,remote] View logged commands

### ISSUE THREAD

**Issue by LemonLake** [ForgeEssentials/ForgeEssentialsMain#1652]
(low-priority and request labels)
I suggest that player commands are logged to latest.log, and a config option be available for this. I have a rainmeter showing the log file from an external machine and I would like to be able to see the commands used by the players (the cmd logs also seem to be missing).

**Comment by olee** [comment]
Commands are logged in Playerlogger (even with position of the player when he used the command etc.) but they are not viewable from the game yet.

**Comment by luacs1998** [comment]
I previously logged all commands to a cmds.log under the chat module folder - must have been removed in one of the refactors. Hence the regression tag.

**Comment by olee** [comment]
Sure sounds good.
It would be nice to have a set of remote handers in `com.forgeessentials.playerlogger.remote` to retrieve such data.

**Comment by olee** [comment]
Fixed in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/1d3697b66ed576e7f647cf37bc1202fd58df3325
