### ISSUE TITLE
World spawning is randomised

### ISSUE THREAD

**Issue by LemonLake** [ForgeEssentials/ForgeEssentialsMain#1653]
(question)
My players are having an issue where they fall into the void due to the fact that upon death, they respawn within a random location somewhere around the spawn point. I am not sure if this is ForgeEssentials's doing, if so, is there a config option I'm missing?

**Comment by olee** [comment]
If you don't configure anything in FE, the default spawn of Minecraft is used.
--> Closing.

I still might be able to help you figure out that problem if you supply more information here.
