### ISSUE TITLE
Sorry but missing the Permission folder and permission txt list file

### ISSUE THREAD

**Issue by rodnico2681** [ForgeEssentials/ForgeEssentialsMain#1656]
I deleted the Permission folder again and updated the mod to the latest version, but this time the permission folder did not load and the permission txt as well. I was able to try it out though and it seems they still have access to /gamemode the only difference this time is that it asks them for the mode and their name /gamemode  <mode> <player>

**Comment by olee** [comment]
Continue such conversation in the original issue #1655
