### ISSUE TITLE
Virtual Chest doesn't keep items

### ISSUE THREAD

**Issue by BossLetsPlays** [ForgeEssentials/ForgeEssentialsMain#1658]
Given my players have the virtual chest permissions and are able to use the command `/vchest` the next time they use it, their items are gone

**Comment by olee** [comment]
Sh**
@luacs1998 Know that entry in #1533?
Know why I added it? Because of this!

Needs to be taken care of ASAP.
There's no quicker way to make players angry than with disappearing precious ~~rings~~ items.

**Comment by luacs1998** [comment]
I have absolutely no idea what is going on.

Code-wise, everything is OK, but for some reason the virtual chest items aren't even persisted into the player.dat.

Should we take the saving into our own hands? That is looking very tempting to me...
