### ISSUE TITLE
[req] Hide commands user have no access to from /help

### ISSUE THREAD

**Issue by AnrDaemon** [ForgeEssentials/ForgeEssentialsMain#1660]
It would be useful to hide commands a user have no authorization to use from the list provided by /help command.

Ref #1533 ?

**Comment by olee** [comment]
Actually they should not appear in `/help` making this a bug.

**Comment by olee** [comment]
And they actually do not show up as far as I could see.
However I fixed some other stuff like commands appearing two times etc.
