### ISSUE TITLE
REQUEST: economy/pay settings or info

### ISSUE THREAD

**Issue by gatekeeper258** [ForgeEssentials/ForgeEssentialsMain#1664]
Players get paid at an interval(unknown) and amount(unknown)
No settings found in cfgs.
No info on wiki.

Not sure if it would be better to ask for info or have it added to the wiki. I've created the pricelist for players to sell items to server to make more money. I would like to stop/extremely lower them making money for just playing as I feel it better for them to sell what they have made.

**Comment by olee** [comment]
Sorry but I was not able to understand what you want.

Is it a)
Your players somehow get money without selling items while playing on the server, but you don't want that? If that is the case it might be that the XP > money setting is enabled which will give players money for every bit of XP they earn.

Or is it b)
You want players to be paid at a regular interval? (i.e. a feature request?)

**Comment by gatekeeper258** [comment]
A. where is the XP>Money settings? I would like to decrease it

**Comment by gatekeeper258** [comment]
I apologize, the xp setting is actually a perm. Issue solved.

**Comment by olee** [comment]
Yeah I didn't answer yet because I wanted to add this setting to `Settings.cfg`
