### ISSUE TITLE
Fe client gui

### ISSUE THREAD

**Issue by gatekeeper258** [ForgeEssentials/ForgeEssentialsMain#1666]
Request documentation on operation. How to activate to see in game selections.

**Comment by olee** [comment]
I think you probably mean the client **CUI** not GUI (because we have no client GUI).
Stuff like the [WorldEdit CUI](http://forgeessentials.com/wp-content/uploads/2015/07/WorldEdit_FE_CUI.png) should show up automatically if you add the FE client mod to your client.
There's nothing else to do.

**Comment by gatekeeper258** [comment]
My bad about the gui statement; so the "forgeessentials-1.7.10-1.4.0-beta3-client" is NOT the CUI for FE?

**Comment by olee** [comment]
Ehm... what did I just say?
The client mod **is** for the CUI.
Also beta3 is way to old and it won't properly there.

**Comment by liach** [comment]
What's the whole name of CUI? C... User Interface? Maybe that helps understanding. GUI is Graph User Interface.

**Comment by olee** [comment]
GUI = grapical user interface
CUI = client user interface
(well you could say it's a kind of GUI but GUI normally means stuff like buttons etc.)
