### ISSUE TITLE
portal frame shows glass blocks instead of portal animation

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentialsMain#1667]
hey guys :)

Our portals are filled with vanilla glass blocks instead of portal animation blocks. I have tested to remove portal and renew but still glass blocks appear.

i am using version : forgeessentials-1.7.10-1.4.1.830-server.jar

is this a known bug ?

thanks in advance
-jogi

**Comment by luacs1998** [comment]
Typical nether portals or ones created with /portal?

**Comment by luacs1998** [comment]
Duplicate of #1649
