### ISSUE TITLE
Economy commands

### ISSUE THREAD

**Issue by gatekeeper258** [ForgeEssentials/ForgeEssentialsMain#1675]
I am not able to get the economy commands to function except for /pay, /trade, and /wallet.

**Comment by olee** [comment]
.... do you believe we can tell you what is wrong with just that? :neutral_face: 
Please tell us exactly **what** does not work for you.
Also for usage questions we recommend you use [IRC](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/IRC) instead.

**Comment by gatekeeper258** [comment]
lol I was expecting something along the lines that economy hasnt been fully implemented. ok so here are my specifics. 

/addtowallet <playername> <amount> or /walletadd
/getwallet <player>
/removewallet <playername> <amount> or /walletremove
/requestpayment <playername> <amount>
/setwallet _player_ _amount_

All of the above commands (referenced from the economy wiki page) are acting like there is no command. not listed in help, not able to exec from console and/or not able to be ran as OP in game.

**Comment by olee** [comment]
These commands are outdated and almost all of those have been replaced by `/wallet`.
The wiki is outdated (which is written on the wiki as a warning as well).
We really want to update it but it takes time... sorry

**Comment by olee** [comment]
Updated the wiki for you
https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Economy-module
