### ISSUE TITLE
can't place fluid buckets like water after a while

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentialsMain#1677]
hey guys!

we're using forgeessentials-1.7.10-1.4.1.830-server

after a while its unpossible to place water with full water bucket in the world. I tried to set my player to OP, in permission debug mode all outputed permissions are set to true. As we playing gregtech where you need water in cauldrons we have massive problem now :)

btw: if i restart the server the waterplacement works (for a while)

any ideas ?

thanks so much..
-jogi

edit: no fluids are working at all
edit: eating dont works, too

**Comment by olee** [comment]
Sounds unrelated to FE.
If you enabled `/p debug` and it shows all true, it's probably another's mod fault.

**Comment by jogi01** [comment]
ahh ok... unfornutately there are no ather "server mods" installed :) i hoped that anybody has a similar problem. is it ok to let the thread a few days active to see if another player has same problems ?

**Comment by olee** [comment]
You could start by providing a modpack / list of installed mods for example.
That way it might be possible to reproduce your bug.
Also the most important question: Did you check if the bug happens without FE as well?
You can copy your server directory and remove FE to test it for example.

**Comment by jogi01** [comment]
we are playing InfiTech2 v3.1.5
yes i have planned to start server without FE, i haven't done it yet because there are already playing people on the server :) i have to plan a downtime yet... its so stupid and nerving -.- 
I have posted same issue on modpack forum hoping to get some resonance..

i have noticed everytime when i do /feinfo reload, some player lost their group. Yesterday after server restart one player lost her group only after restart. achievments wont save and resets after restart but i dont know if this is relevant... i will continue observing this anomalies.

**Comment by jogi01** [comment]
ok now finally it happens when FE is disabled...
unfortunately on the modpack crew nobody has an idea.
server is forge native no changes no more mods.
i am so fucked now :-S

i close this issue...

**Comment by olee** [comment]
Report it to the InfiTec2 maintainer and let them investigate it.
