### ISSUE TITLE
add possibility to add member to plot

### ISSUE THREAD

**Issue by killerpommes** [ForgeEssentials/ForgeEssentialsMain#1681]
Hello, i have a Feature Request.
I would really like if the plot owner can add member to the plot. Members should have all rights to the Plot. So People can Team up to build on a plot.

Or did i miss anything and this is already possible?

Greetings

**Comment by olee** [comment]
`/plot mod add <name>` adds players that can do the same stuff as the owner.
`/plot user add <name>` adds players that are restricted by the "user" permissions.

**Comment by killerpommes** [comment]
oh thanks i did not found any informations about these commands.
Maybe add some in the wiki :)

**Comment by olee** [comment]
We .... :disappointed: .... I mean I am working on it...

**Comment by trismegistis** [comment]
Yes this is good info to know everyone on my server wanted to know it :]

**Comment by luacs1998** [comment]
I tried... https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Plots

**Comment by trismegistis** [comment]
^_^
