### ISSUE TITLE
level counter display error after warp/teleport

### ISSUE THREAD

**Issue by jogi01** [ForgeEssentials/ForgeEssentialsMain#1684]
heyho :)

The level shows 0 Levels after warping e.g. to farmworld, if you want to enchant something, it doesnt work. If you got some new levelpoints during killing something the level counter jumps to right count. The value variable seems to be ok it only affect level bar. 

The only nerving is that you cannot use your levels until you get some new points.

greetings-

jogi

**Comment by olee** [comment]
1. What command / method did you use to travel to the other dimension
2. This is likely again not an FE issue but caused by another mod

**Comment by jogi01** [comment]
we have only FE for teleport, the command was /warp or /pwarp. ok than we'll live with that cause i have no idea if gregtech e.g. have something todo with teleport

please close
