### ISSUE TITLE
Issues with /butcher and missing /spawnmob commands

### ISSUE THREAD

**Issue by wmpowell** [ForgeEssentials/ForgeEssentialsMain#1688]
First off thank you for a great mod, but I have run into a few issues... small.
When I use /butcher command no matter what radius I specify it returns 0 mobs killed in (X) radius

When I try the /spawnmob command it tells me Unknown command...

Am running Forge 1.7.10 -10.13.4.1448  I have tried with 1.7.10-10.13.2.1258 as well
forgeessentials-1.7.10-1.4.2.858
I have other mods but I ran a test server with just FE on it and received the same issues.

Thank you for any help or advice

**Comment by olee** [comment]
That is because `/butcher` is a WorldEdit command and is (was?) bugged.
In either case you need to make a selection for it to work.

You can use `/febutcher` instead which will work directly and you can simply specify a radius.
