### ISSUE TITLE
Thaumic tinkerer - EntityPlayerMP issue

### ISSUE THREAD

**Issue by Aracnoss** [ForgeEssentials/ForgeEssentialsMain#1691]
Having the same issue as #1599. Was using the latest build:  Build #858 (Aug 8, 2015 3:27:51 AM)

crashlog:
https://gist.github.com/Aracnoss/54c7693c1901745b5625#file-thaumic-tinkerer-entityplayermp-issue

Forge log:
https://gist.github.com/Aracnoss/44cde404dea8528f6f45

**Comment by luacs1998** [comment]
Put us in touch with the mod author, we'll need to figure something out.

We can be contacted on irc.esper
net, channel #forgeessentials.

**Comment by Aracnoss** [comment]
Still having problems when breaking dynamism tablets with items in their slots. try both the mods together.

**Comment by olee** [comment]
Be sure to use the latest build.
Also if you get a crash _again_, please give the log of the (probably) new crash.

**Comment by Aracnoss** [comment]
I don't think it's a different crash... But I did use the newer forge essentials build:
Build #872 (Aug 15, 2015 3:18:02 PM)

Crash log:
https://gist.github.com/Aracnoss/7f7794b24a4947dc49e6
Full log:
https://gist.github.com/Aracnoss/6225ae1fbcd6abc35cb0

**Comment by liach** [comment]
WorldEdit! Funny.

**Comment by Aracnoss** [comment]
Erm, I hate to comment, because you're probably still working on this, but it's been 3 days since I posted, has anyone tried to fix it, or am I just really unlucky?

**Comment by olee** [comment]
That second crash is different - it's a problem of WorldEdit itself.
Try updating the WorldEdit build directly from sk.
If that does not help, report this as a bug on the WorldEdit issue tracker.
There is nothing for us to fix any more here.
