### ISSUE TITLE
Portalgun and zone permisions

### ISSUE THREAD

**Issue by algul** [ForgeEssentials/ForgeEssentialsMain#1692]
When I define zone to deny placing and breaking blocks, portalguns pickup block mode completely bypass it. Shooting portal at the moon will suck everything as well. Is there any way to prevent that?

**Comment by luacs1998** [comment]
No way around it, unless portalgun learns to respect FE permissions.

We'll need to get in touch with the mod author for that.

**Comment by olee** [comment]
What @luacs1998 means is that the developer of the Portal Gun mod needs to fire the appropriate events when destroying blocks or there is no way to prevent these interactions at all.
--> There is nothing we _can_ do.

**Comment by algul** [comment]
I suspected that would be the case, but it was worth a shoot to ask. Thanks for quick reply.
