### ISSUE TITLE
Weather command returning error.

### ISSUE THREAD

**Issue by siameseSerpent** [ForgeEssentials/ForgeEssentialsMain#1705]
When using /weather alone, FE returns the syntax for usage, but when attempting to add any additional information to the command, it returns this error.
http://pastebin.com/GVmQyQcP

**Comment by luacs1998** [comment]
Weather will need a relook.

Use /toggledownfall for the time being.

**Comment by olee** [comment]
You can use `/weather rain stop` as alias for `/toggledownfall` and disable rain completely with `/weather rain disable`.
