### ISSUE TITLE
Zone permissions with potion effects trouble

### ISSUE THREAD

**Issue by Psykrot** [ForgeEssentials/ForgeEssentialsMain#1708]
Hello, 

I'm trying to add specific potion effects to a desired zone. I messed up on the arguments for the effects and now the server console spams "Too few arguments for potion effects" every 2 seconds when someone is in that zone. 

I can't seem the get the ID:duration:amplifier correct. i.e. 10:8:1

I'm confused on how to reset this and I've entered so many permission commands regarding the issue that I've probably did more bad then good. Any help?

**Comment by olee** [comment]
Here is an example:
´´´´
/p global value fe.protection.zone.potion 1:8:4
´´´´
This will apply the potion effect [1] (Speed) for 8 seonds with a strength value of 4.

I hope this helps you, just try again and ask here *or better on IRC* if you still have question.

**Comment by Psykrot** [comment]
Thanks so much!
