### ISSUE TITLE
TP / TPPOS / THRU

### ISSUE THREAD

**Issue by paleym** [ForgeEssentials/ForgeEssentialsMain#1709]
/tp does not seem to work, when specifying the names of the two people, the second person simply has their view angle rotated.  /thru also rotates the view as well.  Also, can tppos please be implemented?  It is a bit annoying to have to use tpa to move around with tp and tppos not functional.

**Comment by siameseSerpent** [comment]
Afaik /tp <name> <x> <y> <z> functions similar to tppos and seems to work, however /tp <name> <name2> does not seem to work.

**Comment by olee** [comment]
Is this on 1.8 perhaps?
Simply doing `/tp player1 player2` should teleport player1 to player2.
Please also check if there is maybe an error in the console and check if you have other mods installed that might conflict with `/tp`.

**Comment by paleym** [comment]
Yes 1.8, just updated to FE build 31 and still seeing this issue

other mods:
Pixelmon 4.0.7
Dynmap 2.2-alpha-3 forge

Forge 1.8-11.14.3.1499-universal

The tp command simply rotates the view angle of the second player, but does not move either player.  There are no errors in console, and I don't believe that either Pixelmon or Dynmap have /tp commands that would interfere.

**Comment by olee** [comment]
**Please** ... tell beforehand if this is about 1.8 - main support / development is taken care of on 1.7.10

**Comment by paleym** [comment]
Thank you!  Also a note that /thru appears to have the same yaw/pitch error as /tp used to?  It does work properly but it rotates the view incorrectly.

Tested this on FE 32 as well, still has the view rotation there.

**Comment by olee** [comment]
We have no `/thru` command... at least not that I know...
