### ISSUE TITLE
Question - Has anyone else noticed random invisible spots that damage you?

### ISSUE THREAD

**Issue by DPxKnightxZero** [ForgeEssentials/ForgeEssentialsMain#1711]
So I guess after removing this mod the random invisible spots no longer are an issue but the question is why?

**Comment by olee** [comment]
Ehm... wth are you talking about? :laughing: 
Please give a more detailed explanation.... for now I can only guess either someone cursed you with another mod like Witchcraft etc., making you take damage or whatever....

**Comment by DPxKnightxZero** [comment]
Okay so basically while using forge essentials for world generation certain areas appear to cause players damage even if there is nothing there.

**Comment by olee** [comment]
Record a video or upload your world+modpack or something like that.
This is 99% not caused by FE and if I have not at least that amount of information, I cannot help you.
It might be better for you to ask for help at Minecraft Forums or somewhere else....

**Comment by DPxKnightxZero** [comment]
Okay I will do some work thanks for your input.
