### ISSUE TITLE
"/sellcommand @p minecraft:cobblestone 1 0 /wallet @p add 1" permissions issue 

### ISSUE THREAD

**Issue by blkwind** [ForgeEssentials/ForgeEssentialsMain#1712]
We just updated our server  to FE to 887 which fixed the permissions issue when using `/paidcommand @p 1000 /give @p minecraft:diamond 1` in a command block; however, now the command `/sellcommand @p minecraft:cobblestone 64 0 /wallet @p add 1` gives you the `you dont have permissions to use this command` error when trying to use the command block.

I tried updating to version 890 on a personal server to see if the issue had been addressed already and I still get the issue. Also tried assigning the Commandblock user to ops group to see if that would let the command block function and that also did not resolve the issue. Figured I would punt it your way and see what happens.

         Thanks 
       Blkwind "gentsgaming dev"

**Comment by olee** [comment]
`/paidcommand` and `/sellcommand` now use a virtual user for permission control.
This user is called `$FE_ECONOMY` and by default only has the global permissions and additionally the `command.give` permission.
You can do `/p user $FE_ECONOMY allow fe.economy.command.wallet.*` to give sellcommand the permission to modify wallets, until I fixed this.
After that stuff like this `/sc @p minecraft:stone 1 0 /wallet @p add 10` will work again.

**Comment by blkwind** [comment]
Awesome thanks olee!
