### ISSUE TITLE
java.lang.IllegalStateException: MixinBootstrap.register

### ISSUE THREAD

**Issue by acer86** [ForgeEssentials/ForgeEssentialsMain#1713]
Dear guzs,

thanks for this nice opportunity with essentials. But I couldn't let it run with Sponge, I have the folowing handling error, I attached a picture of the issue as well.

Thanks in advance.

My current mods in the sponge folder are.
(attached in the picture)
![mods](https://cloud.githubusercontent.com/assets/13914765/9423023/8996a96e-48b1-11e5-8ad2-ddfa5f526aa3.PNG)

Cheers,
acer86

![error sponge](https://cloud.githubusercontent.com/assets/13914765/9423015/26211018-48b1-11e5-8139-9cd29c0ced4f.PNG)

**Comment by olee** [comment]
See https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1689

**Comment by liach** [comment]
Actually fe devs need to update mixin first...
