### ISSUE TITLE
`Command god registered twice` upon consecutive `/feinfo reload`s

### ISSUE THREAD

**Issue by AnrDaemon** [ForgeEssentials/ForgeEssentialsMain#1715]
It seems that scripted commands are not deregistered before re-reading configuration by `/feinfo reload`.
Which results in `Command god registered twice` and similar messages popping in console starting from second reload.

**Comment by olee** [comment]
I don't even know if Minecraft knows the concept of **de**registering commands, but I'll see :laughing:

**Comment by luacs1998** [comment]
It's just a map - get access to the map, and remove the command.
