### ISSUE TITLE
Claiming land

### ISSUE THREAD

**Issue by M00FEN** [ForgeEssentials/ForgeEssentialsMain#1716]
I'm currently running a server with Forge Essentials and Pixelmon mods installed. I want my players to be able to claim land themselves, instead of an OP doing it. There are quite a few commands I have to execute to actually claim and define land and some of them will give the player too much power (amount of plots that can be claimed and the height of the plot) and I'd like to reduce this.

My question is: can I combine all the commands for land claiming and put in preset values for the amount of blocks that can be claimed etc? I want the player to be able to just grab the wooden axe (wand tool), select a plot and be done. It could automatically be called @p's plot or something.

**Comment by olee** [comment]
This is already possible with plots.
You just need to give players the select permissions for WorldEdit (I think I will make this the default soon). After that they can use `/plot claim` to claim a plot.

You can define limits with `/p global value fe.economy.plot.limit.count 3` or  `/p global value fe.economy.plot.limit.size 200` for example. Also the plot will automatically have the owners name, too.

**Comment by M00FEN** [comment]
Thanks for you reply olee. What I can't seem to figure out is which command exactly I have to allow for the users to use for them to be able to use the /plot claim command. I understand what most of the permissions in the permissions list allow, but not all of them. Is there a list available of what each permission allows exactly? :disappointed_relieved:

And I limited the size, so thanks for that! I didn't know I could set values for certain permissions like that hehe...

And yes, updating the wiki is probably wise :laughing:

**Comment by olee** [comment]
I think users should be able to use `/plot claim` by default.
Any if anything does not work, use `/p debug`.

**Comment by M00FEN** [comment]
That might be so, but I've disabled all permissions for all the users (except OPs), so I could control exactly which command every user can use. So yeah xD I'll try to check with /p debug later today, but I don't see how that would help me. Does /p debug give me the permission nodes that need to be allowed before a command can be used?

**Comment by olee** [comment]
@M00FEN one tip: 
Don't deny all permission. This does nor work well with FE and can cause a some problems if not done correctly. What works a lot better (and easier) is just disabling some of the root permissions by default like: `command.* = false` and `fe.commands.* = false`.

**Comment by M00FEN** [comment]
Hmm okay, I'll try enabling everything again then and just disable the ones I don't want. I should've documenten what I was doing lol. Anyway, thanks!

**Comment by olee** [comment]
np.
I wanted to try to think of a way to have a default-false system sometime anyway.
It will need some special handling which is why I will need to adjust some stuff in the code.

**Comment by M00FEN** [comment]
Alright. Good luck with that. I can't imagine all the work you put into this. I know my basics, but this is just way over my head haha.

**Comment by olee** [comment]
With the newest build you can do `/p group _GUESTS_ denydefault`.
This will setup the group in a way that by default any (new) permissions are denied by default.
After using that command (and maybe `/p save`) you can take a look at the permission file (`world/FEData/permissions/groups/_GUESTS_.txt`) to see all granted permissions and remove the ones you don't want.
