### ISSUE TITLE
Request: Issued commands listed in chat, but not full debug level

### ISSUE THREAD

**Issue by paleym** [ForgeEssentials/ForgeEssentialsMain#1719]
It would nice to see functionality where users entering commands would be listed in console without having to have full debug mode enabled.  The desired output would along the lines of:

<player> used command <cmd> <args>

So that console can be used to monitor who is doing what.

(I am using the 1.8 version of FE)

**Comment by olee** [comment]
Might be an optional feature.
For now commands are logged with playerlogger, however it can only be checked with FE remote yet.
