### ISSUE TITLE
Logblock & auto-AFK-Kick

### ISSUE THREAD

**Issue by peeepeeepeee** [ForgeEssentials/ForgeEssentialsMain#1720]
greetings!

so.. we have 2 problems..
Logblock dosent show us who or when blocks got changed.. we can only see how much changes happened

and the AFK-Kick, me as OP with the *=true - permission getting permanently afk-kicks if i stand still for ~ 5 minutes

other players can go afk without getting a kick..
i also tried 
essentials.afk.kickexempt=-1
but without success..

may anyone can help me?

**Comment by olee** [comment]
AFK problem is simple: Don't give `* = true` permission. Especially as OP - why would you do that?
Also this is **ForgeEssentials** and not Bukkit Essentials so that `essentials.afk.kickexempt` permission doesn't even exist.

**Comment by peeepeeepeee** [comment]
AFK-problem: i removed the permission for OP's

what about the logblock-problem?

**Comment by olee** [comment]
As I said - what "logblock" are you talking about?

**Comment by peeepeeepeee** [comment]
the Logblock which is included in Forge Essentials
(click with a clock on a block to see changes - theoretically)

**Comment by olee** [comment]
Ah... (where the hell did you get the name "logblock" from :confused:).

Anyway what you want then is the tool for playerlogger which is - as I already said above - the clock item. Just click a block to see the changes as described in the [wiki](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/playerLogger#checking-logs).

**Comment by peeepeeepeee** [comment]
okay, i played a bit with 'Playerlogger' / rollback

seems like it dosent like multiblock tools..
and metadatas are lost, even when the block (like a furnace or in my case ME-Drives) gets restored


when i hit a block with a clock, it shows me 'Showing recent block changes(clickes block):'

but it dosen't show me a name or a time when it got changed..

i can only see how much chanced there was when i hit the block multiple times it shows me 1-X times the same text (showing recent block changes:) and when there are no more block changes it tells me 'no more changes'

**Comment by olee** [comment]
First - be sure that you use latest FE build from Jenkins.
There was a bug in Playerlogger some time ago with the clock.

Rollback of metadata like chests and furnaces *should* work. If it does not, this is probably a bug.

Also please tell me if you are using MC 1.7.10 or 1.8.

**Comment by olee** [comment]
One note: You cannot restore chests etc. which were destroyed before the update.
