### ISSUE TITLE
//regen buildcraft

### ISSUE THREAD

**Issue by macDaddypro** [ForgeEssentials/ForgeEssentialsMain#1721]
Hey Guys,

first let me say great job with FE

I have an issue with //regen and buildcraft.

When I regen an area that was dug by a quarry the regenerated area doesn't work again with buildcraft. The new Quarry gets stuck over the area  like the chunk is corrupt.

Any ideas or fixes on this?

**Comment by olee** [comment]
This is not the WorldEdit issue tracker and this issue has nothing to do with FE.
Please report this on the WorldEdit issue tracker from @sk89q instead.

**Comment by macDaddypro** [comment]
THANK YOU.

**Comment by olee** [comment]
PS: In general I recommend restarting the server after using `//regen`.
At least that is what I always do because it always causes some derps.

**Comment by macDaddypro** [comment]
I will try that

**Comment by macDaddypro** [comment]
That works. Thank you for the tip.

in 1.6.4 worldedit //regen worked great with out having to restart.

I would always set up a Buildcraft quarry, dig, then //regen and dig again to compare.

im going to do that today with a restart after regen.

**Comment by olee** [comment]
To do that, instead of using regen just fill the pit with `//set stone` or whatever.

**Comment by macDaddypro** [comment]
Yes, glad you mentioned that. When I do that it works just fine without restarting the server.
