### ISSUE TITLE
[Multiworld] Every created world is empty

### ISSUE THREAD

**Issue by DerOli82** [ForgeEssentials/ForgeEssentialsMain#1722]
Looks similar to the loading bug (https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1613) but i get a void world direct after i've created a new world.

MC: 1.7.10
Forge: 10.13.4.1492
ForgeEssentials: 1.4.3.908

Forge Server + ForgeEssentials, no other mods and no configs changed exept main.cfg => debug=true.

**Comment by olee** [comment]
Yeah I need to tweak some stuff in multiworld.
There is a general problem with the world initialization that causes some problems.
The whole thing would be a lot easier if we would just move multiworld config to config files and make it static. But then one would have to restart the server to create / delete worlds etc.

Will take a look at this soon.

**Comment by krakel** [comment]
Today we was making same tests on our empty worlds. The collision works very well. A testforblock detect the correkt block at the test position. But all blocks are complete invisible.
