### ISSUE TITLE
zone permissions glitch issue

### ISSUE THREAD

**Issue by gatekeeper258** [ForgeEssentials/ForgeEssentialsMain#1726]
p group members zone WORLD_-1 prefix [nether]
p group members zone WORLD_1 prefix [end]
p group members zone WORLD_0 prefix [over]

it only saves the last command to the members.txt file as a prefix [over]
when in the end or nether the prefix does not change. still [over]

Are there any logs or configs I can show to validate this to yall?

**Comment by olee** [comment]
Fixed - you need to set the permissions again (run the commands you posted once again).
