### ISSUE TITLE
suggestion: option to define kits via config file

### ISSUE THREAD

**Issue by Starless2001** [ForgeEssentials/ForgeEssentialsMain#1727]
it should be possible to define kits via config file, like bukkit essentials does. it should be an option. kits could be defined either as they are defined now or through the config.

**Comment by olee** [comment]
You can define them in the files.
Just check `world/FEData/json/Kit` for the kits (after you defined at least one kit).

**Comment by Starless2001** [comment]
got it, thanks! someone should put that in the wiki though.
