### ISSUE TITLE
CoFH fake player seems to be "null" instead of "[cofh]"

### ISSUE THREAD

**Issue by Robijnvogel** [ForgeEssentials/ForgeEssentialsMain#1729]
Any ideas as to how and why this happens?

https://github.com/CoFH/Feedback/issues/815

**Comment by olee** [comment]
Was not really an issue - the username was just not correctly saved but the permissions still worked.

**Comment by Robijnvogel** [comment]
Before, I only believed that either issues or intended behaviour existed.
Are you telling me that there is some grey area in between those? :)

**Comment by olee** [comment]
The UUID is what is important for the permissions to work.
The username is in most cases only used for display purposes (and to use it in /p command for example).

**Comment by Robijnvogel** [comment]
Ah ok, so you initially thought it might be broken more than it actually was? I am glad that this very specific and small issue could be solved though. You are doing great work.

**Comment by olee** [comment]
With https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/0a5b4c59f922bde78a1b312d5dbd2b197b30e1db the FakePlayers are not correctly registered, too.
That will make them show up in `FEData/permissions/players`.
