### ISSUE TITLE
Without permission, still able to teleport with Voxelmap 

### ISSUE THREAD

**Issue by Robijnvogel** [ForgeEssentials/ForgeEssentialsMain#1731]
I am playing with a combined Forge and Liteloader modpack with Voxelmap (only client sided) and Forge Essentials (only server sided).

I made a new group called members and removed almost all permissions from the _guest_ group.
If I deop myself and am only in the group "members" (which should have the default permissions), I am able to teleport using Voxelmap. (open the fullscreen map, right click somewhere on the map and click "teleport to")

It says "You do not have permission to use this command" in the chat, but it teleports you anyway:
"
[18:47:58] [Client thread/INFO]: [CHAT] You do not have permission to use this command
[18:47:58] [Client thread/INFO]: [CHAT] Teleporting. Please stand still for 3 seconds.
[18:48:01] [Client thread/INFO]: [CHAT] Teleported.
"

When I put myself in the group _ guests_, however, this teleport function does not work.

How do I disable this vague teleport permission? And if possible it would be a good idea to put this restriction in the list of default restrictions as well.

**Comment by olee** [comment]
Read the tutorial on the [WIKI](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/Permissions-tutorial).
The default way to solve such problems is to use `/p debug`.
It will show you which permissions are checked when the teleport is started.
I guess if you use the teleport from Voxelmap, it might actually use two commands where only the first is blocked maybe (resulting in the "You do not have permission to use this command") and the second doing the teleport.

If you still have problems solving it with `/p debug`, ask here again.

**Comment by Robijnvogel** [comment]
However fe.teleport.tp is false by default,
fe.teleport.tppos seems to be true.

Maybe this should be changed? Or is this meant to be some kind of legitimate teleport that mods like Mystcraft use?

**Comment by olee** [comment]
That's why I said check it with `/p debug`.
That will tell us more than just some speculations...

**Comment by Robijnvogel** [comment]
Thank you for helping.
I am sorry for not reading first, but ironically I just can't find the time, because I am to busy answering people who don't bother to read first...

Will anything be changed though?
This fe.teleport.tppos being true by default is not intended behaviour, is it?

**Comment by olee** [comment]
Probably... not.
Will check it.
