### ISSUE TITLE
Performance Upgrade for Backup

### ISSUE THREAD

**Issue by aschmois** [ForgeEssentials/ForgeEssentialsMain#1734]
Close if I'm wrong (I may very well be).

The backup task is checked every tick for tasks (for loop). This doesn't seem to be very nice on performance. There are options here to schedule tasks for Java.

ScheduledExecutorService is a good starting point. Since you probably want to wait for a tick to actually do the backup, the scheduledexecutorservice can add a one time backup run at the exact periodic time and then the tick will loop through pending tasks; this for loop is fine because it will only happen for a few ticks before the backup occurs.

You also have the option of using a third party library, Quartz comes to mind, but this is most likely not needed as it's a very robust solution for a simple problem.

Minecraft has WAY too much already running on its game thread, a little threading won't hurt here and there ;)

**Comment by luacs1998** [comment]
He mentioned this on IRC, I requested he make the issue for further follow-up.

**Comment by olee** [comment]
Backups run in the background and what you described there does not match how backups are handled.
