### ISSUE TITLE
Server crash on startup - no other mods

### ISSUE THREAD

**Issue by KKbuilder** [ForgeEssentials/ForgeEssentialsMain#1735]
I have minecraft 1.7.1 forge server, brand new unedited except for forge essentials. Drop forge essentials 934 in the mods folder and it starts up for a couple seconds then crashes. Tried looking for similar issues in forums and couldn't find any. Here is the crash report.

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 9/7/15 11:49 PM
Description: Exception in server tick loop

cpw.mods.fml.common.MissingModsException
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:244)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:472)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by olee** [comment]
This is most definitely not not caused by FE.
In the full log it would be written which mod is missing so you will have to post that.

If you post it here, someone can probably point out what you are missing.

**Comment by KKbuilder** [comment]
Ok thank you. Here is the full attached crash report, I feel I am missing something really, really, simple but I cant figure out what. 

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 9/7/15 11:49 PM
Description: Exception in server tick loop

cpw.mods.fml.common.MissingModsException
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:244)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:472)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode, sharing), Oracle Corporation
	Memory: 40327008 bytes (38 MB) / 124858368 bytes (119 MB) up to 259522560 bytes (247 MB)
	JVM Flags: 0 total; 
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 5 mods loaded, 5 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded
	FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230-universal.jar) Unloaded
	Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230-universal.jar) Unloaded
	ForgeEssentials{1.4.3} [Forge Essentials] (forgeessentials-1.7.10-1.4.3.934-server (2).jar) Unloaded
	worldedit{6.1.1-SNAPSHOT} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dist.jar) Unloaded
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by olee** [comment]
This is still not the full log.
What I want from you is the fml-server-latest.log for example.
And do **not** just post it in here.
Use pastebin or a gist.github.com for that.

**Comment by KKbuilder** [comment]
My apologies, I am new to the website and to working with a server. Here is the latest server log from pastebin. It appears to crash shorting after attempting to load world edit, or am I reading that wrong?

http://pastebin.com/raw.php?i=mGvHx8bK

**Comment by olee** [comment]
`The mod ForgeEssentials (Forge Essentials) requires mod versions [Forge@[10.13.2.1258,)] to be available`

... I don't think I need to say anything else.... :sweat:
