### ISSUE TITLE
Better backup proposal

### ISSUE THREAD

**Issue by Zethalion** [ForgeEssentials/ForgeEssentialsMain#1737]
Hi! Thanks for making the best management mod for a forge server ever. I enjoy your mod since I ran an 1.5.2 server. I always used the backup module but starting with 1.7.10 I decided to use another backup because a full backup of a modded world every time really takes some disk space.

One time I ran a server under MineOS 0.6 (http://minecraft.codeemo.com/mineoswiki/index.php?title=Main_Page). That Linux tool offered something interesting when it came to back-ups. I could make a full back-up and every next one would be a full back-up as well and the previous one was reduced to an inverse incremental. The third back-up would be a full one again and the second one would be also an inverse incremental of the third one, still keeping the first one valid in it's small state. 

An example:
3rd full backup 1 GB in size
  * 2nd reverse incremental back-up 10 MB in size

    Only stores changes compared with 3rd back-up
    * 1st reverse incremental back-up 10 mb in size

       Only stores changes compared with 2nd back-up

In this way I could tell it to keep 100 back-ups with only one full back-up which is the latest and easely could be a few GB's and 99 incrementals which each takes just a few MB's of disk space. When the 101st back-up is made, the very 1st one would be deleted.

Would it be possible to enhance the back-up module with this kind of incrementing? It would really save a lot of disk space and still having the option to roll-back a long time if ever needed.

**Comment by olee** [comment]
Compared to the development "cost" necessary, storage space costs much less.
This is why we will not - at least not in the foreseeable future - implement such a feature.
Sorry.

**Comment by Zethalion** [comment]
If I get you a C# solution, could you translate the logic behind it into java? It would be awesome.

**Comment by olee** [comment]
The problem is how to actually create the incremental backups (compare hashes, exclude files) and also provide an easy way to restore these partial backups.
This is not an easy task and also language dependent.
And that's why I'm gonna cite what I said above:

> Compared to the development "cost" necessary, storage space costs much less.
