### ISSUE TITLE
Player Cababilities "MayBuild"

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [ForgeEssentials/ForgeEssentialsMain#1739]
As I saw in an old issue, this is how you set capabilities:

    NBTTagCompound tagCompound = new NBTTagCompound();
        playerMP.capabilities.writeCapabilitiesToNBT(tagCompound);
        tagCompound.getCompoundTag("abilities").setTag("flySpeed", new NBTTagFloat(flySpeed));
        tagCompound.getCompoundTag("abilities").setTag("walkSpeed", new NBTTagFloat(walkSpeed));
        playerMP.capabilities.readCapabilitiesFromNBT(tagCompound);
        playerMP.sendPlayerAbilities(); 

But how do you set a boolean tag? I want to change if the player can build or not no matter what gamemode he is at.

**Comment by olee** [comment]
Use permissions to control if a player can build or not.
E.g., `/p user <player> deny fe.protection.break.* fe.protection.place.*`
