### ISSUE TITLE
Feature Request: In-game Hotkey to allow server admins to config perms on-the-fly without typing

### ISSUE THREAD

**Issue by PitchBright** [ForgeEssentials/ForgeEssentialsMain#1742]
A configgable key such as CapsLock would be a great way for admins to let FE know they want to change the perm of whatever it is they are accessing/touching/holding/clicking.

If the admin configures the Hotkey with a command such as '/p hotkey <group> deny fe.protection.break.'  they would then be able to "Perm-as-you-Play", with the hotkey down (CapsLock would be great because it doesn't require being held down constantly).

Each click would toggle between allow and deny.

Admins would be able to walk around their world, clicking on things they do or don't want a group to use. No typing required!  :-)

**Comment by PitchBright** [comment]
Note: discussed tie-in with Permission Scheduler.

**Comment by olee** [comment]
Added a feature taking care of this in https://github.com/ForgeEssentials/ForgeEssentialsMain/commit/d9d4cf5ddaae4b2fb575510121b67dc79e324bce
