### ISSUE TITLE
FTB Infinity 1.10.1 Compatability

### ISSUE THREAD

**Issue by TopStiGear** [ForgeEssentials/ForgeEssentialsMain#1750]
I have updated fastcraft to 'fastcraft-1.22-ctest14' and also changed the forge version to 'forge-1.7.10-10.13.4.1448-1.7.10-universal' tried to launch the server and it will not run.

I am using the latest 'forgeessentials-1.7.10-1.4.3.936-server' in the mods folder.

What am I doing wrong and how can I fix this?
I am wanting to use this mod as I cannot find a plugin based server to work for 1.7.10.

Thanks TopStiGear

**Comment by olee** [comment]
LOGS!
(and please as pastebin / gist)

**Comment by Zethalion** [comment]
It's Thaumcraft in that pack. It's not compatible with Forge 1448.

**Comment by luacs1998** [comment]
As @Zethalion said - remove thaumcraft.

Reopen if it still happens (and with crash logs!)

**Comment by TopStiGear** [comment]
I Have Removed Thaumcraft and it still crash's.
Here is a crash report with Thaumcraft: http://pastebin.com/cGS6fzuZ
Here is a crash report without thaumcraft: http://pastebin.com/s6DSjae4

**Comment by TopStiGear** [comment]
Also Thaumcraft works by default in the FTB Infinity Pack running Forge 1448 I mistakenly put the wrong forge info as I changed to use 1258 for this mod to work

**Comment by TopStiGear** [comment]
"open"
