### ISSUE TITLE
IRC Bot hangs server on McMyAdmin restart

### ISSUE THREAD

**Issue by PitchBright** [ForgeEssentials/ForgeEssentialsMain#1752]
http://pastebin.com/a0KTn6Vb

**Comment by luacs1998** [comment]
Scheduled restarts by...

**Comment by PitchBright** [comment]
McMyAdmin

**Comment by PitchBright** [comment]
Note: 
I'm seeing it happen even when I press the Restart button for a manual restart.

**Comment by PitchBright** [comment]
Also Note: same error occurs when using the /Stop command in-game.

**Comment by luacs1998** [comment]
On further investigation, it seems that the only fix is to upgrade pircbotx to 2.x, which will likely require considerable changes.

**Comment by olee** [comment]
I guest you can just try out replacing the library and see how much needs to be adjusted.
I don't think it would be hard to patch that simple code.

**Comment by luacs1998** [comment]
Not as simple as you think, but I managed to do it in 87337514b848f77f03dc209d6dd9c992f93b0b05

**Comment by luacs1998** [comment]
@PitchBright can you try out [this build](https://www.mediafire.com/?dz21gj61npv99f3) and see if the issue still persists?

**Comment by PitchBright** [comment]
It works.

**Comment by luacs1998** [comment]
Will be closed when #1764 is merged.
