### ISSUE TITLE
[RE-OPEN] FTB Infinity 1.10.1 Compatability

### ISSUE THREAD

**Issue by TopStiGear** [ForgeEssentials/ForgeEssentialsMain#1753]
I have updated fastcraft to 'fastcraft-1.22-ctest14' and also changed the forge version to 'forge-1.7.10-10.13.2.1258-universal' tried to launch the server and it will not run.

I am using the latest 'forgeessentials-1.7.10-1.4.3.936-server' in the mods folder.

What am I doing wrong and how can I fix this?
I am wanting to use this mod as I cannot find a plugin based server to work for 1.7.10.

Thanks TopStiGear

I Have Removed Thaumcraft and it still crash's.
Here is a crash report with Thaumcraft: http://pastebin.com/cGS6fzuZ
Here is a crash report without thaumcraft: http://pastebin.com/s6DSjae4

Also Thaumcraft works by default in the FTB Infinity Pack running Forge 1448 I mistakenly put the wrong forge info as I changed to use 1258 for this mod to work

**Comment by Zethalion** [comment]
You must remove all mods depending on Thaumcraft after removing Thaumcraft "cpw.mods.fml.common.MissingModsException" says you didn't.

Then in the crashlog with Thaumcraft the same error shows up telling there is another mod which needs another mod which is not available. Which one you'll have to find yourself.
