### ISSUE TITLE
Cant seem to get zone block place / break permissions to work

### ISSUE THREAD

**Issue by Baaleos** [ForgeEssentials/ForgeEssentialsMain#1754]
Defined an area called 'Baaleos_Castle'
I know the area / zone definition is correct because when I enter the zone, it gives me the welcome message allocated by the 'entry' node.

I then do  (note - I have tried various combinations of deny / false to try and get it to stop the breaking / placing)
/feperm group _GUESTS_ zone 10 deny *
/feperm group _GUESTS_ zone 10 deny fe.protection.interact.*
/feperm group _GUESTS_ zone 10 deny fe.protection.break.*
/feperm group _GUESTS_ zone 10 deny fe.protection.place.*

I use /protectdebug  and it shows that when I am breaking things two permissions are checked.
fe.protection.interact.minecraft.dirt
fe.protection.break.minecraft.dirt

However my understanding is that if I have the wildcard on the .* it should prevent interaction with anything.

In any case -I have tried doing the specific tile type as well.
/feperm group _GUESTS_ zone 10 deny fe.protection.interact.minecraft.dirt

no effect.
I tried /p save then /p reload to see if that makes a difference.

Also - the op command seems to be available to guests in my server...
Even though I have tried to deny it to 'all' .

The tutorial on the wiki for setting up prefixes is also incorrect- it advises the user to use 
/p group _GUESTS_ prefix set &r[&2GUEST&r]

but it appears that we actually need to use 
/p group _GUESTS_ prefix &r[&2GUEST&r]

My ALL permission is this (FOR SERVER WIDE)
#Permissions for group _ALL_
#DO NOT MODIFY OR REMOVE fe.internal PERMISSIONS UNLESS YOU KNOW WHAT YOU DO!
#After you modified permissions in this file, remember to directly run "/feperm reload", or the changes get overwritten next time permissions are saved by the server.
#Sat Sep 12 19:43:38 UTC 2015
fe.internal.group=true
fe.internal.group.priority=0
command.op=false
fe.remote.chat.send=false
some.test.permission=true

My Zone permissions for the _GUEST_ AND ALL  group

#Permissions for group _GUESTS_
#DO NOT MODIFY OR REMOVE fe.internal PERMISSIONS UNLESS YOU KNOW WHAT YOU DO!
#After you modified permissions in this file, remember to directly run "/feperm reload", or the changes get overwritten next time permissions are saved by the server.
#Sat Sep 12 19:43:38 UTC 2015
*=false

#Permissions for group _ALL_
#DO NOT MODIFY OR REMOVE fe.internal PERMISSIONS UNLESS YOU KNOW WHAT YOU DO!
#After you modified permissions in this file, remember to directly run "/feperm reload", or the changes get overwritten next time permissions are saved by the server.
#Sat Sep 12 19:52:48 UTC 2015
fe.internal.zone.entry=Welcome to Baaleos Castle     <-- This does play when entering zone
fe.protection.break.*=false
fe.protection.interact.*=false
fe.protection.place.*=false

**Comment by Baaleos** [comment]
Note  : Using build #934

**Comment by olee** [comment]
So you already found the  problem?
Let me guess - you weren't as a guest on the server (part of some other group)?
