### ISSUE TITLE
Help (German)

### ISSUE THREAD

**Issue by UDOzockt** [ForgeEssentials/ForgeEssentialsMain#1755]
Hallo,
ich habe ein Problem. Ich brauche die Funktion, dass wenn man eine Zone betritt, Commands ausgeführt werden können, um zum Beispiel den Spielmodus zu ändern, oder Portale zu bauen. Gibt es diese Funktion, wenn ja wie geht das?

Kontakt: airpromc.jimdo.com
TS:airprots.minecraftserver.de

**Comment by luacs1998** [comment]
I don't speak German - @olee ?

**Comment by olee** [comment]
Spielmodus lässt sich direkt durch `fe.protection.gamemode = creative` als permission steuern.
Commands beim betreten einer Zone gehen ähnlich - einfach mal einen Blick in die [PermissionList.txt](https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/PermissionList.txt) werfen und nach `fe.protection.zone` schauen.

Wenn du sonst noch fragen hast, komm auf meinen TS analsheep.de.
Bin dort fast 24/7 erreichbar.

**Comment by UDOzockt** [comment]
Wie genau sieht das Command aus, wenn ich beispielsweise auf einer Zone "Teleporter" alle die die Zone betreten zu einer anderen MW teleportieren will?
