### ISSUE TITLE
[RE-OPEN AGAIN] FTB Infinity 1.10.1 Compatability

### ISSUE THREAD

**Issue by TopStiGear** [ForgeEssentials/ForgeEssentialsMain#1756]
I have updated fastcraft to 'fastcraft-1.22-ctest14' and also changed the forge version to 'forge-1.7.10-10.13.2.1258-universal' tried to launch the server and it will not run.
I am using the latest 'forgeessentials-1.7.10-1.4.3.936-server' in the mods folder.

Okay I am not wanting to delete any mods from the pack as this would just cause confusion to people trying to access the server and I do not want to change the FTB modpack as I am wanting to make a server where people just download the pack and go straight to the server without having to do this that and the other to access it.

Is there a way to get ForgeEssentials to work with the whole of the FTB Infinity 1.10.1 modpack?

Also the use of closing an issue with a one sentence answer and saying 'if that doesn't work re open it' then closing it we have no way to reopen a ticket we can only post new tickets so wait until a Fix has been Found and Confirmed before closing the ticket.
Thanks TopStiGear

**Comment by paintballlaws** [comment]
Don't use fastcraft is all over the install for this mod that's why he closed it

**Comment by TopStiGear** [comment]
Fastcraft 1.21 is default with the pack but updating it to 1.22 on server side will still work with fastcraft 2.1 client side and is compatible with forgeessentials. They are closing it saying thaumcraft doesn't work and even taking out thaumcraft doesn't make the pack work its ForgeEssentials itself that is causing the problem and what is needed to be fixed to work with the modpack.

**Comment by olee** [comment]
Can you **PLEASE** stop opening new issues and keep your replies in #1750?
Then we *might* consider to further help you.
