### ISSUE TITLE
[Snooper] feature requests

### ISSUE THREAD

**Issue by LargePrime** [ForgeEssentials/ForgeEssentialsMain#520]
history for; bans, mutes, kicks, ipbans, ip, money, claimed blocks/chuks, ranks, promotions, demotions, Chat, blocks,

Perhaps bans, mutes, kicks, ipbans should include Who banned and the reason given.

Totals for ;Time logged in, blocks altered, chat characters, % time logged in since joined, # of /nick changes, 

Is a list better than busting then into individual requests?

Probably highest priority should be ban history

**Comment by luacs1998** [comment]
Snooper module has been removed already, @olee if you're interested in adding this to remote feel free.

**Comment by 123Lin** [comment]
GOOD！
