### ISSUE TITLE
[Request] /rollback enhancement

### ISSUE THREAD

**Issue by profjb** [ForgeEssentials/ForgeEssentialsMain#604]
Ive noticed the /pl get commmand has been very helpfull as same as the mySQL logging. However I feel a time command at least should be implemented per player. e.g.
/rollback profjb 10[d/h/m/s] clear

And maybe even the introduction of /rollback [number]r profjb clear. as a radius command. E.g. below.

/rollback profjb 16h 60r

Just a suggestion really :). Feel free to take your time on this if you wish it implement it, please don't rush on it though :P. Please focus mainly on bugfixes :).

**Comment by olee** [comment]
Closed in regards to https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1306
