### ISSUE TITLE
Arrested like functionality

### ISSUE THREAD

**Issue by lonewolf896** [ForgeEssentials/ForgeEssentialsMain#687]
Basicly arrested is a bukkit mod that allows me as a server admin to have my server automatically grab a persons group/rank/status/etc from a forum in game upon entering the server.  This allows very easy administration of large communities.

If you could implement this, the forge using part of my community would immediately switch to forgeEssentials.

**Comment by olee** [comment]
Closing.
This can be achieved if you set the required player-group via remote by PHP etc.
(e.g., java lib https://github.com/ForgeEssentials/FERemoteLib)
