### ISSUE TITLE
More Economy possibilities

### ISSUE THREAD

**Issue by Nowmane** [ForgeEssentials/ForgeEssentialsMain#847]
Would it be possible to add more possibilities to the Economy-Part? Actually we need to use commandblocks togeather with removewallet but yo get negative money when you dont havy any more money and i think thats not really useful because then the players can buy really much things and dont need money because they get more and more negative money what must be looked for in every player-data. I hope a better model, maybe a bit like iconomy or such things would be nide.

**Comment by luacs1998** [comment]
I think that this can be further elaborated on in #1189. Closing.
