### ISSUE TITLE
PlayerLogger database records limiting by age

### ISSUE THREAD

**Issue by Donillo** [ForgeEssentials/ForgeEssentialsMain#849]
I am suggesting add automatic removing for old records created by PlayerLogger module, like as Backups module able to remove old backups (one week old by default). It would help keep MySQL database small.

**Comment by luacs1998** [comment]
Is this planned for new playerlogger?

**Comment by olee** [comment]
I'd say could be planned, but I don't think it's really necessary as the new DB layout is very optimized and even running a server with many players for years should only produce a database of a few MB.
If one really wants to remove old entry, use an external SQL editor to send a query to the database or just delete it once a year when you restart the server (if you are sure the state of the world is good as it is).
Auto-remove for backups (which are very huge) is understandable, but for PL we can ignore it until someone really reports a database exceeding at least 50-100 MB.
