### ISSUE TITLE
PlayerLogger /rb syntax? Not working

### ISSUE THREAD

**Issue by Pwnsaucier** [ForgeEssentials/ForgeEssentialsMain#955]
FE: 1.3 RC1 build #22
Forge 965
MC 1.6.4

Just testing the playerlogger module at the moment and discovering what it can and can't do in it's current state. I've got it outputting basic block changes and interactions to a mysql db and I can use /pl enable to view block history in game, which is most of the basic functionality that I need.

However when testing the rollback (/rb) features, I can't seem to get it to work properly. When I try /rb rollback Pwnsaucier 10r 1h it spits back: "You have to provide a username!" I tried a dozen variations on the syntax without success, going from the in game help: http://i.imgur.com/33y2xWc.jpg

I could be doing it wrong (likely). Can't seem to find command examples anywhere in the documentation: https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/playerLogger

**Comment by luacs1998** [comment]
/rollback syntax changed with the new PL implementation. As such, this issue is now invalid.

**Comment by Fighter777** [comment]
luacs, you can't write a command list please ? :)

**Comment by luacs1998** [comment]
It's like, three hours old? :D

**Comment by Fighter777** [comment]
hum maybe... xD

**Comment by olee** [comment]
This is the new `/rollback` syntax (alias `/rb`)
You could have also just run `/rb help` to get this.
````
/rb help : Print help
/rb : Start Rollback
/rb start : same as above
/rb + : Go further back in time (increase reverted changes)
/rb - : Go forward in time (decrease reverted changes)
/rb play [speed] : Playback changes in reverse from current time (same command to pause again)
/rb cancel : Cancel rollback
/rb confirm : Confirm rollback and apply changes
````

**Comment by olee** [comment]
https://github.com/ForgeEssentials/ForgeEssentialsMain/wiki/PlayerLogger
